<?php
/**
 * @copyright Copyright (c) 2014-2015 Handbid Inc.
 * @category handbid
 * @package Handbid2-WordPress
 * @license Proprietary
 * @link http://www.handbid.com/
 * @author Master of Code (worldclass@masterofcode.com)
 */

$is_local = $this->get("is_local");
?>
<div class="wrap">
    <h2>Handbid</h2>
    <form method="post" action="options.php">
        <?php settings_fields('handbid-admin'); ?>
        <?php do_settings_fields('handbid-admin-dashboard', 'handbid-admin'); ?>
        <table class="form-table">
            <tr valign="top">
                <th scope="row"><?php echo('Rest Api Url ( Default : https://handbid.com )'); ?></th>
                <td><input type="text" name="handbidRestEndpoint"
                           value="<?php echo get_option('handbidRestEndpoint', 'https://handbid.com'); ?>"/></td>
            </tr>

            <tr valign="top">
                <th scope="row"><?php echo('Facebook App Id ( For Comments )'); ?></th>
                <td><input type="text" name="handbidFacebookAppId"
                           value="<?php echo get_option('handbidFacebookAppId'); ?>"/></td>
            </tr>
            <tr valign="top">
                <th scope="row"><?php echo('Default Auction Key'); ?></th>
                <td><input type="text" name="handbidDefaultAuctionKey"
                           value="<?php echo get_option('handbidDefaultAuctionKey'); ?>"/></td>
            </tr>
            <tr valign="top">
                <th scope="row"><?php echo('Default Organization Key'); ?></th>
                <td><input type="text" name="handbidDefaultOrganizationKey"
                           value="<?php echo get_option('handbidDefaultOrganizationKey'); ?>"/></td>
            </tr>

            <tr valign="top">
                <th scope="row"><?php echo('HandbidJS'); ?></th>
                <td><input type="text" name="handbidJs"
                           value="<?php echo get_option('handbidJs', 'https://handbid-js-handbid.netdna-ssl.com/handbid.js?cachebuster=234234'); ?>"/></td>
            </tr>
            <?php if($is_local){ ?>
            <tr valign="top">
                <th scope="row"><?php echo('My Organization'); ?><br/></span></th>
                <td><input type="text"  name="handbidShowOnlyMyOrganization"
                           value="<?php echo get_option('handbidShowOnlyMyOrganization'); ?>"/></td>
            </tr>
            <?php } ?>
            <tr valign="top">
                <th scope="row"><?php echo('CDN Endpoint'); ?></th>
                <td><input type="text" name="handbidCdnEndpoint"
                           value="<?php echo get_option('handbidCdnEndpoint'); ?>"/></td>
            </tr>
            <tr valign="top">
                <th scope="row"><?php echo('Columns count on auctions and organizations pages'); ?></th>
                <td><select type="text" name="handbidDefaultColCount">
                        <?php
                        $count = (int) get_option('handbidDefaultColCount');
                        $count = ($count) ? $count : 4;
                        for($i = 1; $i < 5; ++$i){
                            echo "<option value='".$i."' ".selected($count, $i, false).">".$i."</option>";
                        }?>
                        </select></td>
            </tr>
            <tr valign="top">
                <th scope="row"><?php echo('Columns count on auction details page'); ?></th>
                <td><select type="text" name="handbidDefaultColCountItem">
                        <?php
                        $count = (int) get_option('handbidDefaultColCountItem');
                        $count = ($count) ? $count : 3;
                        for($i = 1; $i < 5; ++$i){
                            echo "<option value='".$i."' ".selected($count, $i, false).">".$i."</option>";
                        }?>
                        </select></td>
            </tr>
            <tr valign="top">
                <th scope="row"><?php echo('Auctions and Organizations per page'); ?></th>
                <td><input type="number" name="handbidDefaultPageSize"
                           value="<?php $count = (int) get_option('handbidDefaultPageSize') ; echo ($count) ? $count : 25 ; ?>"/></td>
            </tr>

        </table>
        <?php submit_button(); ?>

    </form>

</div>