<?php
/**
 * @copyright Copyright (c) 2014-2015 Handbid Inc.
 * @category handbid
 * @package Handbid2-WordPress
 * @license Proprietary
 * @link http://www.handbid.com/
 * @author Master of Code (worldclass@masterofcode.com)
 */

$is_local = $this->get("is_local");
?>
<div class="wrap">
    <h2>Handbid</h2>
    <form method="post" action="options.php">
        <?php settings_fields('handbid-admin'); ?>
        <?php do_settings_fields('handbid-admin-dashboard', 'handbid-admin'); ?>
        <table class="form-table">
            <tr valign="top">
                <th scope="row"><?php echo('Rest Api Url ( Default : https://handbid.com )'); ?></th>
                <td><input type="text" name="handbidRestEndpoint"
                           value="<?php echo get_option('handbidRestEndpoint', 'https://handbid.com'); ?>"/></td>
            </tr>
            <tr valign="top">
	            <?php $stripeMode = get_option('handbidStripeMode', 'test');?>
                <th scope="row"><?php echo('Stripe Mode'); ?></th>
                <td>
	                <label for="handbidStripeMode1"><input type="radio" id="handbidStripeMode1" name="handbidStripeMode" value="test" <?php checked($stripeMode, "test");?>/> Test</label>&nbsp;&nbsp;&nbsp;&nbsp;
	                <label for="handbidStripeMode2"><input type="radio" id="handbidStripeMode2" name="handbidStripeMode" value="live" <?php checked($stripeMode, "live");?>/> Live</label>
                </td>
            </tr>

            <tr valign="top">
                <th scope="row"><?php echo('Handbid Sockets URL'); ?></th>
                <td><input type="text" name="handbidSocketUrl"
                           value="<?php echo get_option('handbidSocketUrl', 'https://socket.hand.bid'); ?>"/></td>
            </tr>
            <tr valign="top">
                <?php $forceRefresh = get_option('handbidForceRefresh', 'no');?>
                <th scope="row"><?php echo('Force page refresh after each Bid and MaxBid'); ?></th>
                <td>
                    <label for="handbidForceRefresh1"><input type="radio" id="handbidForceRefresh1" name="handbidForceRefresh" value="no" <?php checked($forceRefresh, "no");?>/> No</label>&nbsp;&nbsp;&nbsp;&nbsp;
                    <label for="handbidForceRefresh2"><input type="radio" id="handbidForceRefresh2" name="handbidForceRefresh" value="yes" <?php checked($forceRefresh, "yes");?>/> Yes</label>
                </td>
            </tr>
            <tr valign="top">
                <?php $forceRefreshAfterPurchases = get_option('handbidForceRefreshAfterPurchases', 'no');?>
                <th scope="row"><?php echo('Force page refresh after each Purchase'); ?></th>
                <td>
                    <label for="handbidForceRefreshAfterPurchases1"><input type="radio" id="handbidForceRefreshAfterPurchases1" name="handbidForceRefreshAfterPurchases" value="no" <?php checked($forceRefreshAfterPurchases, "no");?>/> No</label>&nbsp;&nbsp;&nbsp;&nbsp;
                    <label for="handbidForceRefreshAfterPurchases2"><input type="radio" id="handbidForceRefreshAfterPurchases2" name="handbidForceRefreshAfterPurchases" value="yes" <?php checked($forceRefreshAfterPurchases, "yes");?>/> Yes</label>
                </td>
            </tr>
            <tr valign="top">
                <?php $profileDashboardOn = get_option('handbidDisplayProfileDashboardOn', array("other", "auction", "auction-item"));
                ?>
                <th scope="row"><?php echo('Display Profile Dashboard On'); ?>:</th>
                <td>
	                <label for="handbidDisplayProfileDashboardOn2"><input type="checkbox" id="handbidDisplayProfileDashboardOn2" name="handbidDisplayProfileDashboardOn[]" value="auction" <?php checked(in_array("auction", $profileDashboardOn), true);?>/> Auction Page</label>&nbsp;&nbsp;&nbsp;&nbsp;
	                <label for="handbidDisplayProfileDashboardOn3"><input type="checkbox" id="handbidDisplayProfileDashboardOn3" name="handbidDisplayProfileDashboardOn[]" value="auction-item" <?php checked(in_array("auction-item", $profileDashboardOn), true);?>/> Auction Item Page</label>&nbsp;&nbsp;&nbsp;&nbsp;
                    <label for="handbidDisplayProfileDashboardOn1"><input type="checkbox" id="handbidDisplayProfileDashboardOn1" name="handbidDisplayProfileDashboardOn[]" value="other" <?php checked(in_array("other", $profileDashboardOn), true);?>/> All Other Pages</label>
                </td>
            </tr>

            <tr valign="top">
                <th scope="row"><?php echo('Facebook App Id ( For Comments )'); ?></th>
                <td><input type="text" name="handbidFacebookAppId"
                           value="<?php echo get_option('handbidFacebookAppId'); ?>"/></td>
            </tr>
            <tr valign="top">
                <th scope="row"><?php echo('Default Auction Key'); ?></th>
                <td><input type="text" name="handbidDefaultAuctionKey"
                           value="<?php echo get_option('handbidDefaultAuctionKey'); ?>"/></td>
            </tr>
            <tr valign="top">
                <th scope="row"><?php echo('Default Organization Key'); ?></th>
                <td><input type="text" name="handbidDefaultOrganizationKey"
                           value="<?php echo get_option('handbidDefaultOrganizationKey'); ?>"/></td>
            </tr>
            <?php if($is_local){ ?>
            <tr valign="top">
                <th scope="row"><?php echo('My Organization'); ?><br/></span></th>
                <td><input type="text"  name="handbidShowOnlyMyOrganization"
                           value="<?php echo get_option('handbidShowOnlyMyOrganization'); ?>"/></td>
            </tr>
            <?php } ?>
            <tr valign="top">
                <th scope="row"><?php echo('CDN Endpoint'); ?></th>
                <td><input type="text" name="handbidCdnEndpoint"
                           value="<?php echo get_option('handbidCdnEndpoint'); ?>"/></td>
            </tr>
            <tr valign="top">
                <th scope="row"><?php echo('Columns count on auctions and organizations pages'); ?></th>
                <td><select type="text" name="handbidDefaultColCount">
                        <?php
                        $count = (int) get_option('handbidDefaultColCount');
                        $count = ($count) ? $count : 4;
                        for($i = 1; $i < 5; ++$i){
                            echo "<option value='".$i."' ".selected($count, $i, false).">".$i."</option>";
                        }?>
                        </select></td>
            </tr>
            <tr valign="top">
                <th scope="row"><?php echo('Columns count on auction details page'); ?></th>
                <td><select type="text" name="handbidDefaultColCountItem">
                        <?php
                        $count = (int) get_option('handbidDefaultColCountItem');
                        $count = ($count) ? $count : 3;
                        for($i = 1; $i < 5; ++$i){
                            echo "<option value='".$i."' ".selected($count, $i, false).">".$i."</option>";
                        }?>
                        </select></td>
            </tr>
            <tr valign="top">
                <th scope="row"><?php echo('Auctions and Organizations per page'); ?></th>
                <td><input type="number" name="handbidDefaultPageSize"
                           value="<?php $count = (int) get_option('handbidDefaultPageSize') ; echo ($count) ? $count : 25 ; ?>"/></td>
            </tr>

        </table>
        <?php submit_button(); ?>

    </form>

</div>