<?php
$auction = $this->get('auction');
$item    = $this->get('item');

if (!is_front_page()) {
    ?>
    <div class="handbid-breadcrumb">
        <?php
        // print out home
        echo '<a href="' . get_option('home') . '">' . get_bloginfo('name') . '</a>';
        if (isset($auction)) {
            // If there is an auction set drop in the link
            echo ' > <a href="/auctions/' . $auction->key . '">' . $auction->name . '</a>';
            if (isset($item)) {
                // If there is an auction and an item set drop in the link
                echo ' > ' . $item->name;
            }
        } else {
            if (is_category() || is_single()) {
                the_category('title_li=');
                if (is_single()) {
                    echo " > ";
                    the_title();
                }
            } elseif (is_page()) {
                echo " > ";
                echo the_title();
            }
        }
        ?>
    </div>
<?php
}
?>
