<?php

$total    = $this->get( 'total' );
$page     = $this->get( 'page' );
$pageSize = $this->get( 'page_size' );
$pages    = ceil( $total / $pageSize );
$id       = $this->get( 'id' );

if ( $pages < 2 ) {
	return;
}

?>
<ul class="page pagination">
	<?php if ( $page > 0 ) {
		?>
		<li class="first"><a href="<?php echo $this->url( null, [
				$id => [
					'page' => 0
				]
			] ); ?>"><< First</a></li>
		<li class="previous"><a href="<?php echo $this->url( null, [
				$id => [
					'page' => ( $page - 1 )
				]
			] ); ?>">< Previous</a></li>
	<?php
	}

	for ( $p = 0; $p < $pages; $p ++ ) {
		?>

		<li><a href="<?php echo $this->url( null, [
				$id => [
					'page' => $p
				]
			] ); ?>" class="<?php echo ( $page == $p ) ? 'selected' : ''; ?>"><?php echo( $p + 1 ); ?></a></li>

	<?php } ?>

	<?php if ( $page < ( $pages - 1 ) ) {
		?>
		<li class="next"><a href="<?php echo $this->url( null, [
				$id => [
					'page' => ( $page + 1 )
				]
			] ); ?>">Next ></a></li>
		<li class="last"><a href="<?php echo $this->url( null, [
				$id => [
					'page' => ( $pages - 1 )
				]
			] ); ?>">Last >></a></li>
	<?php } ?>
</ul>