<?php
/**
 * @copyright Copyright (c) 2014-2015 Handbid Inc.
 * @category handbid
 * @package Handbid2-WordPress
 * @license Proprietary
 * @link http://www.handbid.com/
 * @author Master of Code (worldclass@masterofcode.com)
 */


$total    = $this->get( 'total' );
$page     = $this->get( 'page' );
$pageSize = $this->get( 'page_size' );
$pages    = ceil( $total / $pageSize );
$id       = $this->get( 'id' );
$trueUrl = !!((int) $this->get( 'true_url' ));
$base = $this->get( 'base' );
$initialPoint = $this->get( 'initial_point' );

if ( $pages < 2 ) {
	return;
}

?>
<ul class="page pagination">
	<?php if ( $page > $initialPoint ) {
		?>
		<li class="first"><a href="<?php echo ($trueUrl)? $this->trueUrl(null,[$base => $initialPoint]):  $this->url( null, [
				$id => [
					'page' => $initialPoint
				]
			] ); ?>"><< First</a></li>
		<li class="previous"><a href="<?php echo ($trueUrl)? $this->trueUrl(null,[$base => $page-1]):  $this->url( null, [
				$id => [
					'page' => ( $page - 1 )
				]
			] ); ?>">< Previous</a></li>
	<?php
	}

	for ( $p = $initialPoint; $p < $pages + $initialPoint; $p ++ ) {
		?>

		<li><a href="<?php echo ($trueUrl)? $this->trueUrl(null,[$base => $p]):  $this->url( null, [
				$id => [
					'page' => $p
				]
			] ); ?>" class="<?php echo ( $page == $p ) ? 'selected' : ''; ?>"><?php echo( $p + (1-$initialPoint) ); ?></a></li>

	<?php } ?>

	<?php if ( $page < ( $pages - (1-$initialPoint) ) ) {
		?>
		<li class="next"><a href="<?php echo ($trueUrl)? $this->trueUrl(null,[$base => $page+1]):  $this->url( null, [
				$id => [
					'page' => ( $page + 1 )
				]
			] ); ?>">Next ></a></li>
		<li class="last"><a href="<?php echo ($trueUrl)? $this->trueUrl(null,[$base => $pages - (1-$initialPoint)]):  $this->url( null, [
				$id => [
					'page' => ( $pages - 1 )
				]
			] ); ?>">Last >></a></li>
	<?php } ?>
</ul>