<?php
if ($this->get('item')) {
    $item = $this->get('item');
    $bids = $this->get('bids');
    $profile = $this->get('profile');
} else {
    echo "No item found.";
    return;
}
?>
<table class="bid-history">
    <?php

    if(count($bids) > 0) {
        ?>
        <thead>
        <tr>
            <th><?php echo __('Amount'); ?></th>
            <th><?php echo __('Bidder Pin'); ?></th>
        </tr>
        </thead>
        <?php
        forEach($bids as $bid) {
            ?>
            <tr>
                <td>$<?php echo $bid->amount; ?></td>
                <td><?php echo ($profile->pin == $bid->winningBidder->pin) ? 'You' : $bid->winningBidder->pin; ?></td>
            </tr>
        <?php
        }
    }
    else
    {
        ?>
            <tr>
                <?php echo __('There are no bids on this item'); ?>
            </tr>
        <?php
    }
        ?>

</table>