<?php
/**
 * @copyright Copyright (c) 2014-2015 Handbid Inc.
 * @category handbid
 * @package Handbid2-WordPress
 * @license Proprietary
 * @link http://www.handbid.com/
 * @author Master of Code (worldclass@masterofcode.com)
 */


$item       = $this->get('item');
$profile    = $this->get('profile');
$auction    = $this->get('auction');
$isBiddable = !$item->isDirectPurchaseItem;
$buyItNow   = $isBiddable && $item->buyNowPrice > 0 && $item->buyNowPrice > $item->minimumBidAmount;
$itemSold   = ($item->status == "sold" || $item->status == "paid");

$creditCards = (isset($profile->creditCards) and is_array($profile->creditCards)) ? $profile->creditCards : [];
$itemIsTicket = (isset($item->isTicket)) ? (bool) $item->isTicket : false;
$needCreditCards = ($itemIsTicket or $auction->requireCreditCard);
$creditCardsRequired = ($needCreditCards) ? " data-handbid-credit-cards-need " : "";
$creditCardsRequired .= (!count($creditCards) and $needCreditCards) ? " data-handbid-credit-cards-required " : "";
$isLiveItem  = $item->disableMobileBidding;
$isBidpadOnly  = $item->isBidpadOnly;
$availableForPreSale = ($item->availableForPreSale == "1");
$itemCanNotBeShownInPresale = (in_array($auction->status, ["presale","preview"]) and !$availableForPreSale);
$itemsAuctionIsClosed = ($auction->status == "closed");
?>
<input type="hidden" data-item-check-status-auction-id="<?php echo $auction->id;?>" value="<?php echo $auction->status;?>">
<input type="hidden" data-item-check-status-item-id="<?php echo $item->id;?>" value="<?php echo $item->status;?>">
<input type="hidden" data-item-check-is-live-item-id="<?php echo $item->id;?>" value="<?php echo ($isLiveItem)?"yes":"no";?>">
<input type="hidden" data-item-check-is-bidpad-item-id="<?php echo $item->id;?>" value="<?php echo ($isBidpadOnly)?"yes":"no";?>">
<input type="hidden" data-item-check-available-item-id="<?php echo $item->id;?>" value="<?php echo $item->availableForPreSale;?>">

<div data-handbid-bid data-handbid-item-key="<?php echo $item->key; ?>" data-item-nobidding-id="<?php echo $item->id; ?>"
     style="<?php echo ($itemCanNotBeShownInPresale or $itemsAuctionIsClosed)?"":" display:none; ";?>">
    <div class="row"><h4 class="no-bidding-message"><?php echo ($isBiddable)?"Item is not open for bidding":"Item is not available to purchase";?></h4></div>
</div>
<div data-handbid-bid data-handbid-item-key="<?php echo $item->key; ?>" data-item-is-sold-id="<?php echo $item->id; ?>"
     style="<?php echo ($itemSold)?"":" display:none; ";?>">
    <div class="row"><h4 class="no-bidding-message"><?php echo "This item has already been SOLD!";?></h4></div>
</div>
<div data-handbid-bid data-handbid-item-key="<?php echo $item->key; ?>" data-item-is-live-id="<?php echo $item->id; ?>"
     style="<?php echo ($isLiveItem)?"":" display:none; ";?>">
    <div class="row"><h4 class="no-bidding-message only-live-auctions"><?php echo "<b>Live Auction Item</b><br>This item is only available in the live auction at the event. Contact the auction manager on when and where this will happen";?></h4></div>
</div>
<div data-handbid-bid data-handbid-item-key="<?php echo $item->key; ?>" data-item-is-bidpad-id="<?php echo $item->id; ?>"
     style="<?php echo ($isBidpadOnly)?"":" display:none; ";?>">
    <div class="row"><h4 class="no-bidding-message only-live-auctions"><?php echo "<b>BidPad Only Item</b><br>This item is only available using BidPad. Contact the auction manager about this opportunity";?></h4></div>
</div>
<div data-handbid-bid data-handbid-item-key="<?php echo $item->key; ?>"  data-item-bidding-id="<?php echo $item->id; ?>"
     style="<?php echo ($itemCanNotBeShownInPresale or $itemSold or $isLiveItem or $isBidpadOnly or $itemsAuctionIsClosed)?" display:none; ":"";?>">


    <div class="row bid-controls">

        <div class="col-md-3 col-xs-3 bid-down">
            <a href="" class="green-button button <?php
            echo ($isBiddable) ? "isBiddable" : "isDirectPurchase" ;
            ?>" data-handbid-bid-button="down" style="<?php
//            echo ($isBiddable) ? "display: none" : "" ;
            ?>">-</a>
        </div>

        <?php if ($isBiddable) { ?>
            <div class="bid-amount col-md-6 col-xs-6">
                <span class="handbidAuctionCurrency" title="<?php echo $currencyCode; ?>"><?php echo $currencySymbol; ?></span><span
                    data-handbid-bid-amount data-handbid-onlybid-amount data-change-attribute="minimumBidAmount"><?php echo $item->minimumBidAmount; ?></span></div>
        <?php } else { ?>
            <div class="buy-quantity col-md-6 col-xs-6"><span data-handbid-quantity>1</span></div>

        <?php } ?>
        <div class="col-md-3 col-xs-3 bid-up">
            <a href="" class="green-button button  <?php
            echo ($isBiddable) ? "isBiddable" : "isDirectPurchase" ;
            ?>" data-handbid-bid-button="up" style="<?php
//            echo ($isBiddable) ? "display: none" : "" ;
            ?>">+</a>
        </div>

    </div>

    <div class="row">

        <?php if ($isBiddable) {
        ?>

        <?php if(!$itemSold)  { ?>

        <div class="col-xs-6">
            <a class="proxy-bid gray-solid-button handbid-modal-link loading-span-button"
               href=""
                <?php echo $creditCardsRequired; ?>
               <?php if($profile){?>data-handbid-modal-key="proxy"<?php }?>
               <?php if(!$profile){?>data-handbid-connect<?php }?>
                ><span><?php echo __('Set Max Bid'); ?></span></a>
        </div>

        <div class="col-xs-6">
            <a class="bid-now green-solid-button  loading-span-button"
               href=""
               <?php echo $creditCardsRequired; ?>
               data-handbid-bid-button="bid"><span><?php echo __('Bid Now'); ?></span></a>
        </div>

        <?php } ?>


    </div>
    <div class="row">
        <div class="col-md-12 BINButton BINItem<?php echo $item->id; ?> <?php echo ($buyItNow)?" BINAvailable ":""; ?>">
            <a class="buy-now pink-solid-button loading-span-button"
               href=""
                <?php echo $creditCardsRequired; ?>
               data-handbid-bid-button="buyItNow" data-handbid-buynow-price="<?php echo $item->buyNowPrice?>"><span><?php echo __('Buy Now For $')  . "<em data-change-attribute='buyNowPrice'>".$item->buyNowPrice ."</em>"; ?></span></a>
        </div>

        <?php }
        else { ?>
            <div class="col-md-12 col-xs-12">
                <a class="buy-now green-solid-button  loading-span-button"
                   href=""
                    <?php echo $creditCardsRequired; ?>
                   data-handbid-bid-button="purchase" data-handbid-buynow-price="<?php echo (int) $item->buyNowPrice;?>"><span><?php echo __('Buy Now'); ?></span></a>
            </div>
        <?php } ?>

    </div>
</div>

<div class="handbid-modal proxy-bid-dialog" data-handbid-modal-key="proxy" data-handbid-bid data-handbid-item-key="<?php echo $item->key; ?>">
    <div class="row">
        <h3>Set a Max Bid<br/>on this item</h3>
        <a href="#" class="modal-close proxy-bid-dialog-close">X</a>
        <p>Handbid will bid for you up to this amount</p>
    </div>
    <div class="row bid-controls">
        <div class="col-md-12">
            <ul class="horizontal-details row">

                <?php if($isBiddable) { ?>
                    <li class="bids col-md-4 col-xs-3"><em   data-change-attribute="bidCount"><?php echo $item->bidCount; ?></em>Bids</li>
                    <li class="increment col-md-4 col-xs-5"><em><span class="handbidAuctionCurrency" title="<?php echo $currencyCode; ?>"><?php echo $currencySymbol; ?></span><span id="bidIncrement"   data-change-attribute="bidIncrement"><?php echo $item->bidIncrement; ?></span></em>Increment</li>
                    <li class="min minimalBidAmount col-md-4 col-xs-4"><em><span class="handbidAuctionCurrency" title="<?php echo $currencyCode; ?>"><?php echo $currencySymbol; ?></span><span id="currentPrice"  data-change-attribute="minimumBidAmount"><?php echo $item->minimumBidAmount; ?></span></em>Min Bid</li>
                <?php } else { ?>
                    <li class="purchases col-md-4 col-xs-3"><em  data-change-attribute="totalSold"><?php echo $item->meta->totalSold; ?></em>Sold</li>
                    <li class="increment col-md-4 col-xs-3"><span class="handbidAuctionCurrency" title="<?php echo $currencyCode; ?>"><?php echo $currencySymbol; ?></span><em data-change-attribute="buyNowPrice"><?php echo $item->buyNowPrice; ?></em>Price</li>
                    <li class="remaining col-md-4 col-xs-6"><em data-change-attribute="inventoryRemaining"><?php echo $item->inventoryRemaining; ?></em>Remaining</li>
                <?php } ?>
            </ul>
        </div>
        <div class="col-md-2 col-xs-3 bid-down">
            <a href="" class="green-button button max-bid-down" data-handbid-bid-button="down">-</a>
        </div>

        <?php if ($isBiddable) { ?>
            <div class="bid-amount minimalBidAmount col-md-8 col-xs-6"><span class="handbidAuctionCurrency" title="<?php echo $currencyCode; ?>"><?php echo $currencySymbol; ?></span><span
                    data-handbid-bid-amount data-handbid-maxbid-amount data-change-attribute="minimumBidAmount"><?php echo $item->minimumBidAmount; ?></span></div>
        <?php } else { ?>
<!--            <div class="buy-quantity col-md-8 col-xs-7"><span data-handbid-quantity>--><?php //echo ($item->inventoryRemaining != 0) ? 1 : 0 ;?><!--</span></div>-->
            <div class="buy-quantity col-md-8 col-xs-7"><span data-handbid-quantity><?php echo $item->inventoryRemaining;?></span></div>

        <?php } ?>
        <div class="col-md-2 col-xs-3 bid-up">
            <a href="" class="green-button button max-bid-up" data-handbid-bid-button="up">+</a>
        </div>

    </div>

    <div class="row">

        <div class="submit-proxy-bid col-md-12 col-xs-12">
            <a class="proxy-bid button green-solid-button  loading-span-button"
               href=""
                <?php echo $creditCardsRequired; ?>
               data-handbid-bid-button="proxy"
               data-data-item-id-maxbid="<?php echo $item->id; ?>"
                ><span><?php echo __('Set Max Bid'); ?></span></a>
        </div>

    </div>
</div>

<input type="hidden" id="bidItemId" value="<?php echo $item->id; ?>">
<input type="hidden" id="bidAuctionId" value="<?php echo $auction->id; ?>">
<input type="hidden" id="bidUserId" value="<?php echo $profile->id; ?>">
<input type="hidden" id="apiEndpointsAddress" value="<?php echo get_option('handbidRestEndpoint', 'https://handbid.com'); ?>">
<input type='hidden' id="bidNonce"  name='nonce' value='<?php echo apply_filters("handbid_create_nonce", date("d.m.Y") . "bid");?>'/>