<?php

$item       = $this->get('item');
$profile    = $this->get('profile');
$auction    = $this->get('auction');
$isBiddable = !$item->isDirectPurchaseItem;
$buyItNow   = $isBiddable && $item->buyNowPrice > 0 && $item->buyNowPrice > $item->minimumBidAmount;
$itemSold   = ($item->status == "sold" || $item->status == "paid");

?>
<div data-handbid-bid data-handbid-item-key="<?php echo $item->key; ?>">

    <div class="row bid-controls">

        <div class="col-md-3 col-xs-3 bid-down">
            <a href="" class="green-button button" data-handbid-bid-button="down" style="display: none;">-</a>
        </div>

        <?php if ($isBiddable) { ?>
            <div class="bid-amount col-md-6 col-xs-6">$<span
                    data-handbid-bid-amount  data-change-attribute="minimumBidAmount"><?php echo $item->minimumBidAmount; ?></span></div>
        <?php } else { ?>
            <div class="buy-quantity col-md-6 col-xs-6"><span data-handbid-quantity>1</span></div>

        <?php } ?>
        <div class="col-md-3 col-xs-3 bid-up">
            <a href="" class="green-button button" data-handbid-bid-button="up" style="display: none;">+</a>
        </div>

    </div>

    <div class="row">

        <?php if ($isBiddable) { ?>

        <?php if(!$itemSold)  { ?>

        <div class="col-md-6 col-xs-12">
            <a class="proxy-bid gray-solid-button handbid-modal-link loading-span-button"
               href=""
               data-handbid-modal-key="proxy"><span><?php echo __('Set Max Bid'); ?></span></a>
        </div>

        <div class="col-md-6 col-xs-12">
            <a class="bid-now green-solid-button  loading-span-button"
               href=""
               data-handbid-bid-button="bid"><span><?php echo __('Bid Now'); ?></span></a>
        </div>

        <?php } ?>

        <?php if($buyItNow)  { ?>
    </div>
    <div class="row">

        <div class="col-md-12">
            <a class="buy-now pink-solid-button loading-span-button"
               href=""
               data-handbid-bid-button="buyItNow" data-handbid-buynow-price="<?php echo $item->buyNowPrice?>"><span><?php echo __('Buy Now For $')  . $item->buyNowPrice; ?></span></a>
        </div>

        <?php } ?>

        <?php } else { ?>
            <div class="col-md-12 col-xs-12">
                <a class="buy-now green-solid-button"
                   href=""
                   data-handbid-bid-button="purchase"><?php echo __('Buy Now'); ?></a>
            </div>
        <?php } ?>

    </div>
</div>

<div class="handbid-modal proxy-bid-dialog" data-handbid-modal-key="proxy" data-handbid-bid data-handbid-item-key="<?php echo $item->key; ?>">
    <div class="row">
        <h3>Set a Max Bid<br/>on this item</h3>
        <a href="#" class="modal-close proxy-bid-dialog-close">X</a>
        <p>Handbid will bid for you up to this amount</p>
    </div>
    <div class="row bid-controls">
        <div class="col-md-12">
            <ul class="horizontal-details row">

                <?php if($isBiddable) { ?>
                    <li class="bids col-md-4 col-xs-3"><em   data-change-attribute="bidCount"><?php echo $item->bidCount; ?></em>Bids</li>
                    <li class="increment col-md-4 col-xs-5"><em>$<span id="bidIncrement"   data-change-attribute="bidIncrement"><?php echo $item->bidIncrement; ?></span></em>Increment</li>
                    <li class="min minimalBidAmount col-md-4 col-xs-4"><em>$<span id="currentPrice"  data-change-attribute="minimumBidAmount"><?php echo $item->minimumBidAmount; ?></span></em>Min Bid</li>
                <?php } else { ?>
                    <li class="purchases col-md-4 col-xs-3"><em  data-change-attribute="totalSold"><?php echo $item->meta->totalSold; ?></em>Sold</li>
                    <li class="increment col-md-4 col-xs-3">$<em data-change-attribute="buyNowPrice"><?php echo $item->buyNowPrice; ?></em>Price</li>
                    <li class="remaining col-md-4 col-xs-6"><em data-change-attribute="inventoryRemaining"><?php echo $item->inventoryRemaining; ?></em>Remaining</li>
                <?php } ?>
            </ul>
        </div>
        <div class="col-md-2 col-xs-3 bid-down">
            <a href="" class="green-button button" data-handbid-bid-button="down">-</a>
        </div>

        <?php if ($isBiddable) { ?>
            <div class="bid-amount minimalBidAmount col-md-8 col-xs-6">$<span
                    data-handbid-bid-amount data-change-attribute="minimumBidAmount"><?php echo $item->minimumBidAmount; ?></span></div>
        <?php } else { ?>
            <div class="buy-quantity col-md-8 col-xs-7"><span data-handbid-quantity>1</span></div>

        <?php } ?>
        <div class="col-md-2 col-xs-3 bid-up">
            <a href="" class="green-button button" data-handbid-bid-button="up">+</a>
        </div>

    </div>

    <div class="row">

        <div class="submit-proxy-bid col-md-12 col-xs-12">
            <a class="proxy-bid button green-solid-button  loading-span-button"
               href=""
               data-handbid-bid-button="proxy"><span><?php echo __('Set Max Bid'); ?></span></a>
        </div>

    </div>
</div>

<input type="hidden" id="bidItemId" value="<?php echo $item->id; ?>">
<input type="hidden" id="bidAuctionId" value="<?php echo $auction->id; ?>">
<input type="hidden" id="bidUserId" value="<?php echo $profile->id; ?>">
<input type="hidden" id="apiEndpointsAddress" value="<?php echo get_option('handbidRestEndpoint', 'https://handbid.com'); ?>">
<input type='hidden' id="bidNonce"  name='nonce' value='<?php echo apply_filters("handbid_create_nonce", date("d.m.Y") . "bid");?>'/>