<?php
/**
 * @copyright Copyright (c) 2014-2015 Handbid Inc.
 * @category handbid
 * @package Handbid2-WordPress
 * @license Proprietary
 * @link http://www.handbid.com/
 * @author Master of Code (worldclass@masterofcode.com)
 */


if ($this->get('item')) {

    $item       = $this->get('item');
    $bids       = $this->get('bids');
    $profile    = $this->get('profile');

} else {
    echo "No item found.";
    return;
}
?>

<ul class="simple-list bid-history bid-history-item-<?php echo $item->id; ?>"  data-no-items-text="This item has no bids.">
<?php
$bids = array_reverse($bids);
if(count($bids) > 0) {

        foreach ($bids as $bid) {
            if($bid->amount){
            ?>
            <li class="row <?php echo ($bid->status == 'winning') ? 'open' : 'closed'; ?>" data-list-bid-id="<?php echo $bid->id; ?>">
                <div class="col-md-6">
                    <h4>Bidder Pin</h4>
                    <span><?php echo $bid->bidderName; ?></span>
                </div>
                <div class="col-md-6">
                    <span class="bid-amount winning">$<span><?php echo $bid->amount; ?></span></span>
                </div>
            </li>
        <?php
            }
        }

}
else
{
    ?>
    <p class="center-text">This item has no bids.</p>
<?php
}
?>
</ul>