<?php
/**
 * @copyright Copyright (c) 2014-2015 Handbid Inc.
 * @category handbid
 * @package Handbid2-WordPress
 * @license Proprietary
 * @link http://www.handbid.com/
 * @author Master of Code (worldclass@masterofcode.com)
 */


if ($this->get('bids')) {

    $item       = $this->get('item');
    $itemID       = $this->get('itemID');
    $bids       = $this->get('bids');

} else {
	$bids = [];
	$item       = $this->get('item');
	$itemID       = $this->get('itemID');
//    echo "No item history found.";
//    return;
}
$noBidsMessage = ($item->disableMobileBidding)?"Bids will be placed here during the Live Auction":"No bids yet! You could be the first!";
?>

<ul class="simple-list bid-history bid-history-item-<?php echo ($item) ? $item->id : $itemID ; ?>"  data-no-items-text="<?php echo $noBidsMessage;?>">
<?php
//$bids = array_reverse($bids);
if(count($bids) > 0) {

        foreach ($bids as $bid) {
            if($bid->amount){
            ?>
            <li class="row <?php echo ($bid->status == 'winning') ? 'open' : 'closed'; ?>" data-list-bid-id="<?php echo $bid->id; ?>">
                <div class="col-md-6">
                    <h4>Bidder Pin</h4>
                    <span><?php echo $bid->bidderName; ?></span>
                </div>
                <div class="col-md-6">
                    <span class="bid-amount winning">$<span><?php echo $bid->amount; ?></span></span>
                </div>
            </li>
        <?php
            }
        }

}
else
{
    ?>
    <p class="center-text"><?php echo $noBidsMessage;?></p>
<?php
}
?>
</ul>