<?php
/**
 * @copyright Copyright (c) 2014-2015 Handbid Inc.
 * @category handbid
 * @package Handbid2-WordPress
 * @license Proprietary
 * @link http://www.handbid.com/
 * @author Master of Code (worldclass@masterofcode.com)
 */


if ($this->item) {
    $item = $this->get('item');
} else {
    echo "No Item Set";
    return;
}
?>
<p class="description">

    <?php
    if (isset($item->description) && $item->description) {
        echo $item->description;
    }
    else
    {
      echo "No description of the item found";
    }
    ?>
</p>