<?php
/**
 * @copyright Copyright (c) 2014-2015 Handbid Inc.
 * @category handbid
 * @package Handbid2-WordPress
 * @license Proprietary
 * @link http://www.handbid.com/
 * @author Master of Code (worldclass@masterofcode.com)
 */


$item    = $this->get('item');
$bids    = $this->get('bids');
$related = $this->get('related');
$auction = $this->get('auction');
$profile = $this->get('profile');
$winning = $this->get('winning');
$losing  = $this->get('losing');

$isWinning = count(array_filter($winning, function ($bid) use ($item)
{
    return $bid->itemId == $item->id;
}));

$isLosing = count(array_filter($losing, function ($bid) use ($item)
{
    return $bid->itemId == $item->id;
}));
if (!$item)
{
    return;
}
$itemIsTicket = (isset($item->isTicket)) ? (bool)$item->isTicket : (strpos(strtolower($item->name), 'ticket') !== false);
if ($itemIsTicket)
{
    $item->isDirectPurchaseItem = true;
}
$category     = $item->categoryName;
$description  = $item->description;
$isBiddable   = !$item->isDirectPurchaseItem;
$isLiveItem   = $item->disableMobileBidding;
$isBidpadOnly = $item->isBidpadOnly;

$description = (trim($description)) ? $description : "No details provided";
$description .= "\n\n";
$description .= '<h5>Fine Print</h5>';
$description .= (trim($item->notables)) ? $item->notables : "Yay! No fine print";


if (!$item->hasInventory)
{
    $item->inventoryRemaining = '∞';
}

$hasManyImages   = (count($item->images) > 1);
$itemValueHidden = (isset($item->showValue) and ($item->showValue != 1));
$itemHideIfSold  = (isset($item->hideSales) and $item->hideSales == 1);

$currencyCode   = (isset($auction->currencyCode)) ? $auction->currencyCode : HANDBID_DEFAULT_CURRENCY;
$currencySymbol = (isset($auction->currencySymbol)) ? $auction->currencySymbol : HANDBID_DEFAULT_CURRENCY_SYMBOL;

$isDonation = (!empty($item->isAppeal) and $item->isAppeal);
?>

    <div class="item-details item-<?php echo $item->status; ?> items-auction-<?php echo $auction->status; ?>"
         data-handbid-item-details-block="<?php echo $item->id; ?>" data-handbid-item-key="<?php echo $item->key; ?>"
         data-handbid-auction-guid="<?php echo $auction->auctionGuid; ?>"
         <?php if ($itemHideIfSold)
         { ?>data-hide-if-sold<?php } ?>
         data-item-id="<?php echo $item->id; ?>"
         data-item-auction-id="<?php echo $auction->id; ?>"
         data-item-is-ticket="<?php echo ($itemIsTicket) ? 'yes' : 'no'; ?>"
         data-item-is-donation="<?php echo ($isDonation) ? 'yes' : 'no'; ?>"
         <?php if ($itemIsTicket)
         { ?>data-ticket-inventory="<?php echo $item->inventoryRemaining; ?>"<?php } ?>
    >


        <div class="back-to-previous-container">
            <a class="back-to-previous" href="/auctions/<?php echo $auction->key; ?>/#back-<?php echo $item->id; ?>">View
                All Items</a>
        </div>

        <div class="row detail-bar">

            <div class="col-md-7">
                <div class="images">
                    <?php if ($hasManyImages)
                    { ?>
                        <ul class="slider-nav" data-slider-nav-id="item-image-slider">
                            <a class="slider-arrow prev" href="#" data-slider-nav-direction="prev">Previous</a>
                            <a class="slider-arrow next" href="#" data-slider-nav-direction="next">Next</a>
                        </ul>

                        <div class="slider-content" data-slider-nav-id="item-image-slider" data-slider-progress>
                            <?php foreach ($item->images as $k => $v)
                            { ?>
                                <div class="image" data-slider-nav-key="<?php echo 'item-image-' . $k; ?>">
                                    <div style="background-image: url('<?php
                                    $image = apply_filters("handbid_cdn_image_gallery", $v->itemImageUrl);
                                    $image = (strpos($image, "http://") === false and strpos($image, "https://") === false) ? "https://" . $image : $image;
                                    echo $image; ?>'); background-size: contain;" class="image-holder"></div>
                                </div>
                            <?php } ?>
                        </div>

                        <?php
                    } else
                    {
                        ?>
                        <div style="background-image: url('<?php
                        $image = apply_filters("handbid_cdn_image_gallery", $item->images[0]->itemImageUrl);
                        $image = (trim($image)) ? $image : HANDBID_PLUGIN_URL . 'public/images/simple-box/default_photo.png';
                        $image = (strpos($image, "http://") === false and strpos($image, "https://") === false) ? "https://" . $image : $image;
                        echo $image; ?>'); background-size: contain;" class="image-holder"></div>
                        <?php
                    }
                    ?>

                    <div style="<?php if (!$isBidpadOnly)
                    { ?>display:none;<?php } ?>" data-handbid-item-banner="bidpad"
                         class="item-banner live-item" data-handbid-box-id="<?php echo $item->id; ?>">This item is only
                        available in the live auction.
                    </div>
                    <div style="<?php if (!$isLiveItem)
                    { ?>display:none;<?php } ?>" data-handbid-item-banner="live"
                         class="item-banner live-item" data-handbid-box-id="<?php echo $item->id; ?>">This item is only
                        available in the live auction.
                    </div>
                    <div style="<?php if (!$isLosing)
                    { ?>display:none;<?php } ?>" data-handbid-item-banner="losing"
                         class="item-banner losing" data-handbid-box-id="<?php echo $item->id; ?>">You are losing this
                        item.
                    </div>
                    <div style="<?php if (!$isWinning)
                    { ?>display:none;<?php } ?>"
                         data-handbid-item-banner="winning" class="item-banner winning"
                         data-handbid-box-id="<?php echo $item->id; ?>">You are winning this item.
                    </div>
                    <!-- <div
                        style="<?php if (!($item->status == "sold" || $item->status == "paid" || (($itemIsTicket) && ($item->inventoryRemaining == 0))))
                        { ?>display:none;<?php } ?>"
                        data-handbid-item-banner="sold" class="item-banner winning"
                        data-handbid-box-id="<?php echo $item->id; ?>">This item has already been SOLD!
                    </div> -->
                </div>

                <?php if ($hasManyImages)
                { ?>
                    <ul class="slider-nav auto-open" data-slider-nav-id="item-image-slider">
                        <?php foreach ($item->images as $k => $v)
                        { ?>
                            <a class="circle" data-slider-nav-key="<?php echo 'item-image-' . $k; ?>"
                               data-slider-nav-item
                               data-slider-nav-item>Circle</a>
                        <?php } ?>
                    </ul>
                <?php } ?>
            </div>

            <div class="col-md-5 buttons-and-titles">
                <h2 class="name" data-handbid-item-attribute="name"
                    data-change-attribute="name"><?php echo $item->name; ?></h2>
                <?php if ($category)
                { ?>
                    <h3 class="category" data-handbid-item-attribute="categoryName"><?php echo $category; ?></h3>
                <?php } ?>
                <ul class="horizontal-details not-for-live-auctions row"
                    style="<?php echo ($isLiveItem) ? " display:none; " : ""; ?>">

                    <?php if ($isBiddable)
                    { ?>
                        <li class="bids col-md-4 col-xs-3">
                            <em
                                data-handbid-item-attribute="bidCount"><?php echo $item->bidCount; ?></em>Bids
                        </li>
                        <li class="increment col-md-4 col-xs-5"><em>
                                <span class="handbidAuctionCurrency"
                                      title="<?php echo $currencyCode; ?>"><?php echo $currencySymbol; ?></span>
                                <span
                                    class="incrementSpan"><?php echo $item->bidIncrement; ?></span></em>Increment
                        </li>
                        <li class="min col-md-4 col-xs-4"><em
                                class=" itemValueBox<?php echo $item->id; ?> <?php echo ($itemValueHidden) ? " itemValueBoxHidden " : ""; ?>">
                                <span class="handbidAuctionCurrency"
                                      title="<?php echo $currencyCode; ?>"><?php echo $currencySymbol; ?></span>
                                <span
                                    data-change-attribute="value"><?php echo $item->value; ?></span></em>Value
                        </li>
                    <?php } else
                    { ?>
                        <li class="purchases col-md-4 col-xs-4" data-handbid-item-attribute="totalSold"><em
                                data-handbid-item-attribute="totalSoldItems"><?php echo $item->quantitySold; ?></em><?php echo ($isDonation) ? 'Donated' : 'Sold' ?>
                        </li>
                        <li class="increment col-md-4 col-xs-4"><em>
                                <span class="handbidAuctionCurrency"
                                      title="<?php echo $currencyCode; ?>"><?php echo $currencySymbol; ?></span>
                                <span id="singleItemPrice"
                                      data-handbid-item-attribute="buyNowPrice"><?php echo $item->buyNowPrice; ?></span></em>Price
                        </li>
                        <li class="remaining col-md-4 col-xs-4">
                            <em
                                data-handbid-item-attribute="inventoryRemaining"><?php echo $item->inventoryRemaining; ?></em>Remaining
                        </li>
                    <?php } ?>
                </ul>

                <?php
                // echo do_shortcode('[handbid_bid key="' . $item->key . '"]');
                echo $this->partial('bid.phtml', [
                    'item'    => $item,
                    'bids'    => $bids,
                    'profile' => $profile,
                    'auction' => $auction,
                ]);
                ?>

                <?php echo do_shortcode('[handbid_social_share]'); ?>
            </div>

        </div>
        <div class="row additional">

            <?php if (wp_is_mobile() && $item->donor)
            { ?>

                <ul class="slider-nav col-md-12 auto-open" data-slider-nav-id="item-donor">

                    <li>
                        <a data-slider-nav-key="donor">Donor</a>
                    </li>
                </ul>
                <div class="slider-content" data-slider-nav-id="item-donor">

                    <div class="additional big-content" data-slider-nav-key="donor" data-handbid-item-attribute="donor">
                        <?php echo $item->donor; ?>
                    </div>
                </div>

            <?php } ?>
            <ul class="slider-nav col-md-12 auto-open" data-slider-nav-id="item-details">

                <?php if (!wp_is_mobile() && $item->donor)
                { ?>
                    <li>
                        <a data-slider-nav-key="donor">Donor</a>
                    </li>
                <?php } ?>

                <?php if ($description)
                { ?>
                    <li>
                        <a data-slider-nav-key="description">Description</a>
                    </li>
                <?php } ?>

                <?php //if ( $isBiddable ) { ?>
                <li>
                    <a data-slider-nav-key="bids">History</a>
                </li>
                <?php //} ?>
                <li>
                    <a data-slider-nav-key="comments">Comments</a>
                </li>
            </ul>
        </div>

        <div class="slider-content" data-slider-nav-id="item-details">

            <?php if (!wp_is_mobile() && $item->donor)
            { ?>
                <div class="additional big-content" data-slider-nav-key="donor" data-handbid-item-attribute="donor">
                    <?php echo $item->donor; ?>
                </div>
            <?php } ?>


            <?php if ($description || !!$item->showValue)
            { ?>
                <div class="additional big-content" data-slider-nav-key="description"
                     data-handbid-item-attribute="description">

                    <?php if (isset($item->showValue) && !!$item->showValue)
                    {
                        echo 'Fair Market Value : ' . $item->value;
                        echo ($description) ? '<br/><br/>' : '';
                    } ?>
                    <?php if ($description)
                    { ?>
                        <?php echo nl2br($description); ?>
                    <?php } ?>

                </div>
            <?php } ?>

            <?php if ($isBiddable)
            { ?>
                <div class="additional big-content bid-history-container-<?php echo $item->id; ?>"
                     data-slider-nav-key="bids"
                     data-bids-nonce="<?php echo apply_filters("handbid_create_nonce", date("d.m.Y") . "get_bids_" . ((int)$item->id)); ?>"
                >
                    <?php
                    // echo do_shortcode('[handbid_item_bids key="' . $item->key . '"]');
                    echo $this->partial('bids.phtml', [
                        'item'    => $item,
                        'profile' => $profile,
                        'bids'    => $bids,
                    ]);
                    ?>
                </div>
            <?php } else
            {
                ?>
                <div class="additional big-content bid-history-container-<?php echo $item->id; ?>"
                     data-slider-nav-key="bids"
                     data-bids-nonce="<?php echo apply_filters("handbid_create_nonce", date("d.m.Y") . "get_bids_" . ((int)$item->id)); ?>"
                >
                    <ul class="simple-list bid-history bid-history-item-<?php echo $item->id; ?>">
                        <p class="center-text">Purchase history not available on this item</p>
                    </ul>
                </div>
                <?php
            } ?>

            <div class="additional comments" data-slider-nav-key="comments">
                <?php echo do_shortcode('[handbid_facebook_comments]') ?>
            </div>

        </div>


    </div>

<?php if ($related)
{ ?>
    <div class="related-items">

        <div class="row">
            <h3 class="title">You might also like</h3>
        </div>

        <?php
        echo $this->partial('related.phtml', [
            'auction' => $auction,
            'items'   => $related,
        ]);
        ?>

        <a class="back-to-previous" href="/auctions/<?php echo $auction->key; ?>/">View All Items</a>

    </div>

<?php } ?>
    <input type="hidden" id="currentItemID" value="<?php echo $item->id; ?>">
    <input type="hidden" id="currentUserID" value="<?php echo $profile->id; ?>">
<?php if ($auction->timerRemaining > 0)
{
    ?>
    <input type="hidden" id="timerRemaining" data-auction-name="<?php echo $auction->name; ?>"
           value="<?php echo $auction->timerRemaining; ?>">
    <?php
} ?>