<?php
/**
 * @copyright Copyright (c) 2014-2015 Handbid Inc.
 * @category handbid
 * @package Handbid2-WordPress
 * @license Proprietary
 * @link http://www.handbid.com/
 * @author Master of Code (worldclass@masterofcode.com)
 */



$items      = $this->get('items');
$cols = $this->get('cols_count');
$col        = 1;
$newRow     = false;
$total      = count($items);


$mdClass = sprintf('col-md-%d', 12 / $cols); //12 total cols in bootstrap
$mdClass .= ' ' . sprintf('col-sm-%d', 6); //12 total cols in bootstrap
$mdClass .= ' ' . sprintf('col-xs-%d', 12); //12 total cols in bootstrap

$auction = $this->get('auction');
$winning = $this->get('winning');
$losing = $this->get('losing');


?>

<div class="row simple-box-row item-list isotope">


    <?php
    if(count($items)) {
	    foreach ( $items as $item ) {

		    echo $this->partial( 'simple-box.phtml', [
			    'item'    => $item,
			    'auction' => $auction,
			    'winning' => $winning,
			    'losing'  => $losing,
		    ] );

		    $newRow = ( $col % $cols === 0 && $col != $total );
		    $col ++;
		    ?>

	    <?php
	    }
    }
    ?>

    <?php // ended up having to give the boostrap column its own div, was not meant to be flexible ?>

	<h3 class="message-no-isotope-results" style="display: none;">Sorry! We couldn't find any matching items. Search again!</h3>

    <div class="sizer <?php echo $mdClass; ?>"></div>

</div>
