<?php
if ($this->get('categories') || $this->get('items') || $this->get('donors')) {
    $auction    = $this->get('auction');
    $categories = $this->get('categories');
    $items      = $this->get('items');
    $donors     = $this->get('donors');

} else {
    echo "No Categories / Items Found";
    return;
}

?>

<div class="auctionItemListWidget">

    <!-- Item List -->
    <div class="itemList">
        <ul id="container" class="items js-isotope">
            <?php forEach ($items as $item) {

                $currentPrice = $item->currentPrice;

                ?>

                <li class="item item-tile">

                    <div class="itemBox" data-handbid-item-key="<?php echo $item->key; ?>">
                        <a title="<?php echo $item->name; ?>" href="/auctions/<?php echo $auction->key; ?>/item/<?php echo $item->key; ?>">
                            <div class="inner">
                                <div class="topBox">
                                    <img src="<?php echo $item->images[0]; ?>"/>
                                </div>
                                <?php if ($item->status == "sold") {
                                    ?>
                                    <div class="item-banner sold"><?php echo __('Sold'); ?></div>
                                <?php
                                }
                                ?>
                                <div class="details">
                                    <ul class="itemStats">
                                        <li><?php echo __('Current'); ?><span> $<span
                                                    data-handbid-item-attribute="currentPrice"><?php echo $currentPrice; ?></span></span>
                                        </li>
                                        <li><?php echo __('Increment'); ?>
                                            <span> <?php echo '$' . $item->bidIncrement; ?></span></li>
                                    </ul>
                                </div>
                            </div>
                        </a>
                    </div>
                </li>
            <?php } ?>
        </ul>
    </div>
</div>
