<?php
/**
 * @copyright Copyright (c) 2014-2015 Handbid Inc.
 * @category handbid
 * @package Handbid2-WordPress
 * @license Proprietary
 * @link http://www.handbid.com/
 * @author Master of Code (worldclass@masterofcode.com)
 */


$item = $this->get('item');
$auction = $this->get('auction');
$winning = $this->get('winning');
$losing = $this->get('losing');
$url = '/auctions/' . $auction->key . '/item/' . $item->key . '/';

if($item->isTicket){
    $item->isDirectPurchaseItem = true;
}
if ($item->isDirectPurchaseItem) {
    $item->currentPrice = $item->buyNowPrice;
}

if (!$item->hasInventory or ($item->inventoryRemaining == -1)) {
    $item->inventoryRemaining = '∞';
}

if ($auction->status == 'presale' && !$item->isDirectPurchaseItem) {
    return;
}

$isLosing = count(array_filter($losing, function ($bid) use ($item) {
    return $bid->itemId == $item->id;
}));

$isWinning  = count(array_filter($winning, function ($bid) use ($item) {
    return $bid->itemId == $item->id;
})) and !$isLosing;

$boxStatus = ($isWinning) ? "winning" : (($isLosing) ? "losing" : $item->status);

$isHidden = ($item->isHidden == "1");

$availableForPreSale = ($item->availableForPreSale == "1");
$itemCanNotBeShownInPresale = (in_array($auction->status, ["presale","preview"]) and !$availableForPreSale);

$itemValueHidden = (isset($item->showValue) and ($item->showValue != 1));

$itemHideIfSold = ($item->hideSales == 1);
?>

<div onclick="if(event.metaKey) { return; } window.location.href='<?php echo $url; ?>'"
    <?php echo ($isHidden)?" data-is-hidden-item ":""; ?>
     data-handbid-item-key="<?php echo $item->key; ?>"
     data-handbid-item-cat-id="<?php echo $item->categoryId; ?>"
     data-handbid-item-box="<?php echo $item->id; ?>"
     data-handbid-params-box="<?php echo $item->id; ?>"
     data-handbid-item-auction="<?php echo $auction->id; ?>"
     data-handbid-item-box-status="<?php echo $boxStatus; ?>"
     class="simple-box status-<?php echo $item->status; ?>
     <?php echo ($itemCanNotBeShownInPresale)?" not-available-in-presale ":"";?>"
     <?php if ($item->isDirectPurchaseItem) { ?>data-for-sale<?php } ?>
     <?php if ($item->disableMobileBidding) { ?>data-live<?php } ?>
     <?php if ($item->isTicket) { ?>data-is-ticket<?php } ?>
     <?php if ($itemHideIfSold) { ?>data-hide-if-sold<?php } ?>
     <?php if (!$item->isDirectPurchaseItem && $item->bidCount === 0) { ?>data-no-bids<?php } ?>
     data-tags="|<?php echo implode('|', array_map(function ($term) {
         return esc_html(sanitize_key($term));
     }, array($item->categoryName))); ?>|">

    <div class="header">
        <div class="col-md-4 col-xs-4 price">$<span
                class="currentItemPrice" data-handbid-item-attribute="currentPrice"><?php echo $item->currentPrice; ?></span></div>
        <?php if (trim($item->itemCode)) { ?>
            <div class="col-md-8 col-xs-8 code">#<span
                    data-handbid-item-attribute="itemCode"><?php echo $item->itemCode; ?></span></div>
        <?php } ?>
        <div class="clear"></div>
    </div>

    <div class="body">
        <?php
        $image = (isset($item->images) and is_array($item->images) and count($item->images) and isset($item->images[0]->itemImageUrl))?$item->images[0]->itemImageUrl:"";
        $image = apply_filters("handbid_cdn_image_thumbnail", $image);
        $image = (trim($image))?$image: HANDBID_PLUGIN_URL . 'public/images/simple-box/default_photo.png'  ;
        $imageUrlPath = parse_url($image);
        $image = ($imageUrlPath["scheme"]) ? $image : ((trim($image)) ? "http://" . $image : "");
        $backImageStyle = trim($image) ? "background-image: url(" . $image . ")" : "";
        ?>
        <div class="full-image-wrapper" style="<?php echo $backImageStyle; ?>">
            <div class="dim-overlay"></div>
            <div class="box-flag">

                <h3 data-handbid-box-banner="live" data-handbid-box-id="<?php echo $item->id; ?>">Live Auction Only</h3>
                <h3 data-handbid-box-banner="losing" data-handbid-box-id="<?php echo $item->id; ?>">Losing this item.</h3>
                <h3 data-handbid-box-banner="winning" data-handbid-box-id="<?php echo $item->id; ?>">Winning this item.</h3>
                <h3 data-handbid-box-banner="sold"  data-handbid-box-id="<?php echo $item->id; ?>">Sold Out</h3>
            </div>
        </div>

        <div class="contents">

            <h3>
                <a href="<?php echo $url; ?>" data-handbid-item-attribute="name"><?php echo $item->name; ?></a>
                <span style="display: none;" class="nameLowerCase"><?php echo esc_html(strtolower($item->name));?></span>
            </h3>

            <?php if (trim($item->categoryName)) { ?>
                <h4 data-handbid-item-attribute="categoryName"><?php echo $item->categoryName ?></h4>
            <?php } ?>

            <ul class="horizontal-details">

                <?php if ($item->isDirectPurchaseItem) { ?>

                    <li class="bids col-md-6 col-xs-6">Sold <em
                            data-handbid-sold-of-id="<?php echo $item->id; ?>"
                            data-handbid-item-attribute="quantitySold"><?php echo $item->quantitySold; ?></em></li>
                    <li class="remaining col-md-6 col-xs-6"><em
                            data-handbid-remaining-of-id="<?php echo $item->id; ?>"
                            data-handbid-item-attribute="inventoryRemaining"><?php echo $item->inventoryRemaining; ?></em>
                        Left
                    </li>
                <?php } else { ?>
                    <li class="bids col-md-6 col-xs-6">Bids <em
                            data-handbid-bids-of-id="<?php echo $item->id; ?>"
                            data-handbid-item-attribute="bidCount"><?php echo $item->bidCount; ?></em></li>
                    <li class="bid-now col-md-6 col-xs-6">Bid Now</li>
                <?php } ?>

            </ul>

        </div>

    </div>

</div>