<?php
if ($this->context) {
    $item = $this->context['item'];
} else {
    echo "Context not found";
    return;
}
?>

<div class="banner">
    <a href="#" class="unslider-arrow prev">Previous slide</a>
    <a href="#" class="unslider-arrow next">Next slide</a>
    <ul>
        <?php
            forEach($item['images'] as $imageUrl) {
                ?>
                <li><img src="<?= $imageUrl; ?>"/></li>
                <?php
            }
        ?>
    </ul>
</div>