<?php
if ($this->context) {
    $item = $this->context['item'];
} else {
    echo "Context not found";
    return;
}
?>
<div class="images">
    <?php
    forEach ($item->images as $imageUrl) {
        ?>
        <a href="<?php echo $imageUrl; ?>" itemprop="image" class="woocommerce-main-image zoom" data-rel="prettyPhoto[product-gallery]">
            <img width="300" height="300" src="<?php echo $imageUrl; ?>" class="attachment-shop_single wp-post-image">
        </a>
    <?php
    }
    ?>

    <div class="thumbnails">
        <?php
        forEach ($item->images as $imageUrl) {
        ?>
            <a href="<?php echo $imageUrl; ?>" class="zoom first" data-rel="prettyPhoto[product-gallery]">
                <img width="90" height="90" src="<?php echo $imageUrl; ?>" class="attachment-shop_thumbnail">
            </a>
        <?php
        } ?>
    </div>

</div>
