<?php
if ($this->get('item')) {
    $item = $this->get('item');
} else {
    echo "Item not found";
    return;
}

?>
<div class="photoGallery">
    <div class="banner">
        <a href="#" class="unslider-arrow prev">Previous slide</a>
        <a href="#" class="unslider-arrow next">Next slide</a>
        <ul>
            <?php forEach ($item->images as $imageUrl) {
            ?>
                <li><img src="<?= $imageUrl; ?>"/></li>
            <?php
            }
            ?>
        </ul>
    </div>
</div>