<?php
/**
 * @copyright Copyright (c) 2014-2015 Handbid Inc.
 * @category handbid
 * @package Handbid2-WordPress
 * @license Proprietary
 * @link http://www.handbid.com/
 * @author Master of Code (worldclass@masterofcode.com)
 */



if(!$this->get('bidder')) { ?>

    <a class="handbid-connect" href="#" data-handbid-connect data-handbid-pass="<?php echo $this->get('passUrl'); ?>" data-handbid-fail="<?php echo $this->get('failUrl'); ?>"></a>

<?php } ?>