<div class="widget widget-buy-ticket">
    <div class="auction-content">
        <h2><a href="/auctions/handbid-demo-auction">Handbid Demo Auction</a></h2>
        <div class="timer auction-timer normal">Ends in</div>
    </div>
    <div>
        <div class="tickets">
            <a href="/auctions/handbid-demo-auction/tickets">
                <div>BUY TICKETS</div>
                TO AUCTION
            </a>
        </div>
        <div class="share">
            <a class="twitter" href="">Share</a>
            <a class="facebook" href="">Share</a>
        </div>
    </div>
</div>