<?php
/**
 * @copyright Copyright (c) 2014-2015 Handbid Inc.
 * @category handbid
 * @package Handbid2-WordPress
 * @license Proprietary
 * @link http://www.handbid.com/
 * @author Master of Code (worldclass@masterofcode.com)
 */


if ($this->get('tickets'))
{
    $auction = $this->get('auction');
    $tickets = $this->get('tickets');
    $cards   = $this->get('cards');
    $profile = $this->get('profile');

} else
{
    echo "No Tickets Found";

    return;
}

if (!$auction->enableTicketSales)
{
    return;
}

$currencyCode   = (isset($auction->currencyCode)) ? $auction->currencyCode : HANDBID_DEFAULT_CURRENCY;
$currencySymbol = (isset($auction->currencySymbol)) ? $auction->currencySymbol : HANDBID_DEFAULT_CURRENCY_SYMBOL;
?>

<a class="button pink-button handbid-modal-link purchase-tickets"
    <?php if (!count($profile->creditCards))
    {
        //echo " data-handbid-credit-cards-required ";
    } ?> data-handbid-credit-cards-need
   data-handbid-modal-key="tickets-form" data-handbid-tickets>Buy Tickets</a>

<div class="handbid-modal modal fade tickets-modal" tabindex="-1" role="dialog" data-handbid-modal-key="tickets-form"
     data-handbid-tickets>
    <div class="modal-dialog">
        <h3>Event Tickets / Registration</h3>
        <a href="#" class="modal-close" data-dismiss="modal" aria-label="Close">&times;</a>


        <?php

        if ($profile)
        {
            $needToCheckIfCreditCardsRequired = false;
            if ($needToCheckIfCreditCardsRequired && $auction->requireCreditCard && !count($cards) > 0)
            {
                echo "You need to add a credit card to buy tickets";
            } else
            {
                ?>
                <div class="tickets-container">
                    
                    <?php forEach ($tickets as $k => $ticket)
                    {
                        $step      = 1;
                        $remaining = $ticket->inventoryRemaining;
                        $isHidden  = ($ticket->isHidden == "1");
                        ?>
                        <div class="row ticket-row" data-handbid-ticket-row="<?php echo $ticket->id; ?>"
                            <?php echo ($isHidden) ? " data-is-hidden-item " : ""; ?>
                             data-handbid-params-box="<?php echo $ticket->id; ?>">
                            <div class="ticket"
                                 data-handbid-ticket-block
                                 data-handbid-ticket-id="<?php echo $ticket->id; ?>"
                                 data-handbid-ticket-price="<?php echo $ticket->buyNowPrice; ?>"
                                 data-handbid-ticket-step="<?php echo $step; ?>"
                            >
                                <div class="col-sm-8 ticket-part-container no-padding-left">
                                    <h4 class="ticket-title"><span
                                            data-handbid-ticket-title><?php echo $ticket->name; ?></span>
                                        &nbsp;&nbsp;<span class="ticket-price"><span class="handbidAuctionCurrency"
                                                                                     title="<?php echo $currencyCode; ?>"><?php echo $currencySymbol; ?></span><span
                                                data-handbid-ticket-buynow><?php echo $ticket->buyNowPrice; ?></span></span>
                                    </h4>

                                    <p class="ticket-quantity">(admits <span
                                            data-handbid-ticket-quant><?php echo $ticket->ticketQuantity; ?></span>
                                        people)</p>
                                    <p class="ticket-description"
                                       data-handbid-ticket-description><?php echo $ticket->description; ?></p>


                                </div>
                                <div class="col-sm-4 ticket-part-container no-padding-right tickets-are-sold"
                                     style="<?php echo (($remaining == 0) or ($ticket->status == 'sold')) ? "" : "display:none"; ?>">
                                    <h4>SOLD OUT</h4>
                                </div>
                                <div
                                    class="col-xs-6 col-xs-offset-3 col-sm-4 col-sm-offset-0 ticket-part-container no-padding-right tickets-are-available"
                                    style="<?php echo (($remaining == 0) or ($ticket->status == 'sold')) ? "display:none" : ""; ?>">
                                    <div class="col-xs-4 no-padding">
                                        <a href="" class="bid-price-toggle bid-down green-button button ghosted-out"
                                           data-handbid-ticket-button="down">-</a>
                                    </div>

                                    <div class="buy-quantity col-xs-4 no-padding"><span
                                            data-handbid-ticket-quantity>0</span>
                                        <input type="hidden" data-handbid-tickets-remaining
                                               value="<?php echo $remaining; ?>">
                                    </div>

                                    <div class="col-xs-4 ticket-quantity-up no-padding">
                                        <a href=""
                                           class="bid-price-toggle bid-up green-button button <?php echo (((int)$remaining > 0) and ($remaining < $step)) ? "ghosted-out" : ""; ?>"
                                           data-handbid-ticket-button="up">+</a>
                                    </div>

                                    <div class="col-xs-12 ticket-remaining-inventory-cont no-padding">
                            <span class="remaining-inventory" data-handbid-ticket-quant-remaining><?php
                                echo ($remaining != -1) ? $remaining . " available" : "Unlimited quantity";
                                ?></span>
                                    </div>
                                </div>

                            </div>
                        </div>
                        <?php

                    }
                    ?>
                </div>
                <div class="row tickets-footer-row">
                    <div class="col-sm-3 col-sm-offset-6">
                        <h3 class="total"><span class="handbidAuctionCurrency"
                                                title="<?php echo $currencyCode; ?>"><?php echo $currencySymbol; ?></span><span
                                data-handbid-tickets-total>0</span></h3>
                        <h5>Grand Total</h5>
                    </div>

                    <div class="col-sm-3">
                        <a href="#" class="button green-solid-button   loading-span-button"
                           data-handbid-tickets-button="purchase"
                            <?php if (!count($profile->creditCards))
                            {
                                echo " data-handbid-credit-cards-required ";
                            } ?> data-handbid-credit-cards-need
                           data-handbid-buy-tickets-nonce="<?php echo apply_filters("handbid_create_nonce", date("d.m.Y") . "buy_tickets_array"); ?>"
                           data-handbid-auction-id="<?php echo $auction->id; ?>"
                           data-handbid-profile-id="<?php echo $profile->id; ?>"
                        ><span>Add</span></a>
                    </div>
                </div>
                <?php
            } // End credit card check
        } else
        {

            echo '<a href="#" data-handbid-connect>To purchase tickets, we first need to get you to login or setup an account.  Please <strong>click here</strong> to do that. After you are logged in, we can get your payment info and get you going.</a>';
        }

        ?>
    </div>
</div>



