<div class="page-not-found center-text">
    <h2>Oops</h2>
    <h3>Page not found</h3>
    <div class="gavel-icon">
        <svg class="u-svg-icon">
            <use xlink:href="#gavel-icon"></use>
        </svg>
    </div>
    <p>
        This page was sold to the highest bidder...<br/>
        Lets go before they get home.
    </p>
    <a href="/" class="button green-solid-button">Return to home page</a>

</div>
