<?php
/**
 * @copyright Copyright (c) 2014-2015 Handbid Inc.
 * @category handbid
 * @package Handbid2-WordPress
 * @license Proprietary
 * @link http://www.handbid.com/
 * @author Master of Code (worldclass@masterofcode.com)
 */


if ($this->organization) {

    $org = $this->get('organization');
    $address = null;
    $hasLocation = !!($org->organizationAddressStreet1);

    if ($hasLocation) {
        $street1 = $org->organizationAddressStreet1;
        $street2 = $org->organizationAddressStreet2;
        $city = $org->organizationAddressCity;
        $province = $org->organizationAddressProvince;
        $postalCode = $org->organizationAddressPostalCode;
        $address = $street1 . ' ' . $street2 . ' ' . $city . ' ' . $prov . ' ' . $postalCode;
    }


} else {
    echo "No Organization Set";
    return;
}


?>

<div class="org-details">

    <div class="container container-fluid detail-banner-wrapper">
        <div class="detail-banner" style="background-image: url('<?php echo $org->banner; ?>')">
            <div class="logo">
                <img src="<?php
                $image = $org->logo;
                $imageUrlPath = parse_url($image);
                $image = ($image and isset($imageUrlPath["scheme"])) ? $image : $org->organizationImages[0]->organizationImageUrl;
                $imageUrlPath = parse_url($image);
                $image = ($imageUrlPath["scheme"]) ? $image : "http://" . $image;
                echo $image; ?>"/>
            </div>
        </div>
        <div class="controls">

             <span class="status">
                <a href="<?php if (strpos($org->website, 'http') === false)  {
                    echo "http://";
                } echo $org->website; ?>" target="_blank"><?php echo $org->website; ?></a>
            </span>

            <?php
            $socialLinks = [
                [
                    "class" => "facebook",
                    "link" => $org->socialFacebook,
                ],
                [
                    "class" => "google-plus",
                    "link" => $org->socialFacebook,
                ],
                [
                    "class" => "twitter",
                    "link" => $org->socialFacebook,
                ],
                [
                    "class" => "pinterest",
                    "link" => $org->socialFacebook,
                ],
            ];
            $socialsNotEmpty = false;
            foreach($socialLinks as $socialLink){
                if(trim($socialLink["link"])){
                    $socialsNotEmpty = true;
                }
            }
            if($socialsNotEmpty){
                echo '<div class="handbid-share-bar row"><div class="col-md-1 col-xs-1">&nbsp;</div>';
                foreach($socialLinks as $socialLink){
                    if(trim($socialLink["link"])){
                        echo '<a class="icon '.$socialLink["class"].' col-md-2 col-xs-2" href="'.$socialLink["link"].'"></a>';
                    }
                }
                echo '<div class="col-md-1 col-xs-1">&nbsp;</div></div>';
            }
            else{
                echo do_shortcode('[handbid_social_share]');
            }
            ?>

        </div>
    </div>

    <ul class="slider-nav col-md-12 auto-open" data-slider-nav-id="org-details">
        <?php if ($org->description) { ?>
            <li>
                <a data-slider-nav-key="description">Description</a>
            </li>
        <?php } ?>
        <?php if ($hasLocation) { ?>
            <li>
                <a data-slider-nav-key="map">Address &amp; Map</a>
            </li>
        <?php } ?>
    </ul>

    <div class="slider-content" data-slider-nav-id="org-details">

        <?php if ($org->description) { ?>
            <div class="container container-fluid" data-slider-nav-key="description">
                <?php echo $org->description; ?>
            </div>
        <?php } ?>

        <?php if ($hasLocation) { ?>
            <div class="details-map" data-slider-nav-key="map" data-address="<?php echo $address; ?>">

                <div id="large-map"></div>
                <div id="small-map"></div>

            </div>
            <div style="display: none" id="map-marker-content">
                <div class="overflow">
                    <div class="row">
                        <div class="col-md-6 iw-label">Location</div>
                        <div class="col-md-6"><?php echo $org->name; ?></div>
                    </div>
                    <div class="row">
                        <div class="col-md-6 iw-label">Address</div>
                        <div
                            class="col-md-6"><?php
                            $street1 = $org->organizationAddressStreet1;
                            $street2 = $org->organizationAddressStreet2;
                            $city = $org->organizationAddressCity;
                            $province = $org->organizationAddressProvince;
                            $postalCode = $org->organizationAddressPostalCode;
                            echo $street1 . ' ' . $street2 . '<br />' . $city . ', ' . strtoupper($province) . ' ' . $postalCode; ?></div>
                    </div>
                    <div class="row submit">
                        <a class="pink-button get-directions" onclick="getDirections()" href="#">Get Directions</a>
                    </div>
                </div>
            </div>
        <?php } ?>

    </div>


    <div class="container container-fluid">
        <h3 class="auction-title">Auctions</h3>
        <?php echo do_shortcode('[handbid_organization_auctions]'); ?>
    </div>


</div>

<script src="https://maps.googleapis.com/maps/api/js?v=3.exp"></script>
