<?php
if ($this->organization) {
    $org = $this->get('organization');
    $address = $org->address;
} else {
    echo "No Organization Set";
    return;
}
?>
<header id="title-area" class="clearfix header-cover">
    <div class="inner" style="opacity: 1;"><h1 class="page-title entry-title"><?php echo $org->name; ?></h1></div>
</header>

<div class="organization-details-container">
    <img src="<?php echo $org->logo; ?>"/>

    <div class="org-details">
        <address class="vcard">
            <div class="street-address"><?php echo $address->street1; ?></div>
            <div class="street-address"><?php echo $address->street2; ?></div>
            <div class="city"><?php echo $address->city; ?></div>
            <div class="province"><?php echo $address->province; ?></div>
            <div class="postal-code"><?php echo $address->postalCode; ?></div >
            <div class="country-name"><?php echo $address->country; ?></div >
        </address>

        <div class="website">
            <a href="<?php echo $org->website; ?>" target="_blank"><?php echo $org->website; ?></a>
        </div>
        <div class="description">
            <?php echo $org->description; ?>
        </div>
    </div>
</div>