<?php
    $organizations = $this->get('organizations');
?>

<div class="organization-list">
    <div class="image-grid isotope">
        <?php

        forEach ($organizations as $org) {
            ?>

            <a href="/organizations/<?php echo $org->key; ?>" class="">
                <?php echo $org->name; ?>
            </a>

        <?php
        }
        ?>
    </div>
</div>
<?php echo do_shortcode('[handbid_pager page_size=' . $this->get('page_size') . ' page=' . $this->get('page') . ' total=' . $this->get('total') . ' id=' . $this->get('id') . ' ]'); ?>