<?php
/**
 * @copyright Copyright (c) 2014-2015 Handbid Inc.
 * @category handbid
 * @package Handbid2-WordPress
 * @license Proprietary
 * @link http://www.handbid.com/
 * @author Master of Code (worldclass@masterofcode.com)
 */



$organizations = $this->get('organizations');
$cols = $this->get('cols_count');
$search = $this->get('search');
$col = 1;
$newRow = false;
$total = count($organizations);

$mdClass = sprintf('col-md-%d',  12 / $cols); //12 total cols in bootstrap
$mdClass .= ' ' . sprintf('col-sm-%d',  12 / $cols * 2); //12 total cols in bootstrap
$mdClass .= ' ' . sprintf('col-xs-%d',  12); //12 total cols in bootstrap

$selected = isset($_GET['auction_list']) ? $_GET['auction_list'] : 'current';

?>

<div class="section-nav">
    <a href="/auctions/">Auctions |</a> Organizations
</div>

<div class="row sort-bar auction-item-list" style="transition: none; margin-bottom: 15px;">

    <div class="category-cover-cheating"></div>

    <div class="col-md-6 col-xs-6 fancy-search-wrapper">

        <form class="fancy-search" method="get">
            <button type="submit">
                <span class="icon">
                    <svg class="u-svg-icon">
                        <use xlink:href="#hb-mag"></use>
                    </svg>
                </span>
                Search Organizations
            </button>
            <input class="query categories-query" type="search" name="search" placeholder="Search organizations" value="<?php echo ($search)?$search:"";?>">
            <a class="reset" href="#" style="display: none">X</a>
        </form>

    </div>
</div>

<div class="row simple-box-row organizations">

    <?php
    if(count($organizations)){
    foreach ($organizations as $organization) {

    $url = '/organizations/' . $organization->key . '/';
    $image = (isset($organization->logo))?$organization->logo:"";
    $imageUrlPath = parse_url($image);
    $image = ($image and isset($imageUrlPath["scheme"])) ? $image :
        ((isset($organization->organizationImages)
        and is_array($organization->organizationImages)
        and count($organization->organizationImages)
        and isset($organization->organizationImages[0]->organizationImageUrl))?$organization->organizationImages[0]->organizationImageUrl : "" );
    $imageUrlPath = parse_url($image);
    $image = (isset($imageUrlPath["scheme"])) ? $image : "https://" . $image;
    $image = (strpos($image, "ucarecdn") !== false and strpos($image, "preview") === false)? $image . "-/preview/220x80/" : $image ;
    ?>

    <?php // ended up having to give the bootsrap column its own div, was not meant to be flexible ?>
    <div class="<?php echo $mdClass; ?>">

        <div onclick="if(event.metaKey) { return; } window.location.href='<?php echo $url; ?>'" class="simple-box">

            <div class="header">
            </div>

            <div class="body">

                <div class="highlight">
                    <!-- the diagonal highlight -->
                </div>

                <div class="contents">

                    <a href="<?php echo $url; ?>" class="image-wrapper">
                        <div class="auction-image-place without-image"  data-backgroung-image-url="<?php echo $image; ?>">
                        </div>
                    </a>

                    <h3><a href="<?php echo $url; ?>"><?php echo strip_tags($organization->name); ?></a></h3>

                    <ul class="details">

                        <li class="total-auctions">
                            <span class="icon">
                                <svg class="u-svg-icon">
                                    <use xlink:href="#hb-gavel"></use>
                                </svg>
                            </span>
                            <?php
                            $countAuctions = (int) $organization->activeAuctions;

                            $countAuctions .= ' Auction';
                            if($countAuctions > 1 or $countAuctions == 0) {
                                $countAuctions .= 's';
                            }
                            $countAuctions .= ' Open';

                            echo $countAuctions;

                            ?></li>

                        <?php
                        $city = $organization->organizationAddressCity;
                        $prov = $organization->organizationAddressProvince;
                        if($city) { ?>
                            <li class="addy">
                                <span class="icon">
                                    <svg class="u-svg-icon">
                                        <use xlink:href="#hb-pin"></use>
                                    </svg>
                                </span>
                                <?php echo $city . (($prov) ? ', ' . $prov : ""); ?>
                            </li>
                        <?php } ?>

                    </ul>

                </div>

            </div>

        </div>

    </div>

    <?php
    $newRow = ($col % $cols === 0 && $col != $total);
    $col++;
    ?>


    <?php if ($newRow) { ?></div><div class="row simple-box-row organizations"><?php } ?>


    <?php }
    }
    else{
        echo "<h3>No organizations found</h3>";
    }
    ?>

</div>

<?php if(count($organizations) > 0 && $this->has('page_size')) {
    echo do_shortcode('[handbid_pager page_size=' . $this->get('page_size') . ' page=' . $this->get('page') . ' total=' . $this->get('total') . ' id=' . $this->get('id') . ' ]');
}
?>
