<?php
if ($this->auctions) {
    $auctions = $this->get('auctions');
} else {
    echo "No Auction Set";
    return;
}
?>

<div class="organizationListBlock">
    <div class="image-grid isotope">
        <?php

        forEach ($auctions as $auction) {
            ?>

            <a href="/auctions/<?php echo $auction->key; ?>" class="fancyLink auctionListLogo">
                <img src="<?php echo $auction->logo->medium; ?>"/>
            </a>

        <?php
        }
        ?>
    </div>
</div>