<?php
/**
 * @copyright Copyright (c) 2014-2015 Handbid Inc.
 * @category handbid
 * @package Handbid2-WordPress
 * @license Proprietary
 * @link http://www.handbid.com/
 * @author Master of Code (worldclass@masterofcode.com)
 */


if ($this->get('url')) {
    $customUrlParameter = $this->get('url');
} else {
    echo "Facebook comments not set";
    return;
}

$url = 'http://' . $_SERVER['SERVER_NAME'] . '/' . $_SERVER['REQUEST_URI']

?>

<div class="fb-comments" data-href="<?php echo $url; ?>" data-numposts="5" data-colorscheme="light"></div>