<?php
if ($this->context) {
    $customUrlParameter = $this->context['url'];
} else {
    echo "Facebook comments not set";
    return;
}
?>
<div id="fb-root"></div>
<script>(function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&appId=289898497844744&version=v2.0";
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>

<div class="fb-comments" data-href="http://handbid.com/comments/<?php echo $customUrlParameter; ?>" data-numposts="5" data-colorscheme="light"></div>