<?php
if (isset($this->context['item']) || isset($this->context['bidHistory']) || $this->context) {
    $item       = $this->context['item'];
    $bidhistory = $this->context['bidHistory'];
    var_dump($bidhistory);
    exit;

} else {
    echo "No Item Set";
    return;
}

?>

<div class="widget widget-bidhistory widgetContainer">
    <div>
        <h3><?php echo __('Bid History'); ?></h3>
    </div>
    <div class="bid-history-list">
        <div class="bid-history-item">
            <div class="left">
                <div class="image"><img src="<?php echo $item->images[0]; ?>"></div>
            </div>
            <div class="right">
                <div class="text">
                    <div class="alias">Jeffrey Porter (4449)</div>
                    <div class="amount">$55</div>
                </div>
            </div>
        </div>
    </div>
</div>