<div class="product-info">
    <h1>Donec tellus purus</h1>

    <div class="price">                    $119.50                    <br>
        <span class="price-tax">Ex Tax: $100.00</span><br>
        <span class="reward"><small>Price in reward points: 400</small></span><br>
    </div>

    <div class="description">
        <span>Brand:</span> <a href="http://demopavothemes.com/pav_digital_store/index.php?route=product/manufacturer/info&amp;manufacturer_id=7">Hewlett-Packard</a><br>
        <span>Product Code:</span> product 8<br>
        <span>Reward Points:</span> 300<br>
        <span>Availability:</span> In Stock
    </div>
    <div class="product-extra clearfix">
        <div class="quantity-adder pull-left">
            <span class="add-up add-action button">+</span>
            <input class="form-control" type="text" name="quantity" size="2" value="1">
            <span class="add-down add-action button">-</span>
        </div>
        <div class="product-action product-block">
            <input type="hidden" name="product_id" value="47">
            &nbsp;
            <div class="cart pull-left"><input type="button" value="Add to Cart" id="button-cart" class="button"></div>
        </div>
    </div>
</div>