<?php
if ($this->context) {
    $item = $this->context['item'];
} else {
    echo "No Item Set";
    return;
}

?>
<h1 itemprop="name" class="product_title entry-title"><?php echo $item->name; ?></h1>

<div title="Donor">
    <div class="label"><?php echo __('Donated by') . ': '; ?></div>
    <div class="donor"><?php echo $item->donor; ?></div>
</div>

<div>
    <span class="label" id="bidLabel"><?php echo __('Minimum next bid'); ?></span>
    <span class="amount">
        $<span class="value" id="bidAmountTotal"><?php echo $item->minimumBidAmount; ?></span>
    </span>
</div>
<div class="bidIncrement">
    <?php echo __('Bid increments by') . ' $'; ?><span
        class="value"><?php echo $item->bidIncrement; ?></span>
</div>
<form class="cart">
    <div class="quantity buttons_added"><input type="button" value="-" class="minus down"><input type="number" step="1"
                                                                                                 min="1"
                                                                                                 name="quantity"
                                                                                                 value="1"
                                                                                                 title="Qty"
                                                                                                 class="input-text qty text"
                                                                                                 size="4"><input
            type="button"
            value="+"
            class="plus up">
    </div>
    <div class="clear"></div>
    <button type="submit" class="single_add_to_cart_button button alt"><?php echo __('Bid Now'); ?></button>
    <div class="clear"></div>
    <button type="submit" id="proxyBid" class="single_add_to_cart_button button alt proxy"><?php echo __('Make a Proxy Bid'); ?></button>
</form>

<button class="reset"><?php echo __('Reset Bid'); ?></button>