<?php
if ($this->get('item')) {
    $item = $this->get('item');
} else {
    echo "No Item Set";
    return;
}

?>
<h1 itemprop="name" class="product_title entry-title"><?php echo $item->name; ?></h1>

<?php if(isset($item->donor) || $item->donor) {
?>
    <div title="Donor">
        <div class="label"><?php echo __('Donated by') . ': '; ?></div>
        <div class="donor"><?php echo $item->donor; ?></div>
    </div>
<?php
}
?>

<div>
    <span class="label" id="bidLabel"><strong><?php echo __('Minimum next bid'); ?></strong></span>
    <span class="amount">
        $<span class="value" id="bidAmountTotal"><?php echo $item->minimumBidAmount; ?></span>
    </span>
</div>
<div class="bidIncrement">
    <strong><?php echo __('Bid increments by'); ?></strong><span
        class="value"><?php echo ' $' . $item->bidIncrement; ?></span>
</div>
<form class="bidUpDown">
    <div class="quantity buttons_added"><input type="button" value="-" class="minus down"><input type="number"
                                                                                                 class="value input-text qty text" value="<?php echo $item->minimumBidAmount; ?>"><input
            type="button"
            value="+"
            class="plus up">
    </div>
    <div class="clear"></div>
    <button type="submit" class="bidNow button"><?php echo __('Bid Now'); ?></button>
    <button type="submit" id="proxyBid" class="proxyBid button"><?php echo __('Make a Proxy Bid'); ?></button>
</form>

<button class="reset"><?php echo __('Reset Bid'); ?></button>