<?php
/**
 * @copyright Copyright (c) 2014-2015 Handbid Inc.
 * @category handbid
 * @package Handbid2-WordPress
 * @license Proprietary
 * @link http://www.handbid.com/
 * @author Master of Code (worldclass@masterofcode.com)
 */


//$url = 'https://' . $_SERVER['SERVER_NAME'] . '/' . $_SERVER['REQUEST_URI'];
$url = urlencode(HANDBID_FB_SHARE_URL);
$openInJavascript = "javascript:window.open(this.href,'', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=600,width=600');return false;";
?>

<div class="handbid-share-bar">
    <a class="icon facebook" href="https://www.facebook.com/sharer.php?u=<?php echo $url; ?>" onclick="<?php echo $openInJavascript; ?>"></a>

    <a class="icon google-plus" href="https://plus.google.com/share?url=<?php echo $url; ?>" onclick="<?php echo $openInJavascript; ?>">g+</a>

    <a class="icon twitter" href="https://www.twitter.com/share?url=<?php echo $url; ?>" onclick="<?php echo $openInJavascript; ?>">Tweet</a>

    <a class="icon pinterest" href="https://pinterest.com/pin/create/button/?url=<?php echo $url; ?>&description=Handbid+Auction" onclick="<?php echo $openInJavascript; ?>">Share on Pinterest</a>
    <a class="icon email" href="mailto:?subject=Handbid+Auction&body=<?php echo $url; ?>" title="Share by Email">Email</a>
</div>