<?php
/**
 * @copyright Copyright (c) 2014-2015 Handbid Inc.
 * @category handbid
 * @package Handbid2-WordPress
 * @license Proprietary
 * @link http://www.handbid.com/
 * @author Master of Code (worldclass@masterofcode.com)
 */


//$url = 'https://' . $_SERVER['SERVER_NAME'] . '/' . $_SERVER['REQUEST_URI'];
$url = urlencode(HANDBID_FB_SHARE_URL);
$openInJavascript = "javascript:window.open(this.href,'', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=600,width=600');return false;";
?>

<div class="handbid-share-bar">
    <a class="icon" href="https://www.facebook.com/sharer.php?u=<?php echo $url; ?>" onclick="<?php echo $openInJavascript; ?>">
        <svg class="u-svg-icon">
            <use xlink:href="#facebook-icon"></use>
        </svg>
    </a>

    <a class="icon" href="https://plus.google.com/share?url=<?php echo $url; ?>" onclick="<?php echo $openInJavascript; ?>">
        <svg class="u-svg-icon">
            <use xlink:href="#googleplus-icon"></use>
        </svg>
        g+
    </a>

    <a class="icon" href="https://www.twitter.com/share?url=<?php echo $url; ?>" onclick="<?php echo $openInJavascript; ?>">
        <svg class="u-svg-icon">
            <use xlink:href="#twitter-icon"></use>
        </svg>
        Tweet
    </a>

    <a class="icon" href="https://pinterest.com/pin/create/button/?url=<?php echo $url; ?>&description=Handbid+Auction" onclick="<?php echo $openInJavascript; ?>">
        <svg class="u-svg-icon">
            <use xlink:href="#pinterest-icon"></use>
        </svg>
        Share on Pinterest
    </a>
    <a class="icon" href="mailto:?subject=Handbid+Auction&body=<?php echo $url; ?>" title="Share by Email">
        <svg class="u-svg-icon">
            <use xlink:href="#email-icon"></use>
        </svg>
        Email
    </a>
</div>