<?php
/**
 * @copyright Copyright (c) 2014-2015 Handbid Inc.
 * @category handbid
 * @package Handbid2-WordPress
 * @license Proprietary
 * @link http://www.handbid.com/
 * @author Master of Code (worldclass@masterofcode.com)
 */

$testimonials = $this->get("testimonials");
$singleTestimonial = $this->get("singleTestimonial");
$recentTestimonials = $this->get("recentTestimonials");
$displayTestimonials = $this->get("displayTestimonials");
$count = $this->get("count");
$perPage = $this->get("perPage");
$currentPage = $this->get("currentPage");
$offset = $this->get("offset");
?>
<div class="container container-fluid auction-timer-wrapper testimonials-wrapper">
    <?php if (count($testimonials)) {
        ?>
        <div id="testimonials-container" class="testimonials-container <?php echo ($singleTestimonial)?" container-align-center ":"";?>">
            <?php if(!$singleTestimonial) { ?>
                <h4 class="testimonials-header">Here are some comments from our customers</h4>
                <ul class="testimonials-list">
                    <?php foreach ($displayTestimonials as $testimonial) { ?>
                        <li>
                            <a href="<?php echo add_query_arg(["testimonial" => $testimonial->ID], get_permalink());?>" data-testimonial-id="<?php echo $testimonial->ID; ?>">
                                <img
                                    src="<?php echo wp_get_attachment_image_src(get_post_thumbnail_id($testimonial->ID), "medium")[0] ?>">
                                <span class="testimonial-title"><?php echo get_the_title($testimonial->ID); ?></span>
                                <?php $teaser = get_post_meta($testimonial->ID, "hb_teaser", true);
                                if(trim($teaser)){
                                ?>
                                <span class="testimonial-teaser"><?php echo $teaser; ?></span>
                                <?php }?>
                                <span
                                    class="testimonial-date"><?php echo date("F Y", strtotime($testimonial->post_date)) ?></span>
                            </a>

                        </li>
                    <?php } ?>
                </ul>
            <?php
                if($count > $perPage){
                    echo do_shortcode('[handbid_pager page_size=' . $perPage . ' page=' . $currentPage . ' total=' . $count . ' true_url=1 base="block" initial_point=1 ]');
                }
            } else {
                echo $this->partial('single-testimonial.phtml', [
                        'testimonial' => $singleTestimonial,
                        'is_initial' => true,
                    ]
                );
            }
            ?>
        </div>
        <div class="testimonials-sidebar">
            <?php if(!dynamic_sidebar('sidebar-testimonials')){?>
            <h4>RECENT TESTIMONIALS</h4>
            <p class="howto">What customers say about Handbid</p>
            <ul class="testimonials-list">
                <?php foreach($recentTestimonials as $testimonial){ ?>
                <li>
                    <a href="<?php echo add_query_arg(["testimonial" => $testimonial->ID], get_permalink());?>" data-testimonial-id="<?php echo $testimonial->ID;?>">
                        <img src="<?php echo wp_get_attachment_image_src( get_post_thumbnail_id($testimonial->ID), "medium" )[0] ?>">
                        <span class="testimonial-title"><?php echo get_the_title($testimonial->ID);?></span>
                        <span class="testimonial-date"><?php echo date("F Y", strtotime($testimonial->post_date))?></span>
                    </a>

                </li>
                <?php } ?>
            </ul>
            <?php  } ?>
            <h4 class="started-header">START YOUR AUCTION</h4>
            <p class="howto">Get started with your own
                Handbid auction today or reach
                out to us to learn more!</p>
            <a href="/get-started/" class="start-auction-button">Get Started</a>
        </div>
    <?php
    } else {
        echo "<h3>No Testimonials Yet</h3>";
    }?>
</div>