<?php

$tickets = $this->get('tickets');
$premium = floatval($this->get('premium'));
$currencyCode  = $this->get('currencyCode');
$currencySymbol = $this->get('currencySymbol');

if(is_array($tickets) and !empty($tickets))
{
    ?>
    <h4 class="purchase-header">
        Please confirm your purchases
    </h4>
    <table class="purchase-list">
        <thead>
        <tr>
            <th>Item</th>
            <th>Price</th>
            <th>Quantity</th>
            <th>Total</th>
        </tr>
        </thead>
        <tbody>
        <?php
        $tickets_price = 0;
        $surcharges = 0;
        $surchargeNames = [];
        foreach($tickets as $ticket)
        {
            $surcharges += ((!empty($ticket->surcharge)) ? $ticket->quantity * $ticket->surcharge : 0);

            if(!empty($ticket->surchargeName) && !empty($ticket->surcharge))
            {
                $surchargeNames[] = $ticket->surchargeName;
            }
            ?>
            <tr>
                <td>
                    <h6><?php echo $ticket->name; ?></h6>
                    <span><?php echo wp_unslash($ticket->description); ?></span>
                </td>
                <td>
                    <span title="<?php echo $currencyCode; ?>"><?php echo $currencySymbol; ?></span>
                    <?php echo $ticket->price; ?>
                </td>
                <td>
                    <?php echo $ticket->quantity; ?>
                </td>
                <td>
                    <span title="<?php echo $currencyCode; ?>"><?php echo $currencySymbol; ?></span>
                    <?php
                    $price =  $ticket->quantity * $ticket->price;
                    $tickets_price += $price;
                    echo $price;
                    ?>
                </td>
            </tr>
        <?php
        }
        $surchargeNames = array_unique($surchargeNames);
        if(empty($surchargeNames) || (count($surchargeNames) > 1)){
            $surchargeNames = 'Handling Fee';
        }
        else{
            $surchargeNames = $surchargeNames[0];
        }
        ?>
        </tbody>
    </table>

    <div class="discount-block">
        <form class="form-inline">
            <div class="form-group">
                <label for="discount-code">Apply a Discount Code</label>
                <input type="text" class="form-control" id="discount-code">
            </div>
            <button class="light-blue-solid-button loading-span-button" id="hb-apply-discount-code-button"><span>Apply</span></button>
        </form>
        <p class="discount-applied discount-error">
            Discount Error
        </p>
    </div>

    <?php
    $premium_amount = ((($tickets_price + $surcharges) * $premium) / 100);
    ?>
    <p class="purchase-block purchase-subtotal"  style="<?php echo $tickets_price ? '' : ' display:none '?>">Subtotal:
        <span>
            <span title="<?php echo $currencyCode; ?>"><?php echo $currencySymbol; ?></span>
            <span id="confirm-purchasing-subtotal"><?php echo $tickets_price; ?></span>
        </span>
    </p>
    <p class="purchase-block purchase-discount discount-applied discount-success"  style="display:none">Discount Applied:
        <span>
            <span title="<?php echo $currencyCode; ?>">(<?php echo $currencySymbol; ?></span>
            <span id="confirm-purchasing-discount">0</span>)
        </span>
    </p>
    <p class="purchase-block purchase-surcharges"  style="<?php echo $surcharges ? '' : ' display:none '?>"><?php echo $surchargeNames; ?>:
        <span>
            <span title="<?php echo $currencyCode; ?>"><?php echo $currencySymbol; ?></span>
            <span id="confirm-purchasing-surcharges"><?php echo $surcharges; ?></span>
        </span>
    </p>
    <p class="purchase-block purchase-premium" style="<?php echo $premium ? '' : ' display:none '?>">Auction Premium (<?php echo $premium; ?>%):
        <span>
            <span title="<?php echo $currencyCode; ?>"><?php echo $currencySymbol; ?></span>
            <span id="confirm-purchasing-premium" data-premium="<?php echo $premium; ?>"><?php echo number_format($premium_amount, 2, ".", ""); ?></span>
        </span>
    </p>

    <?php
    $total = $tickets_price + $premium_amount + $surcharges;
    ?>
    <p class="purchase-block purchase-total">Grand Total:
        <span>
            <span title="<?php echo $currencyCode; ?>"><?php echo $currencySymbol; ?></span>
            <span id="confirm-purchasing-total"><?php echo number_format($total, 2, ".", ""); ?></span>
        </span>
    </p>

    <?php
}
else{
    ?>
    <h3 class="cannot-load">Cannot load selected tickets. Please go back and select another.</h3>
    <?php

}