<?php
/**
 * @copyright Copyright (c) 2014-2015 Handbid Inc.
 * @category handbid
 * @package Handbid2-WordPress
 * @license Proprietary
 * @link http://www.handbid.com/
 * @author Master of Code (worldclass@masterofcode.com)
 */

$myAuctions = $this->get( 'myAuctions' );
?>
    <ul class="simple-list  handbid-list-of-active-auctions">
        <?php
        if (count($myAuctions) > 0) {
            forEach ($myAuctions as $auction) {
                if ($auction->status == "open") {
                    ?>
                    <li class="row <?php echo $auction->status; ?>" data-handbid-active-profile-auction="<?php echo $auction->id; ?>">
                        <div class="col-md-2"><img class="full-width-image"
                                                   src="<?php
                                                   $image = (isset($auction->logo) and isset($auction->logo->medium))?$auction->logo->medium:"";
                                                   $image = ($image) ? $image : (isset($auction->imageUrl) ? $auction->imageUrl : "");
                                                   $imageUrlPath = parse_url($image);
                                                   $image = ($imageUrlPath["scheme"]) ? $image : "http://" . $image;
                                                   echo $image; ?>"/>
                        </div>
                        <div class="col-md-7">
                            <h4><?php echo $auction->name; ?></h4>
                            <a href="/organizations/<?php echo $auction->organization->key; ?>"
                               class="org-link"><?php echo $auction->organization->name; ?></a>
                        </div>
                        <div class="col-md-3">
                            <a class="cta-link" href="/auctions/<?php echo $auction->key; ?>">See Auction</a>
                        </div>
                    </li>
                <?php
                }
            }
        } else {
            ?>
            <p>You are not registered for any upcoming auctions.</p>
        <?php
        }
        ?>
    </ul>

    <div class="handbid-hidden-of-active-auctions">
        <?php
        if (count($myAuctions) > 0) {
            forEach ($myAuctions as $auction) {
                ?>
                <input type="hidden" data-hidden-active-auction="<?php echo $auction->id; ?>">
            <?php
            }
        }
        ?>
    </div>

<?php
