<?php
if ($this->get('bids')) {
    $bids = $this->get('bids');
} else {
    echo "I could not find your bids";
    return;
}

?>
<table class="bidder-table">
    <thead>
    <tr>
        <th>Amount</th>
        <th>Item</th>
        <th>Date Inserted</th>
    </tr>
    </thead>
    <?php forEach ($bids as $bid) {
        ?>
        <tr>
            <td>
                <?php echo $bid['amount']; ?>
            </td>
            <td>
                <?php echo $bid['name']; ?>
            </td>
            <td>
                <?php echo date("m/d/Y g:i a", $bid['microtime']); ?>
            </td>
        </tr>
    <?php
    }
    ?>

</table>