<?php
if (!is_null($this->get('winning'))) {
    $winning = $this->get('winning');
    $losing  = $this->get('losing');
    $auction = $this->get('auction');
} else {
    echo "I could not find your bids.";
    return;
}
?>
<div class="bidder-info-container winning-losing-bids">
    <?php
    if (!$winning && !$losing) {
        echo "You have no bids";
    }
    ?>

    <?php if ($winning) { ?>

        <h4 class="winning-item">Winning</h4>
        <table class="bidder-table">
            <thead>
            <tr>
                <th>Amount</th>
                <th>Item</th>
                <th>Date Inserted</th>
            </tr>
            </thead>
            <?php
            forEach ($winning as $bid) {
                ?>
                <tr>
                    <td>
                        <?php echo '$' . $bid->amount; ?>
                    </td>
                    <td>
                        <a href="/auctions/<?php echo $auction->key; ?>/item/<?php echo $bid->meta['itemKey']; ?>"><?php echo ($bid->meta['itemName']) ? $bid->meta['itemName'] : $bid->name; ?></a>
                    </td>
                    <td>
                        <?php echo date("m/d/Y g:i a", $bid->microtime); ?>
                    </td>
                </tr>
            <?php } ?>
        </table>
    <?php } ?>


    <?php if ($losing) { ?>
        <h4 class="losing-item">Losing</h4>
        <table class="bidder-table">
            <thead>
            <tr>
                <th>Amount</th>
                <th>Item</th>
                <th>Date Inserted</th>
            </tr>
            </thead>
            <?php
            forEach ($losing as $bid) {
                ?>
                <tr>
                    <td>
                        <?php echo '$' . $bid->amount; ?>
                    </td>
                    <td>
                        <a href="/auctions/<?php echo $auction->key; ?>/item/<?php echo $bid->meta['itemKey']; ?>"><?php echo ($bid->meta['itemName']) ? $bid->meta['itemName'] : $bid->name; ?></a>
                    </td>
                    <td>
                        <?php echo date("m/d/Y g:i a", $bid->microtime); ?>
                    </td>
                </tr>
            <?php
            } ?>

        </table>

    <?php } ?>
</div>