<?php
if (!is_null($this->get('cards'))) {
    $cards = $this->get('cards');
} else {
    echo "I could not find your credit cards.";
    return;
}
?>
<div class="bidder-info-container credit-card">
    <?php
    if (count($cards) > 0) {
?>
    <table class="bidder-table">
        <thead>
        <tr>
            <th>Name</th>
            <th>Card Number</th>
            <th>Expiration Month</th>
            <th>Expiration Year</th>
        </tr>
        </thead>
<?php
    forEach ($cards as $card) {
    ?>
        <tr>
            <td>
                <?php echo $card->nameOnCard; ?>
            </td>
            <td>
                xxxx xxxx xxxx <?php echo $card->lastFour; ?>
            </td>
            <td>
                <?php echo $card->expMonth; ?>
            </td>
            <td>
                <?php echo $card->expYear; ?>
            </td>
        </tr>
        <?php
    }
    ?>

    </table>
    <?php
        } else { ?>
        You have no cards on file.
    <?php } ?>
    <?php echo do_shortcode('[handbid_bidder_credit_card_form]'); ?>
</div>