<a class="button greenButton" href="#handbid-add-card-dialog">Add Credit Card</a>
<div class="modal edit-creditcard-modal handbid-modal" id="handbid-add-card-dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-header">
            <h2>Add Card</h2>
            <a href="#close" class="btn-close" aria-hidden="true">×</a> <!--CHANGED TO "#close"-->
        </div>
        <div class="modal-body">
            <div class="creditcard-wrapper">
                <form class="creditcard-template" action="<?php echo get_admin_url() . 'admin-post.php'; ?>" method="post" enctype="multipart/form-data">
                    <div class="creditcard">
                        <p>
                            <div class="cc-section">
                                <label>Name on Card</label>
                                <input type="text" name="nameOnCard" class="checkout-input checkout-name"
                                       placeholder="Name on Card">
                            </div>
                            <div class="cc-section">
                                <label>Expiration</label>
                                <input type="text" name="expMonth" class="checkout-input checkout-exp" placeholder="MM">
                                <input type="text" name="expYear" class="checkout-input checkout-exp" placeholder="YYYY">
                            </div>
                        </p>
                        <p>
                            <div class="cc-section bottom-row">
                                <label>Card Number</label>
                                <input type="text" name="cardNum" class="checkout-input checkout-card"
                                       placeholder="Credit Card Number">
                            </div>
                            <div class="cc-section bottom-row">
                                <label>CVC</label>
                                <input type="text" name="cvc" class="checkout-input checkout-cvc" placeholder="CVC">
                                <a class="cvc-info" title="On most cards, the 3-digit security code is on the back, to the right of the signature. On American Express cards, the 4-digit security code is on the front, to the top-right of the card number.">?</a>
                            </div>
                        </p>
                    </div>
                    <input type="submit" class="button greenButton" value="submit"/>
                    <input type='hidden' name='form-id' value='handbid-add-creditcard'/>
                    <input type='hidden' name='action' value='submit-form'/>
                </form>
            </div>
        </div>
    </div>
</div>