<?php
if (!is_null($this->get('cards'))) {
    $cards = $this->get('cards');
} else {
    echo "I could not find your credit cards.";
    return;
}
?>
<div class="bidder-info-container credit-card">
    <?php
    if (count($cards) > 0) {
        ?>

        <ul class="simple-list bid-history">
            <?php
            forEach ($cards as $card) {
                ?>
                <li class="row">
                    <div class="col-md-3">
                        <h4>Name</h4>
                        <?php echo $card->nameOnCard; ?>
                    </div>
                    <div class="col-md-3">
                        <h4>Card Number</h4>
                        xxxx xxxx xxxx <?php echo $card->lastFour; ?>
                    </div>
                    <div class="col-md-3">
                        <h4>Exp. Date</h4>
                        <?php echo $card->expMonth . '/' . $card->expYear; ?>
                    </div>
                    <div class="col-md-3">
                        <a class="button pink-solid-button" href="#" data-handbid-delete-credit-card="<?php echo $card->_id; ?>"><?php echo __('Delete'); ?></a>
                    </div>
                </li>
            <?php
            }
            ?>
        </ul>

    <?php
    } else { ?>
        <div class="row">

            <p style="text-align: left;">Note: Not all auctions use credit cards</p>

            <label class="no-results">
                You have no cards on file.
            </label>
        </div>
    <?php } ?>
    <?php
    //was it too hard to create a [handbid_bidder_cc_form]? thanks
    //echo do_shortcode('[handbid_bidder_profile_form template="views/bidder/credit-card-form"]');
    echo do_shortcode('[handbid_bidder_cc_form]');
    ?>
</div>