<?php

$countries = $this->get("countries");

?>


<div class="handbid-modal contact-body" data-handbid-modal-key="login-modal">
<a href="#" class="modal-close">X</a>

<div class="page-body connect-page">

    <div class="container-fluid container-tab active-container" data-tab-name="login-form">
        <div class="row">
            <div class="col-xs-12 signup-form">
                <div class="handbid-form signup-form">
                    <h3>LOGIN</h3>
                    <h4>to your Handbid account</h4>

                    <form id="hb-login-form" class="form" method="POST" action="<?php echo get_admin_url() . 'admin-post.php'; ?>"
                          enctype="multipart/form-data">


                        <div class="row">
                            <div class="form-group col-md-12">
                                <h2>Handbid Bidder Login</h2>
                                <h5>Login with your bidder account information below. Not sure if you have an account?
                                    <a class="login-popup-link" data-target-tab="get-started">Click here</a> to get
                                    started.</h5>
                                <input placeholder="Email or Phone Number" type="text" name="username" value=""
                                       class="form-control cleanable-input" id="hb-login-form-username">
                            </div>
                        </div>


                        <div class="row">
                            <div class="form-group col-md-12">
                                <input placeholder="Password" type="text" name="pin" value=""
                                       class="form-control cleanable-input"  id="hb-login-form-password">
                                <h5>Having trouble logging in? <a class="login-popup-link"
                                                                  data-target-tab="forgot-pass">Click here</a> for help.
                                </h5>

                            </div>
                        </div>

                        <div class="modal-footer">
                            <button type="submit" class="btn btn-info signup" id="hb-login-form-submit"><span>Sign Up</span></button>

                            <a class="btn btn-info signup login-popup-link" data-target-tab="tutorial-info-1">Tutorial</a>
                        </div>

                        <div class="row">
                            <div class="form-group col-md-12">
                                <h2>Trying to manage your Handbid account?</h2>
                                <h5><a target="_blank" href="http://manager.handbid.com/login">Click here</a> to access
                                    Handbid Auction Manager.</h5>

                            </div>
                        </div>

                        <input type='hidden' name='redirect' value='<?php echo $_SERVER["REQUEST_URI"] ?>' id="hb-login-form-redirect"/>
                        <input type='hidden' name='form-id' value='handbid-login'/>
                        <input type='hidden' name='nonce' value='<?php echo apply_filters("handbid_create_nonce", date("d.m.Y") . "login");?>' id="hb-login-form-nonce"/>
                        <input type='hidden' name='action' value='handbid_ajax_login' id="hb-login-form-action"/>
                    </form>

                </div>
            </div>
        </div>
    </div>

    <div class="container-fluid container-tab" style="display: none" data-tab-name="forgot-pass">
        <div class="row">
            <div class="col-xs-12 signup-form">
                <div class="handbid-form signup-form">
                    <h3>LOGIN</h3>
                    <h4>to your Handbid account</h4>

                    <form class="form" method="POST" action="<?php echo get_admin_url() . 'admin-post.php'; ?>"
                          enctype="multipart/form-data">


                        <div class="row">
                            <div class="form-group col-md-12">
                                <h2>Forgot your Password or Login Info?</h2>
                                <h5>Not sure if you have an account? <a class="login-popup-link"
                                                                        data-target-tab="get-started">Click here</a> to
                                    get started.</h5>
                            </div>
                        </div>


                        <div class="row">
                            <div class="form-group col-md-12">
                                <h5>Enter your email or phone number and we will send you instructions on how to get
                                    logged in.</h5>

                                <input placeholder="Email or Phone Number" type="text" name="username" value=""
                                       class="form-control cleanable-input">

                            </div>
                        </div>

                        <div class="modal-footer">
                            <button type="submit" class="btn btn-info signup">Send Instructions</button>
                            <a class="btn btn-info signup login-popup-link" data-target-tab="forgot-pass-sent">Send
                                Instructions</a>
                        </div>

                    </form>

                </div>
            </div>
        </div>
    </div>

    <div class="container-fluid container-tab" style="display: none" data-tab-name="forgot-pass-sent">
        <div class="row">
            <div class="col-xs-12 signup-form">
                <div class="handbid-form signup-form">
                    <h3>LOGIN</h3>
                    <h4>to your Handbid account</h4>


                    <div class="row">
                        <div class="form-group col-md-12">
                            <h2 class="center-aligned-text">Your Login Information has been Sent!</h2>
                            <h5 class="center-aligned-text">Check your email or phone for the information.</h5>
                        </div>
                    </div>

                    <div class="modal-footer center-aligned-text">
                        <a class="btn btn-info signup login-popup-link" data-target-tab="login-form">Start Over</a>
                    </div>

                </div>
            </div>
        </div>
    </div>

    <div class="container-fluid container-tab" style="display: none" data-tab-name="get-started">
        <div class="row">
            <div class="col-xs-12 signup-form">
                <div class="handbid-form signup-form">
                    <h3>GETTING STARTED</h3>
                    <h4>with Handbid</h4>

                    <form class="form" method="POST" action="<?php echo get_admin_url() . 'admin-post.php'; ?>"
                          enctype="multipart/form-data">

                        <div class="row">
                            <div class="form-group col-md-12">
                                <h5 class="center-aligned-text">Handbid lets you bid from anywhere using any or all
                                    following devices.</h5>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-lg-4 center-aligned-text">
                                <img class="img-circle"
                                     src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw=="
                                     alt="Generic placeholder image" width="140" height="140">

                                <h2 class="center-aligned-text">YOUR PHONE</h2>
                                <h4>Using the Handbid App for Android or Iphone</h4>

                                <p class="howto">Are you a Windows Phone or Blackberry user? Just navigate to
                                    handbid.com from your phone's </p>
                            </div>
                            <div class="col-lg-4 center-aligned-text">
                                <img class="img-circle"
                                     src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw=="
                                     alt="Generic placeholder image" width="140" height="140">

                                <h2 class="center-aligned-text">IPADS</h2>
                                <h4>Provided for you to use at the Auction Event</h4>
                            </div>
                            <div class="col-lg-4 center-aligned-text">
                                <img class="img-circle"
                                     src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw=="
                                     alt="Generic placeholder image" width="140" height="140">

                                <h2 class="center-aligned-text">YOUR COMPUTER</h2>
                                <h4>From the Handbid.com website</h4>
                            </div>
                        </div>

                        <div class="row">
                            <div class="form-group col-md-12">
                                <h5 class="center-aligned-text"><br><br><br>To get started, we need to know if you need
                                    to create a new account or if you were invited to sign up to an auction.<br><br><br>
                                </h5>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-lg-4 center-aligned-text">
                                <h4>Got an invite code from an auction host?</h4>
                                <a class="btn btn-info signup login-popup-link" data-target-tab="use-invite-code">Use
                                    Invite Code</a>
                            </div>
                            <div class="col-lg-4 center-aligned-text">
                                <h4>Need to setup an account?</h4>
                                <a class="btn btn-info signup login-popup-link"
                                   data-target-tab="register-form">Register</a>
                            </div>
                            <div class="col-lg-4 center-aligned-text">
                                <h4>Already have an account?</h4>
                                <a class="btn btn-info signup login-popup-link" data-target-tab="login-form">Login</a>
                            </div>
                        </div>

                        <div class="row">
                            <div class="form-group col-md-12">
                                <h5 class="center-aligned-text"><br><br><br>Not sure? Just click on the "Register" and
                                    we will figure it out from there.</h5>
                            </div>
                        </div>

                    </form>

                </div>
            </div>
        </div>
    </div>


</div>

<div class="container-fluid container-tab" style="display: none" data-tab-name="use-invite-code">
    <div class="row">
        <div class="col-xs-12 signup-form">
            <div class="handbid-form signup-form">
                <h3>GETTING STARTED</h3>
                <h4>with Handbid</h4>


                <div class="row">
                    <div class="form-group col-md-12">
                        <h2 class="center-aligned-text">You were invited to use Handbid!</h2>
                        <h5 class="center-aligned-text">Welcome! We are so glad you are here. Enter your invite code
                            below and lets get you setup.</h5>
                    </div>
                </div>


                <div class="row">
                    <div class="form-group col-md-12">
                        <input placeholder="Enter code" type="text" name="code" value=""
                               class="form-control cleanable-input">
                    </div>
                </div>


                <div class="row">
                    <div class="form-group col-md-12">
                        <h5 class="center-aligned-text">Handbid can't find your auction? Perhaps it is not setup yet.
                            You can <a class="login-popup-link" data-target-tab="register-form">register</a> without it
                            and connect to it later.</h5>
                    </div>
                </div>

                <div class="modal-footer center-aligned-text">
                    <a class="btn btn-info signup login-popup-link" data-target-tab="register-form">Find My Auction</a>
                </div>

            </div>
        </div>
    </div>
</div>

<div class="container-fluid container-tab register-tab" style="display: none" data-tab-name="register-form">
    <div class="row">
        <div class="col-xs-12 signup-form">
            <div class="handbid-form signup-form">
                <h3>GETTING STARTED</h3>
                <h4>with Handbid</h4>
                <h4>CREATING YOUR BIDDER ACCOUNT<br></h4>

                <div class="row errorsRow" style="display: none;">
                    <div class="form-group col-md-12 errorsContainer">

                    </div>
                </div>

                <div class="row">
                    <div class="form-group col-md-12">
                        <input id="reg-firstname" placeholder="First Name *" type="text" name="firstname" value=""
                               class="col-md-6 has-question-icon has-popover cleanable-input copyable-field" data-copy-to="confirm-firstname" data-toggle="popover" data-trigger="focus"
                               title="ENTER IN YOUR FIRST AND LAST NAME"
                               data-content="We need your name so we know what to call you and for your receipt at the end. Your identity (by default) will be concealed using a Paddle Number or Alias."
                            required
                            data-required-message="First Name field is required">
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-md-12">
                        <input id="reg-lastname" placeholder="Last Name *" type="text" name="lastname" value=""
                               class="col-md-6 has-question-icon has-popover cleanable-input copyable-field" data-copy-to="confirm-lastname" data-toggle="popover" data-trigger="focus"
                               title="ENTER IN YOUR FIRST AND LAST NAME"
                               data-content="We need your name so we know what to call you and for your receipt at the end. Your identity (by default) will be concealed using a Paddle Number or Alias."
                               required
                               data-required-message="Last Name field is required">
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-md-12">
                        <input id="reg-email" placeholder="eMail" type="text" name="email" value=""
                               class="col-md-6 has-question-icon has-popover cleanable-input copyable-field is-email" data-copy-to="confirm-email" data-toggle="popover" data-trigger="focus"
                               title="ENTER IN YOUR EMAIL ADDRESS"
                               data-content="We will use your eMail to identify you and also to send you a receipt at the end of the auction. Don't worry, you won't end up on any list because of us. You can review our privacy policy for more details."
                               data-not-email-message="Please, provide valid email address" >
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-md-12">
                        <input id="reg-password" placeholder="Password (for use only on the webSite)" type="text"
                               name="password" value=""
                               class="col-md-6 has-question-icon has-popover cleanable-input copyable-field" data-copy-to="confirm-password" data-toggle="popover" data-trigger="focus"
                               title="CREATE A PASSWORD"
                               data-content="You will need a password to login on from Handbid.com. You will not need to use this password to login from the mobile apps or from the iPads. Please, ceep this password secure."
                               required
                               data-required-message="Password field is required">
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-md-12">
                        <input id="reg-password-confirm" placeholder="Confirm your Password" type="text"
                               name="password-confirm" value=""
                               class="col-md-6 has-question-icon has-popover cleanable-input" data-toggle="popover" data-trigger="focus"
                               title="CREATE A PASSWORD"
                               data-content="You will need a password to login on from Handbid.com. You will not need to use this password to login from the mobile apps or from the iPads. Please, ceep this password secure."
                               data-mismatch-message="Password mismatch">
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-md-12">
                        <select id="reg-phone-code" name="phone-code"
                                class="col-md-2 copyable-field"  data-copy-to="confirm-phone-code">
                            <?php
                            foreach($countries as $country){
                                echo "<option value='" . $country["d_code"] . "' " . selected("US", $country["code"], false) . ">" . $country["name"] . "</option>";
                            }
                            ?>
                        </select>
                        <input id="reg-phone-number" placeholder="Cell Phone *" type="text" name="phone-number" value=""
                               class="col-md-4 has-question-icon has-popover cleanable-input copyable-field" data-copy-to="confirm-phone-number" data-toggle="popover" data-trigger="focus"
                               title="PROVIDE YOUR CELL PHONE"
                               data-content="If you intend to bid from your smartphone using the Handbid App, please provide number for that here and tell us what type of phone you have. We will send instructions to that phone on how to get setup."
                               required
                               data-required-message="Phone field is required">
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-md-12">
                        <h5>What kind of phone do you have?</h5>

                        <div class="col-md-6">
                            <label for="reg-phone-type-1" class="col-xs-4 radio-label">
                                <input type="radio" id="reg-phone-type-1" name="phone-type" value="iphone" class="copyable-field" data-copy-to="confirm-phone-type" checked>
                                iPhone</label>
                            <label for="reg-phone-type-2" class="col-xs-4 radio-label">
                                <input type="radio" id="reg-phone-type-2" name="phone-type" value="android" class="copyable-field" data-copy-to="confirm-phone-type">
                                Android</label>
                            <label for="reg-phone-type-3" class="col-xs-4 radio-label">
                                <input type="radio" id="reg-phone-type-3" name="phone-type" value="other" class="copyable-field" data-copy-to="confirm-phone-type">
                                Other</label>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="form-group col-md-12">
                        <h5>Add me as a bidder to this Auction</h5>
                        <input id="reg-add-to-auction" placeholder="" type="text" name="add-to-auction" value=""
                               class="col-md-6 cleanable-input copyable-field"  data-copy-to="confirm-add-to-auction" >
                    </div>
                </div>

                <div class="modal-footer center-aligned-text">
                    <div class="col-md-4">
                        <a class="go-back-button login-popup-link" data-target-tab="login-form">< I have an Account -
                            Login</a>
                    </div>
                    <div class="col-md-4">
                        <label for="reg-agree-terms" class="radio-label agree-terms-label">
                            <input type="checkbox" id="reg-agree-terms" name="agree-terms" value="agree"
                                   required
                                   data-required-message="You must agree to the bidder terms and conditions">
                            You agree to the <a target="_blank" href="#">bidder terms and conditions</a></label>
                    </div>
                    <div class="col-md-4">
                        <a class="btn btn-info signup login-popup-link register-next" data-target-tab="register-form-confirm">NEXT</a>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>


<div class="container-fluid container-tab register-confirm-tab" style="display: none" data-tab-name="register-form-confirm">
    <div class="row">
        <div class="col-xs-12 col-md-6 col-md-offset-3 signup-form">
            <div class="handbid-form signup-form">
                <h3>GETTING STARTED</h3>
                <h4>with Handbid</h4>
                <h4>YOUR HANDBID ACCOUNT IS SETUP<br></h4>

                <div class="row errorsRow" style="display: none;">
                    <div class="form-group col-md-12 errorsContainer">

                    </div>
                </div>

                <div class="row">
                    <div class="form-group col-md-12">
                        <h4>please confirm your information below</h4>
                    </div>
                </div>

                <div class="row">
                    <div class="form-group col-md-12">
                        <input id="confirm-firstname" placeholder="First Name" type="text" name="firstname" value=""
                               class="col-xs-12  cleanable-input"
                               required
                               data-required-message="First Name field is required">
                    </div>
                    <div class="form-group col-md-12">
                        <input id="confirm-lastname" placeholder="Last Name" type="text" name="lastname" value=""
                               class="col-xs-12 cleanable-input"
                               required
                               data-required-message="Last Name field is required">
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-md-12">
                        <input id="confirm-email" placeholder="eMail" type="text" name="email" value=""
                               class="col-md-12 cleanable-input is-email"
                               data-not-email-message="Please, provide valid email address" >
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-md-12">
                        <select id="confirm-phone-code" name="phone-code"
                                class="col-md-4">
                            <?php
                            foreach($countries as $country){
                                echo "<option value='" . $country["d_code"] . "' " . selected("US", $country["code"], false) . ">" . $country["name"] . "</option>";
                            }
                            ?>
                        </select>
                        <input id="confirm-phone-number" placeholder="Cell Phone" type="text" name="phone-number"
                               value=""
                               class="col-md-4 has-question-icon has-popover cleanable-input">
                        <select class="col-md-4" id="confirm-phone-type">
                            <option name="phone-type" value="iphone" selected>iPhone</option>
                            <option name="phone-type" value="android">Android</option>
                            <option name="phone-type" value="other">Other</option>
                        </select>
                    </div>
                </div>

                <div class="row">
                    <div class="form-group col-md-12">
                        <h5>Add me as a bidder to this Auction</h5>
                        <input id="confirm-add-to-auction" placeholder="" type="text" name="add-to-auction" value=""
                               class="col-md-12 cleanable-input">
                    </div>
                </div>
                <input type="hidden" id="confirm-password" name="password">

                <div class="modal-footer center-aligned-text">
                    <a class="btn btn-info signup login-popup-link register-confirm" data-target-tab="register-complete"><span>COMPLETE</span></a>

<!--                    <input type='hidden' name='redirect' value='--><?php //echo $_SERVER["REQUEST_URI"] ?><!--' id="hb-reg-form-redirect"/>-->
                    <input type='hidden' name='form-id' value='handbid-register'/>
                    <input type='hidden' name='nonce' value='<?php echo apply_filters("handbid_create_nonce", date("d.m.Y") . "register");?>' id="hb-reg-form-nonce"/>
                    <input type='hidden' name='action' value='handbid_ajax_registration' id="hb-reg-form-action"/>
                </div>

            </div>
        </div>
    </div>
</div>


<div class="container-fluid container-tab" style="display: none" data-tab-name="register-complete">
    <div class="row">
        <div class="col-xs-12 col-md-6 col-md-offset-3 signup-form">
            <div class="handbid-form signup-form">
                <h3>GETTING STARTED</h3>
                <h4>with Handbid</h4>
                <h4>REGISTRATION COMPLETE!<br></h4>

                <h3 class="bidder-name" id="reg-complete-name">Fred Flinstone</h3>
                <h4 class="paddle-number-info">your paddle number for the</h4>

                <h3 class="auction-name" id="reg-complete-auction">Night at the Museum</h3>

                <h1 class="paddle-number" id="reg-paddle-number">192</h1>
                <div class="center-aligned-text bottom-margin">
                    <span class="what-is-paddle-number">What is a <a href="#" target="_blank">Paddle Number</a>?</span>
                </div>

                <div class="modal-footer center-aligned-text">
                    <div class="col-xs-12 col-md-6">
                        <a class="btn btn-info signup login-popup-link" data-target-tab="tutorial-info-1">Check out our
                            tutorial</a>
                    </div>
                    <div class="col-xs-12 col-md-6">
                        <a class="btn btn-info signup" href="/auctions/">Start Bidding</a>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>


<div class="container-fluid container-tab" style="display: none" data-tab-name="tutorial-info-1">
    <div class="row">
        <div class="row col-xs-12 col-md-6 col-md-offset-3 signup-form">
            <div class="handbid-form signup-form">
                <h3>GETTING STARTED</h3>
                <h4>with Handbid</h4>
                <h4>HANDBID 101<br></h4>
                <h4>Step 1<br></h4>

                <h3>How do you want to bid?</h3>


                <div class="row" role="tablist">
                    <div class="col-lg-4 center-aligned-text active tutorialTabsContainer"  role="presentation">
                        <a href="#your-phone" aria-controls="your-phone" role="tab" data-toggle="tab" class="tutorialTabs">
                        <img class="img-circle"
                             src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw=="
                             alt="Generic placeholder image" width="140" height="140">
                        <h2 class="center-aligned-text">YOUR PHONE</h2>
                            </a>
                    </div>
                    <div class="col-lg-4 center-aligned-text tutorialTabsContainer"  role="presentation">
                        <a href="#ipads" aria-controls="ipads" role="tab" data-toggle="tab" class="tutorialTabs">
                        <img class="img-circle"
                             src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw=="
                             alt="Generic placeholder image" width="140" height="140">
                        <h2 class="center-aligned-text">IPADS</h2>
                            </a>
                    </div>
                    <div class="col-lg-4 center-aligned-text tutorialTabsContainer"  role="presentation">
                        <a href="#your-comp" aria-controls="your-comp" role="tab" data-toggle="tab" class="tutorialTabs">
                        <img class="img-circle"
                             src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw=="
                             alt="Generic placeholder image" width="140" height="140">
                        <h2 class="center-aligned-text">YOUR COMPUTER</h2>
                            </a>
                    </div>
                </div>

                <div class="tab-content">

                    <div role="tabpanel" class="tab-pane active center-aligned-text" id="your-phone">
                        <h4>You can download the Handbid App for Android or iPhone.<br></h4>
                        <p>Watch a brief <a href="#" target="_blank">video tutorial</a> on how the App works.
                        </p>
                        <div class="row">
                            <h4>TEXT INSTRUCTIONS TO MY PHONE</h4>
                        <input id="reg-phone-number" placeholder="Cell Phone" type="text" name="phone-number" value=""
                               class="col-xs-12 col-md-6 col-md-offset-3  cleanable-input"
                               >
                        <button class="btn btn-info signup">SEND TEXT</button>
                        </div>
                    </div>

                    <div role="tabpanel" class="tab-pane center-aligned-text" id="ipads">
                        <h4>Don't have a smartphone? Not sure you will bring it?<br></h4>
                        <p>No worries! You can bid from iPads at the event. The iPads provided will allow you to bid on any ithem on the auction. You will be given assistance on how to place bids when you are at the event.
                        </p>
                        <p>
                            Watch a brief <a href="#" target="_blank">video tutorial</a> on how the iPad works.
                        </p>
                    </div>

                    <div role="tabpanel" class="tab-pane center-aligned-text" id="your-comp">
                        <h4>You can bid right from your computer or smartphone web browser!<br></h4>
                        <p>You can go to Handbid.com right now, find your auction and start bidding.<br>
                        </p>
                        <a class="btn btn-info signup" href="/auctions/">Start Bidding</a>
                    </div>
                </div>



            </div>
        </div>
        <div class="row center-aligned-text">
            <div class="col-md-4">
                <a class="go-back-button login-popup-link" data-target-tab="register-complete">< Go Back</a>
            </div>
            <div class="col-md-4">

            </div>
            <div class="col-md-4">
                <a class="go-back-button login-popup-link" data-target-tab="tutorial-info-2">Next ></a>
            </div>
        </div>


    </div>
</div>


<div class="container-fluid container-tab" style="display: none" data-tab-name="tutorial-info-2">
    <div class="row">
        <div class="row col-xs-12 col-md-6 col-md-offset-3 signup-form">
            <div class="handbid-form signup-form">
                <h3>GETTING STARTED</h3>
                <h4>with Handbid</h4>
                <h4>HANDBID 101<br></h4>
                <h4>Step 2<br></h4>

                <h3>Handbid Bidding Tips</h3>


                <ul class="handbid-tips">
                    <li>
                        <h2>Set MaxBids to avoid losing that treasured item</h2>
                        <p>Do you really want to win that Diamond Pendant? Don't rely on your craftiness and swift finger to place that last minute bid.
                        Instead, set a MaxBid on it and forget about it! Handbid will bid for you automatically up to that amount. And trust us, Handbid doesn't lose.
                        That bid will go in on time</p>
                    </li>
                    <li>
                        <h2>Make Sure you are getting notified when you are not at your computer</h2>
                        <p>Even if you are not bidding from the Apps, you can still get text notifications when you are outbid.
                        Just enter a valid cell phone number into your profile and turn on SMS notifications in your settings.
                        You can easily turn these off later if you want to stop getting messages.</p>
                    </li>
                    <li>
                        <h2>Understand how Extended Biding Works</h2>
                        <p>Your auction host MAY have enabled this feature. It will indicate that it is on when you are viewing the auction page.
                        Extended bidding will keep specific items open AFTER the auction closes if a last minute bid was placed.
                        So, if you think you can snipe that item at the item by placing a bid right before time expires, you may just be
                        extending the item longer for others to bid.</p>
                    </li>
                    <li>
                        <h2>View your Invoice and Pay From your Phone or Computer</h2>
                        <p>At the end of the auction, you will receive a notification with a link to your invoice in the app or by clicking on the
                        text message you received. You can also view the invoice from your profile at Handbid.com. If the auction manager
                        has enabled the Handbid payment system, then you will be able to pay your invoice directly.</p>
                    </li>
                </ul>



            </div>
        </div>
        <div class="row center-aligned-text">
            <div class="col-md-4">
                <a class="go-back-button login-popup-link" data-target-tab="tutorial-info-1">< Go Back</a>
            </div>
            <div class="col-md-4">

            </div>
            <div class="col-md-4">
                <a class="go-back-button login-popup-link" data-target-tab="tutorial-info-3">Next ></a>
            </div>
        </div>


    </div>
</div>


<div class="container-fluid container-tab" style="display: none" data-tab-name="tutorial-info-3">
    <div class="row">
        <div class="row col-xs-12 col-md-6 col-md-offset-3 signup-form">
            <div class="handbid-form signup-form">
                <h3>GETTING STARTED</h3>
                <h4>with Handbid</h4>
                <h4>HANDBID 101<br></h4>
                <h4>Step 3<br></h4>

                <h3>How to get Help</h3>


                <ul class="handbid-tips">
                    <li>
                        <h2>Have you a question about auction or auction items?</h2>
                        <p>Best to contact the auction managers and ask them. Your auction manager information will be provided
                        to you by them when you are invited or register for the auction. Please contact them first as they will
                        have the quickest answer about whether or not Disney Vacation has an expiration date on it or not.</p>
                    </li>
                    <li>
                        <h2>Not sure how to use Handbid or bid?</h2>
                        <p>Click on the help button either in the app (from the menu) or on the bottom right of the website
                            (handbid.com) and ask us for help.</p>
                    </li>
                </ul>

                <h3>Thats all we have.</h3>
                <h4>We hope the quick tutorial was helpful. Happy Bidding!</h4>


                    <div class="row center-aligned-text">
                        <a class="btn btn-info signup login-popup-link" data-target-tab="login-form">EXIT TUTORIAL</a>
                    </div>

            </div>
        </div>
        <div class="row center-aligned-text">
            <div class="col-md-4">
                <a class="go-back-button login-popup-link " data-target-tab="tutorial-info-2">< Go Back</a>
            </div>
            <div class="col-md-8">

            </div>
        </div>


    </div>
</div>


</div>
