<?php
/**
 * @copyright Copyright (c) 2014-2015 Handbid Inc.
 * @category handbid
 * @package Handbid2-WordPress
 * @license Proprietary
 * @link http://www.handbid.com/
 * @author Master of Code (worldclass@masterofcode.com)
 */

$countries = $this->get("countries");
$in_page = $this->get("in_page");
$is_logged_in = $this->get("is_logged_in");
$auction = $this->get("auction");
$auctionRequiresCC = $this->get("auctionRequiresCC");
if($in_page){
    $redirectLink = (isset($_SERVER["HTTP_REFERER"]) and $_SERVER["HTTP_REFERER"] != get_permalink()) ? $_SERVER["HTTP_REFERER"] : "/auctions/";
}
else{
    $redirectLink = $_SERVER["REQUEST_URI"];
}
if(!function_exists("handbid_app_links")){
    function handbid_app_links(){
        ?>
        <!-- <h4>You can download the Handbid App for Android or iPhone.</h4>-->
        <ul class="app-links">
            <li class="app-store">
                <a target="_blank" href="<?php echo add_query_arg(["referrer" => urlencode(HANDBID_APP_REFERRER)], HANDBID_APP_APPSTORE );?>">
                    Download from App Store
                </a>
            </li>
            <li class="google-play">
                <a target="_blank"  href="<?php echo add_query_arg(["referrer" => urlencode(HANDBID_APP_REFERRER)], HANDBID_APP_GOOGLEPLAY );?>">
                    Download from Google Play
                </a>
            </li>
        </ul>
    <?php
    }
}
if(!function_exists("get_login_popup_header")){
    function get_login_popup_header($text){
        ?>
        <div class="row login-modal-head">
            <span class="login-modal-head-logo"></span>
            <h4 class="login-modal-head-title"><?php echo $text;?></h4>
        </div>
    <?php
    }
}
if(!function_exists("handbid_popup_inline_links")){
    function handbid_popup_inline_links($type){
        $isForgot = ($type == "forgot");
        $isLogin = ($type == "login");
        $isRegister = ($type == "register");
        if($isForgot or $isLogin or $isRegister) {
            ?>
            <div class="row links-to-other-tabs">
                <?php if(!$isRegister){?>
                <div class="col-xs-12 col-sm-6 single-link-to-other-tabs">
                    <a class="login-popup-link" data-target-tab="register-form">Sign Up</a>
                </div>
                <?php }?>
                <?php if(!$isLogin){?>
                <div class="col-xs-12 col-sm-6 single-link-to-other-tabs">
                    <a class="login-popup-link" data-target-tab="login-form">Sign In</a>
                </div>
                <?php }?>
                <?php if(!$isForgot){?>
                <div class="col-xs-12 col-sm-6 single-link-to-other-tabs">
                    <a class="login-popup-link" data-target-tab="forgot-pass">Forgot My Password</a>
                </div>
                <?php }?>
            </div>
        <?php
        }
    }
}
?>


<div class="handbid-modal modal fade handbid-login-modal <?php echo ($in_page) ? "handbid-modal-in-page" : "" ; ?>" tabindex="-1" role="dialog" data-handbid-modal-key="login-modal">
    <div class="modal-dialog modal-lg">
        <?php if(!$in_page){?>
            <a href="#" class="modal-close" data-dismiss="modal" aria-label="Close">&times;</a>
        <?php }?>

        <div class="container-fluid container-tab active-container" data-tab-name="login-form">
            <?php get_login_popup_header("Sign in to Handbid");?>
            <div class="handbid-form row">
                <div class="row no-margin" style="display: none">
                    <div class="col-sm-8 col-sm-offset-2 col-xs-12">
                        <h3>Handbid Bidder Login</h3>
                        <?php if($is_logged_in){?>
                            <h4>You are already logged in</h4>
                            <h4><a class="login-popup-link" href="/auctions/">Click here</a> to choose your auction!</h4>
                        <?php }else{ ?>
                            <h4>Not sure if you have an account?
                                <a class="login-popup-link" data-target-tab="register-form">Click here</a> to get
                                started.</h4>
                        <?php }?>
                    </div>
                </div>

                <form id="hb-login-form" class="form" method="POST" action="<?php echo get_admin_url() . 'admin-post.php'; ?>"
                      enctype="multipart/form-data">

                    <div class="col-md-10 col-md-offset-1 col-xs-12 handbid-form-area">
                        <div class="row isCurrentlyLoggingIn to-hide-block" style="display: none;">
                            <h3 class="col-xs-12 ">
                                Logging in. Please wait.
                            </h3>
                        </div><div class="row errorsRow to-hide-block" style="display: none;">
                            <div class="col-md-10 col-md-offset-1 col-xs-12 errorsContainer">
                                Specified combination not found.
                            </div>
                        </div>
                        <?php if(!$is_logged_in){?>
                            <div class="row">
                                <div class="form-group col-md-6 col-md-offset-3 col-xs-12">
                                    <input placeholder="Email*" type="email" name="username" value=""
                                           class="form-control cleanable-input" id="hb-login-form-username">
                                </div>
                            </div>


                            <div class="row">
                                <div class="form-group col-md-6 col-md-offset-3 col-xs-12">
                                    <input placeholder="Password or Pin*" type="password" name="pin" value=""
                                           class="form-control cleanable-input"  id="hb-login-form-password">

                                </div>
                            </div>
                        <?php }?>

                        <div class="row">
                            <div class="form-group col-md-10 col-md-offset-1 col-xs-12 buttons">
                                <?php if($is_logged_in){?>
                                    <a class="btn handbid-logout-link" href="/handbid-logout/">Logout</a>
                                <?php }else{ ?>

                                    <input type="hidden" id="login-add-to-auction" value="<?php echo (isset($auction->auctionGuid))?trim($auction->auctionGuid):"";?>">
                                    <button type="submit" class="btn signup" id="hb-login-form-submit"><span>Sign In</span></button>
                                <?php }?>
                            </div>
                        </div>
                    </div>

                    <?php if(!$is_logged_in) handbid_popup_inline_links("login");?>

                    <div class="row">
                        <div class="col-md-10 col-md-offset-1 col-xs-12 modal-footer">
                            <?php handbid_app_links();?>
                        </div>
                    </div>

                    <input type='hidden' name='redirect' value='<?php echo $redirectLink; ?>' id="hb-login-form-redirect"/>
                    <input type='hidden' name='form-id' value='handbid-login'/>
                    <input type='hidden' name='nonce' value='<?php echo apply_filters("handbid_create_nonce", date("d.m.Y") . "login");?>' id="hb-login-form-nonce"/>
                    <input type='hidden' name='action' value='handbid_ajax_login' id="hb-login-form-action"/>
                </form>
            </div>
        </div>

        <div class="container-fluid container-tab" style="display: none" data-tab-name="forgot-pass">
            <?php get_login_popup_header("Forgot Password?");?>
            <div class="handbid-form row">

                <form class="form" method="POST" action="<?php echo get_admin_url() . 'admin-post.php'; ?>"
                      enctype="multipart/form-data">
                    <div class="col-md-10 col-md-offset-1 col-xs-12 center-aligned-text handbid-form-area">
                        <div class="row errorsRow to-hide-block" style="display: none;">
                            <div class="col-md-10 col-md-offset-1 col-xs-12 errorsContainer">
                                User with specified email was not found.
                            </div>
                        </div>


                        <h5>Enter your email and we will send you instructions on how to get
                            logged in.</h5>

                        <div class="row">
                            <div class="form-group col-md-6 col-md-offset-3 col-xs-12">
                                <input placeholder="Email" type="text" id="emailOrPhoneToResetPass"
                                       name="username" value=""
                                       class="form-control cleanable-input">
                           </div>
                        </div>

                        <button type="submit" class="btn signup login-popup-link reset-password-link loading-span-button"
                                data-change-pass-nonce="<?php echo apply_filters("handbid_create_nonce", date("d.m.Y") . "reset_pass");?>"
                            ><span>Send Instructions</span></button>
                    </div>

                    <?php handbid_popup_inline_links("forgot");?>

                    <div class="row">
                        <div class="col-md-10 col-md-offset-1 col-xs-12 modal-footer">
                            <?php handbid_app_links();?>
                        </div>
                    </div>

                </form>

            </div>
        </div>

        <div class="container-fluid container-tab" style="display: none" data-tab-name="forgot-pass-sent">
            <?php get_login_popup_header("Login Info has been Sent");?>

            <div class="handbid-form row">
                <div class="row">
                    <div class="form-group col-md-10 col-md-offset-1 col-xs-12">
                        <h3 class="center-aligned-text">Check your email for the information.</h3>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-10 col-md-offset-1 col-xs-12 modal-footer">
                        <a class="btn signup login-popup-link" data-target-tab="login-form">Start Over</a>
                        <?php handbid_app_links();?>
                    </div>
                </div>
            </div>
        </div>

        <?php if(defined("HANDBID_SHOW_TUTORIAL") and HANDBID_SHOW_TUTORIAL){?>
            <div class="container-fluid container-tab" style="display: none" data-tab-name="get-started">
                <div class="handbid-form row">
                    <h3>GETTING STARTED</h3>
                    <h4 class="sub-title">with <span>Handbid</span></h4>

                    <form class="form" method="POST" action="<?php echo get_admin_url() . 'admin-post.php'; ?>"
                          enctype="multipart/form-data">

                        <div class="row">
                            <div class="form-group col-xs-12">
                                <h5 class="center-aligned-text">Handbid lets you bid from anywhere using any or all
                                    following devices.</h5>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-lg-4 center-aligned-text">
                                <h2 class="center-aligned-text">Your Phone</h2>
                                <img class="img-circle"
                                     src="<?php echo plugin_dir_url(__FILE__)."../../public/images/login-modal/phones.png"; ?>"
                                     alt="Generic placeholder image" width="140" height="140">


                                <h4>Using the Handbid App for Android or Iphone. Are you a Windows Phone or Blackberry user? Just navigate to
                                    handbid.com from your phone's</h4>

                            </div>
                            <div class="col-lg-4 center-aligned-text">
                                <h2 class="center-aligned-text">iPads</h2>
                                <img class="img-circle"
                                     src="<?php echo plugin_dir_url(__FILE__)."../../public/images/login-modal/ipads.png"; ?>"
                                     alt="Generic placeholder image" width="140" height="140">


                                <h4>Provided for you to use at the Auction Event</h4>
                            </div>
                            <div class="col-lg-4 center-aligned-text">
                                <h2 class="center-aligned-text">Your Computer</h2>
                                <img class="img-circle"
                                     src="<?php echo plugin_dir_url(__FILE__)."../../public/images/login-modal/comp.png"; ?>"
                                     alt="Generic placeholder image" width="140" height="140">


                                <h4>From the Handbid.com website</h4>
                            </div>
                        </div>

                        <div class="row">
                            <div class="form-group col-md-12">
                                <h5 class="center-aligned-text footer-message"><br><br>To get started, we need to know if you need
                                    to create a new account or if you were invited to sign up to an auction.
                                </h5>
                            </div>
                        </div>

                        <div class="row buttons">
                            <div class="col-lg-4 center-aligned-text">
                                <a class="btn btn-info signup login-popup-link" data-target-tab="use-invite-code">Use
                                    Invite Code</a>
                                <h4>Got an invite code from an auction host?</h4>
                            </div>
                            <div class="col-lg-4 center-aligned-text">
                                <a class="btn btn-info signup login-popup-link"
                                   data-target-tab="register-form">Register</a>
                                <h4>Need to setup an account?</h4>
                            </div>
                            <div class="col-lg-4 center-aligned-text">
                                <a class="btn btn-info signup login-popup-link" data-target-tab="login-form">Login</a>
                                <h4>Already have an account?</h4>
                            </div>
                        </div>

                        <div class="row">
                            <div class="form-group col-md-12">
                                <h5 class="center-aligned-text footer-message"><br><br>Not sure? Just click on the "Register" and
                                    we will figure it out from there.<br></h5>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-10 col-md-offset-1 col-xs-12 modal-footer">
                                <?php handbid_app_links();?>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        <?php }?>

        <div class="container-fluid container-tab invite-code-tab" style="display: none" data-tab-name="use-invite-code">
            <?php get_login_popup_header("Use Invite Code");?>
            <div class="handbid-form row">
                <div class="row">
                    <div class="form-group col-md-10 col-md-offset-1 col-xs-12">
                        <h2 class="center-aligned-text">You were invited to use Handbid!</h2>
                        <h5 class="center-aligned-text">Welcome! We are so glad you are here. Enter your invite code
                            below and lets get you setup.</h5>
                    </div>
                </div>

                <div class="row errorsRow to-hide-block" style="display: none;">
                    <div class="col-md-10 col-md-offset-1 col-xs-12 errorsContainer">
                        Cannot find auction by invite code.
                    </div>
                </div>

                <div class="row">
                    <div class="form-group col-md-10 col-md-offset-1 col-xs-12">

                        <input placeholder="Enter code" type="text" name="code" value=""
                               id="inviteShortCodeInput"
                               class="form-control cleanable-input">
                    </div>
                </div>

                <div class="row">
                    <div class="form-group col-md-10 col-md-offset-1 col-xs-12 center-aligned-text">
                        <a class="btn signup login-popup-link inviteShortCodeButton loading-span-button"
                           data-check-invite-nonce="<?php echo apply_filters("handbid_create_nonce", date("d.m.Y") . "check_invite_code");?>"
                            ><span>Find My Auction</span></a>
                    </div>
                </div>

                <div class="row">
                    <div class="form-group col-md-10 col-md-offset-1 col-xs-12">
                        <h5 class="center-aligned-text">Handbid can't find your auction? Perhaps it is not setup yet.
                            You can <a class="login-popup-link" data-target-tab="register-form">register</a> without it
                            and connect to it later.</h5>
                    </div>
                </div>

                <div class="row">
                    <div class="modal-footer col-md-10 col-md-offset-1 col-xs-12">
                        <?php handbid_app_links();?>
                    </div>
                </div>
            </div>
        </div>

        <div class="container-fluid container-tab register-tab" style="display: none" data-tab-name="register-form">
            <?php get_login_popup_header("Getting Started!");?>
            <div class="handbid-form row">
                <h4>Creating Your Bidder Account<br></h4>

                <div class="col-md-10 col-md-offset-1 col-xs-12 center-aligned-text handbid-form-area">
                    <div class="row errorsRow" style="display: none;">
                        <div class="col-xs-12 errorsContainer">

                        </div>
                    </div>

                    <div class="row">
                        <div class="form-group col-md-6 col-xs-12">
                            <input id="reg-firstname" placeholder="First Name *" type="text" name="firstname" value=""
                                   class="col-xs-12 has-question-icon has-popover cleanable-input copyable-field"
                                   data-copy-to="confirm-firstname"
                                   required
                                   data-required-message="First Name field is required">
                            <a class="has-question-icon has-popover"
                               tabindex="-1"
                               role="button"
                               data-toggle="popover"
                               data-placement="top"
                               data-trigger="focus"
                               title="Enter in Your First and Last Name"
                               data-content="We need your name so we know what to call you and for your receipt at the end. Your identity (by default) will be concealed using a Paddle Number or Alias.">
                                ?
                            </a>
                        </div>
                        <div class="form-group col-md-6 col-xs-12">
                            <input id="reg-lastname" placeholder="Last Name *" type="text" name="lastname" value=""
                                   class="col-xs-12 has-question-icon has-popover cleanable-input copyable-field"
                                   data-copy-to="confirm-lastname"
                                   required
                                   data-required-message="Last Name field is required">
                            <a class="has-question-icon has-popover"
                               tabindex="-1"
                               role="button"
                               data-toggle="popover"
                               data-placement="top"
                               data-trigger="focus"
                               title="Enter in Your First and Last Name"
                               data-content="We need your name so we know what to call you and for your receipt at the end. Your identity (by default) will be concealed using a Paddle Number or Alias.">
                                ?
                            </a>
                        </div>
                    </div>

                    <div class="row">
                        <div class="form-group col-xs-12">
                            <input id="reg-email" placeholder="eMail" type="email" name="email" value=""
                                   class="col-xs-12 has-question-icon has-popover cleanable-input copyable-field is-email"
                                   data-copy-to="confirm-email"
                                   data-not-email-message="Please, provide valid email address"
                                   required
                                   data-required-message="Email field is required">
                            <a class="has-question-icon has-popover"
                               tabindex="-1"
                               role="button"
                               data-toggle="popover"
                               data-placement="top"
                               data-trigger="focus"
                               title="Enter in Your Email Address"
                               data-content="We will use your eMail to identify you and also to send you a receipt at the end of the auction. Don't worry, you won't end up on any list because of us. You can review our privacy policy for more details.">
                                ?
                            </a>
                        </div>
                        <div class="form-group col-md-6 col-xs-12">
                            <input id="reg-password" placeholder="Password (for use only on the webSite)" type="password"
                                   name="password" value=""
                                   class="col-xs-12 has-question-icon has-popover cleanable-input copyable-field"
                                   data-copy-to="confirm-password"
                                   required
                                   data-required-message="Password field is required">
                            <a class="has-question-icon has-popover"
                               tabindex="-1"
                               role="button"
                               data-toggle="popover"
                               data-placement="top"
                               data-trigger="focus"
                               title="Create a Password"
                               data-content="You will need a password to login on from Handbid.com. You will not need to use this password to login from the mobile apps or from the iPads. Please, ceep this password secure.">
                                ?
                            </a>
                        </div>
                        <div class="form-group col-md-6 col-xs-12">
                            <input id="reg-password-confirm" placeholder="Confirm your Password" type="password"
                                   name="password-confirm" value=""
                                   class="col-xs-12 has-question-icon has-popover cleanable-input"
                                   data-mismatch-message="Password mismatch">
                            <a class="has-question-icon has-popover"
                               tabindex="-1"
                               role="button"
                               data-toggle="popover"
                               data-placement="top"
                               data-trigger="focus"
                               title="Create a Password"
                               data-content="You will need a password to login on from Handbid.com. You will not need to use this password to login from the mobile apps or from the iPads. Please, ceep this password secure.">
                                ?
                            </a>
                        </div>
                    </div>

                    <div class="row">
                        <div class="form-group col-md-6 col-xs-12">
                            <select id="reg-phone-code" name="phone-code"
                                    class="col-xs-12 copyable-field"  data-copy-to="confirm-phone-code">
                                <?php
                                foreach($countries as $country){
                                    echo "<option value='" . $country["code"] . "' " . selected("US", $country["code"], false) . ">" . $country["name"] . "</option>";
                                }
                                ?>
                            </select>

                        </div>
                        <div class="form-group col-md-6 col-xs-12">
                            <input id="reg-phone-number" placeholder="Cell Phone *" type="text" name="phone-number" value=""
                                   class="col-xs-12 has-question-icon has-popover cleanable-input copyable-field"
                                   data-copy-to="confirm-phone-number"
                                   required
                                   data-required-message="Phone field is required">
                            <a class="has-question-icon has-popover"
                               tabindex="-1"
                               role="button"
                               data-toggle="popover"
                               data-placement="top"
                               data-trigger="focus"
                               title="Provide Your Cell Phone"
                               data-content="If you intend to bid from your smartphone using the Handbid App, please provide number for that here and tell us what type of phone you have. We will send instructions to that phone on how to get setup.">
                                ?
                            </a>
                        </div>

                        <input type="hidden" name="phone-type" value="other" class="copyable-field" data-copy-to="confirm-phone-type">
                        <input type="hidden" class="" id="confirm-add-to-auction" name="add-to-auction" value="<?php echo (isset($auction->auctionGuid))?trim($auction->auctionGuid):"";?>">
                    </div>

                    <div class="row">
                        <div class="col-md-10 col-md-offset-1 col-xs-12">
                            <label for="reg-agree-terms" class="radio-label agree-terms-label">
                                <input type="checkbox" id="reg-agree-terms" name="agree-terms" value="agree"
                                       required
                                       data-required-message="You must agree to the bidder terms and conditions">
                                I agree to the <a target="_blank" href="https://handbid.com/terms-of-service/">bidder terms and conditions</a></label>
                        </div>

                    </div>
                    <div class="row">
                        <div class="col-md-10 col-md-offset-1 col-xs-12">
                            <a class="btn btn-info signup login-popup-link register-next" data-target-tab="register-form-confirm">CONTINUE</a>
                        </div>
                    </div>
                </div>

                <?php handbid_popup_inline_links("register");?>

                <div class="row">
                    <div class="modal-footer col-md-10 col-md-offset-1 col-xs-12">
                        <?php handbid_app_links();?>
                    </div>
                </div>

            </div>
        </div>


        <div class="container-fluid container-tab" style="display: none" data-tab-name="register-form-confirm">
            <?php get_login_popup_header("Confirm Registration");?>
            <div class="handbid-form row">
                <h4>Your Handbid Account is SETUP<br>please confirm your information below</h4>
                <div class="col-md-10 col-md-offset-1 col-xs-12 handbid-form-area">
                    <div class="row errorsRow" style="display: none;">
                        <div class="col-xs-12 errorsContainer">

                        </div>
                    </div>

                    <div class="row">
                        <div class="form-group col-xs-12">
                            <input id="confirm-firstname" placeholder="First Name" type="text" name="firstname" value=""
                                   class="col-xs-12  cleanable-input"
                                   required
                                   data-required-message="First Name field is required">
                        </div>
                        <div class="form-group col-xs-12">
                            <input id="confirm-lastname" placeholder="Last Name" type="text" name="lastname" value=""
                                   class="col-xs-12 cleanable-input"
                                   required
                                   data-required-message="Last Name field is required">
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-xs-12">
                            <input id="confirm-email" placeholder="eMail" type="email" name="email" value=""
                                   class="col-xs-12 cleanable-input is-email"
                                   data-not-email-message="Please, provide valid email address" >
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-xs-12">
                            <select id="confirm-phone-code" name="phone-code"
                                    class="col-xs-4">
                                <?php
                                foreach($countries as $country){
                                    echo "<option value='" . $country["code"] . "' " . selected("US", $country["code"], false) . ">" . $country["name"] . "</option>";
                                }
                                ?>
                            </select>
                            <input id="confirm-phone-number" placeholder="Cell Phone" type="text" name="phone-number"
                                   value=""
                                   class="col-xs-8 has-question-icon has-popover cleanable-input">
                            <input type="hidden" name="phone-type" value="other">
                        </div>

                        <input type="hidden" class="" id="confirm-add-to-auction-id" name="add-to-auction-id" value="<?php echo (isset($auction->id))?trim($auction->id):"";?>">
                        <input type="hidden" class="" id="confirm-add-to-auction" name="add-to-auction" value="<?php echo (isset($auction->auctionGuid))?trim($auction->auctionGuid):"";?>">
                        <input type="hidden" class="" id="confirm-add-to-auction-slug" name="add-to-auction-slug" value="<?php echo (isset($auction->key))?trim($auction->key):"";?>">
                        <input type="hidden" class="" id="confirm-add-to-auction-name" name="add-to-auction-name" value="<?php echo (isset($auction->name))?esc_attr(trim($auction->name)):"";?>">
                    </div>

                    <input type="hidden" id="confirm-password" name="password">
                    <div class="row">
                        <div class="col-xs-12 center-aligned-text">
                            <a class="btn btn-info signup login-popup-link register-confirm" data-target-tab="register-complete"><span>COMPLETE</span></a>
                        </div>
                    </div>
                </div>

                <?php handbid_popup_inline_links("register");?>

                <div class="modal-footer">
                    <?php handbid_app_links();?>

                    <!--                    <input type='hidden' name='redirect' value='--><?php //echo $_SERVER["REQUEST_URI"] ?><!--' id="hb-reg-form-redirect"/>-->
                    <input type='hidden' name='form-id' value='handbid-register'/>
                    <input type='hidden' name='nonce' value='<?php echo apply_filters("handbid_create_nonce", date("d.m.Y") . "register");?>' id="hb-reg-form-nonce"/>
                    <input type='hidden' name='action' value='handbid_ajax_registration' id="hb-reg-form-action"/>
                </div>
            </div>
        </div>


        <div class="container-fluid container-tab" style="display: none" data-tab-name="register-complete">
            <?php get_login_popup_header("Registration Complete!");?>
            <div class="handbid-form row">

                <div class="row">
                    <div class="col-md-10 col-md-offset-1 col-xs-12">
                        <h3 class="bidder-name" id="reg-complete-name">Fred Flinstone</h3>

                        <div id="reg-complete-have-paddle-number">
                            <h4 class="paddle-number-info">your paddle number for the</h4>

                            <h3 class="auction-name" id="reg-complete-auction">Night at the Museum</h3>

                            <h1 class="paddle-number" id="reg-paddle-number">192</h1>
                            <div class="center-aligned-text">
                                <span class="what-is-paddle-number">What is a <a href="#" target="_blank">Paddle Number</a>?</span>
                            </div>
                        </div>
                    </div>
                </div>
                <div id="reg-complete-start-bidding" class="row">
                    <div class="col-xs-12 col-md-4 col-md-offset-4">
                        <a class="btn btn-info signup" id="start-bidding-button" href="/auctions/">Checkout the Auction</a>
                    </div>
                </div>
                <div id="reg-complete-add-card" class="row <?php echo ($auctionRequiresCC)? 'add-new-cc-to-register' : '';?>">
                    <h4>The auction you are registering for requires a credit card. <br>Please add one now.</h4>
                    <div class="col-xs-12 col-md-4 col-md-offset-4">
                        <a class="btn btn-info signup" id="start-enter-card-button" href="#">Add New Card</a>
                    </div>
                </div>


                <div class="row">
                    <div class="col-md-10 col-md-offset-1 modal-footer">
                        <?php handbid_app_links();?>
                    </div>
                </div>

            </div>
        </div>


        <div class="container-fluid container-tab" style="display: none" data-tab-name="purchase-tickets">
            <?php get_login_popup_header("Auction Tickets");?>
            <div class="handbid-form row">
                <div class="row no-margin" style="display: none">
                    <div class="col-sm-8 col-sm-offset-2 col-xs-12">

                    </div>
                </div>


                    <div class="col-xs-12 handbid-form-area tickets-modal tickets-on-register">
                        <?php

                        $currencyCode = 'USD';
                        $currencySymbol = '$';

                        ?>
                        <div class="row">
                            <h5 class="col-xs-12 upper-tickets-text">
                                Selected
                            </h5>
                            <h4 class="col-xs-12 upper-summary">
                                <span class="upper-tickets-count" data-handbid-tickets-quantity>0</span>
                                items for
                                <span class="handbidAuctionCurrency" title="<?php echo $currencyCode; ?>"><?php echo $currencySymbol; ?></span><span class="upper-tickets-count" data-handbid-tickets-total>0</span>
                            </h4>
                                <div class="col-xs-12 tickets-container">
                                </div>
                        </div>

                        <div class="row">
                            <div class="form-group col-md-3 col-xs-6 buttons">
                                <button type="submit" class="btn signup btn-gray" id="hb-purchase-tickets-back"><span>Back</span></button>
                            </div>
                            <div class="form-group col-md-3 col-md-offset-6 col-xs-6 buttons">
                                <button type="submit" class="btn signup" id="hb-purchase-tickets-next"><span>Purchase</span></button>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-10 col-md-offset-1 col-xs-12 modal-footer">
                            <?php handbid_app_links();?>
                        </div>
                    </div>

                    <input type='hidden' name='redirect' value='<?php echo $redirectLink; ?>' id="hb-login-form-redirect"/>
                    <input type='hidden' name='form-id' value='handbid-login'/>
                    <input type='hidden' name='nonce' value='<?php echo apply_filters("handbid_create_nonce", date("d.m.Y") . "login");?>' id="hb-login-form-nonce"/>
                    <input type='hidden' name='action' value='handbid_ajax_login' id="hb-login-form-action"/>

            </div>
        </div>
    </div>
</div>
