<?php
/**
 * @copyright Copyright (c) 2014-2015 Handbid Inc.
 * @category handbid
 * @package Handbid2-WordPress
 * @license Proprietary
 * @link http://www.handbid.com/
 * @author Master of Code (worldclass@masterofcode.com)
 */

$notifications = $this->get( 'notifications' );
$notifications = array_reverse($notifications);
?>
    <ul class="simple-list">
        <?php if ( count( $notifications ) > 0 ) {
            forEach ( $notifications as $notification ) {
                //echo "<pre style='display: none'>".print_r($notification,true)."</pre>";
                ?>
                <li class="row message-row <?php echo $notification->messageType; ?>">
                    <div class="col-md-1">
                        <span class="message-status message-status-<?php echo $notification->messageType; ?>"></span>
                    </div>
                    <div class="col-md-4 message-date"><b><?php echo date( 'F d, Y ', strtotime($notification->dateInserted) ); ?></b>
                        <span><?php echo date( 'g:ia', strtotime($notification->dateInserted) ); ?></span>
                    </div>
                    <div class="col-md-7">
                        <?php echo $notification->body; ?>
                    </div>
                </li>
            <?php
            }
        } else {
            ?>
            <p>You do not have any notifications.</p>
        <?php
        }

        ?>
    </ul>

<?php
