<?php

$notifications = $this->get( 'notifications' );

?>
    <ul class="simple-list">
        <?php if ( count( $notifications ) > 0 ) {
            forEach ( $notifications as $notification ) {

                ?>
                <li class="row preview">
                    <div class="col-md-4"><?php echo date( 'm/d/Y - g:ia', $notification->dateUpdated ); ?></div>
                    <div class="col-md-8">
                        <?php echo $notification->body; ?>
                    </div>
                </li>
            <?php
            }
        } else {
            ?>
            <p>You do not have any notifications.</p>
        <?php
        }
        ?>
    </ul>

<?php
