<?php
if (!is_null($this->get('profile'))) {
    $profile = $this->get('profile');
} else {
    echo "You must be logged in to view your profile.";
    return;
}

?>
<div class="bidder-info-container">
    <div class="bidder-image" style="background-image: url(<?php echo $profile->photo; ?>)"></div>

    <table class="bidder-info">
        <tr>
            <td><label>Name:</label></td>
            <td>
                <?php echo $profile->firstName . ' ' . $profile->lastName; ?>
            </td>
        </tr>
        <tr>
            <td><label>Pin:</label></td>
            <td>
                <?php echo $profile->pin; ?>
            </td>
        </tr>
        <tr>
            <td><label>Cellphone:</label></td>
            <td>
                <?php echo $profile->cellPhone->value; ?>
            </td>
        </tr>
        <tr>
            <td><label>Email:</label></td>
            <td>
                <?php echo $profile->email; ?>
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <?php echo do_shortcode('[handbid_bidder_profile_form]'); ?>
            </td>
        </tr>
    </table>
</div>