<?php
/**
 * @copyright Copyright (c) 2014-2015 Handbid Inc.
 * @category handbid
 * @package Handbid2-WordPress
 * @license Proprietary
 * @link http://www.handbid.com/
 * @author Master of Code (worldclass@masterofcode.com)
 */


if (!is_null($this->get('profile'))) {
    $profile = $this->get('profile');
	$auction = $this->get('auction');
        $inventory = $this->get('inventory');
    $address = $profile->shippingAddress;
    $redirect = $this->get('redirect');
    $countries = $this->get("countries");
    $countryIDs = $this->get("countryIDs");
    $bidConfirm = $this->get("bidConfirm");
} else {
    echo "You must be logged in to view your profile.";
    return;
}

$currencyCode = (isset($auction->currencyCode))? $auction->currencyCode : HANDBID_DEFAULT_CURRENCY;
$currencySymbol = (isset($auction->currencySymbol))? $auction->currencySymbol : HANDBID_DEFAULT_CURRENCY_SYMBOL;
?>

<form class="edit-profile" action="<?php echo get_admin_url() . 'admin-post.php'; ?>" method="post" enctype="multipart/form-data">
    <input type="hidden" id="payInvoiceID" name="payInvoiceID" value="">
    <ul class="simple-list">
        <li class="row">
            <div class="col-md-12">
                <input type="text" name="alias" value="<?php echo $profile->alias; ?>" id="profileAlias" placeholder="Alias" title="Alias"/>
                <input type="hidden" value="<?php echo $profile->alias; ?>" id="profileAliasOld"/>
            </div>
        </li>
        <li class="row">
            <div class="col-md-12">
                <input type="text" name="firstName" value="<?php echo $profile->firstName; ?>" id="profileFirstName" placeholder="First Name" title="First Name"/>
                <input type="hidden" value="<?php echo $profile->firstName; ?>" id="profileFirstNameOld"/>
            </div>
        </li>
        <li class="row">
            <div class="col-md-12">
                <input type="text" name="lastName" value="<?php echo $profile->lastName; ?>" id="profileLastName" placeholder="Last Name" title="Last Name"/>
                <input type="hidden" value="<?php echo $profile->lastName; ?>" id="profileLastNameOld"/>
            </div>
        </li>
        <li class="row">
            <div class="col-md-12">
                <span title="Email" style="text-transform: uppercase;"><?php echo $profile->email; ?></span>
<!--                <input type="email" name="email" value="--><?php //echo $profile->email; ?><!--" id="profileEmail" placeholder="Email" title="Email"/>-->
                <input type="hidden" value="<?php echo $profile->email; ?>" id="profileEmail"/>
                <input type="hidden" value="<?php echo $profile->email; ?>" id="profileEmailOld"/>
            </div>
        </li>
	    <?php if(!empty($inventory->spendingLimit)){ // NOT EMPTY does the work of ISSET and > 0 ?>
	    <li class="row">
		    <div class="col-md-12">
			    <span title="Spending Limit: <?php echo $currencySymbol . $inventory->spendingLimit; ?>" style="text-transform: uppercase;">Spending Limit: <?php echo $currencySymbol . $inventory->spendingLimit; ?></span>
		    </div>
	    </li>
	    <?php }?>
        <li class="row">
            <div class="col-md-4">
                        <select id="userAddressCountryId" name="userAddressCountryId"
                                title="Country"
                                data-provinces-nonce="<?php echo apply_filters("handbid_create_nonce", date("d.m.Y") . "country_provinces");?>"
                                class="col-md-12">
                            <?php
                            $provinces = [];
                            $curID = 0;
                            foreach($countryIDs as $country){
                                $selected = trim($profile->userAddressCountryId) ? selected($profile->userAddressCountryId, $country->id, false) : selected("US", $country->countryCode, false);
                                $provincesTemp = trim($profile->userAddressCountryId) ? ($profile->userAddressCountryId == $country->id ? $country->provinces : []) : ("US" == $country->countryCode ? $country->provinces : []);
                                $curIDTemp = trim($profile->userAddressCountryId) ? ($profile->userAddressCountryId == $country->id ? $country->id : 0) : ("US" == $country->countryCode ? $country->id : 0);
                                $provinces = (count($provincesTemp))? $provincesTemp : $provinces;
                                $curID = ($curIDTemp == -1)? $curID : $curIDTemp;
                                echo "<option value='" . $country->id . "' " . $selected . ">" . $country->name . "</option>";
                            }
                            ?>
                        </select>
            </div>
            <div class="col-md-8">
                <input type="tel" name="userCellPhone" value="<?php echo $profile->userCellPhone; ?>" id="profileCellPhone" placeholder="Cell Phone" title="Cell Phone"/>
                <input type="hidden" value="<?php echo $profile->userCellPhone; ?>" id="profileCellPhoneOld"/>
            </div>
        </li>
        <li class="row provincesRow" style="<?php echo (count($provinces))?"":"display:none";?>">
            <div class="col-md-12">
                        <select id="userAddressProvinceId" name="userAddressProvinceId"
                                title="Province"
                                class="col-md-12">
                            <?php

                            foreach($provinces as $province){
                                $selected = selected($profile->userAddressProvinceId, $province->id, false);
                                echo "<option value='" . $province->id . "' " . $selected . ">" . $province->countriesRegionsName . "</option>";
                            }
                            ?>
                        </select>
                <input type="hidden" id="provincesCountByCountry"
                       data-current-country="<?php echo $curID; ?>"
                    <?php
                    foreach($countryIDs as $country){
                        if(isset($country->provinces) and count($country->provinces)){
                            echo " data-provinces-".$country->id."='".count($country->provinces)."' ";
                        }
                    }
                    ?>
                    >
            </div>
        </li>
        <li class="row">
            <div class="col-md-12">
                <label>Upload Photo</label>
                <input type="file" name="profile_photo"/>
            </div>
        </li>
        <li class="row">
            <div class="col-md-12">
                <input type="password" name="password" placeholder="Password" title="Password" id="profileNewPassword"/>
            </div>
        </li>
        <li class="row">
            <div class="col-md-12">
                <input type="password" name="password2" placeholder="Confirm Password" title="Confirm Password" id="profileNewPasswordConfirm"/>
            </div>
        </li>
        <li class="row">
            <div class="col-md-8">
                <input type="text" name="shippingAddress" value="<?php echo $profile->shippingAddress; ?>" id="profileShippingAddress" placeholder="Shipping Address" title="Shipping Address"/>
                <input type="hidden" value="<?php echo $profile->shippingAddress; ?>" id="profileShippingAddressOld"/>
            </div>
            <div class="col-md-4">
                <input class="button btn-small green-solid-button" value="Toggle Map" id="update_profile_location_map" onclick="handbidMain.toggleProfileLocationMap();"/>
            </div>
        </li>
        <li id="profile-location-map-container" class="row" style="display:none;">
            <div id="profile-location-map" style="width: 100%; height: 300px;"></div>
        </li>
        <li class="row">
            <div class="col-md-12">
                <input type="text" name="userAddressStreet1" value="<?php echo $profile->userAddressStreet1; ?>" id="profileStreet1" placeholder="Street" title="Street"/>
                <input type="hidden" value="<?php echo $profile->userAddressStreet1; ?>" id="profileStreet1Old"/>
            </div>
        </li>
        <li class="row">
            <div class="col-md-12">
                <input type="text" name="userAddressStreet2" value="<?php echo $profile->userAddressStreet2; ?>" id="profileStreet2" placeholder="Street 2" title="Street 2"/>
                <input type="hidden" value="<?php echo $profile->userAddressStreet2; ?>" id="profileStreet2Old"/>
            </div>
        </li>
        <li class="row">
            <div class="col-md-12">
                <input type="text" name="userAddressCity" value="<?php echo $profile->userAddressCity; ?>" id="profileCity" placeholder="City" title="City"/>
                <input type="hidden" value="<?php echo $profile->userAddressCity; ?>" id="profileCityOld"/>
            </div>
        </li>
        <li class="row">
            <div class="col-md-12">
                <input type="text" name="userAddressPostalCode" value="<?php echo $profile->userAddressPostalCode; ?>" id="profilePostalCode" placeholder="Postal Code" title="Postal Code"/>
                <input type="hidden" value="<?php echo $profile->userAddressPostalCode; ?>" id="profilePostalCodeOld"/>
            </div>
        </li>
<!--        <li class="row">-->
<!--            <div class="col-md-12">-->
<!--                <input type="text" name="province" value="--><?php //echo $profile->province; ?><!--" id="profileProvince" placeholder="Province" title="Province"/>-->
<!--                <input type="hidden" value="--><?php //echo $profile->province; ?><!--" id="profileProvinceOld"/>-->
<!--            </div>-->
<!--        </li>-->

<!--        <li class="row">-->
<!--            <div class="col-md-12">-->
<!--                <input type="text" name="countryCode" value="--><?php //echo isset($profile->countryCode) ? $profile->countryCode : 'US'; ?><!--" id="profileCountry" placeholder="Country" title="Country"/>-->
<!--                <input type="hidden" value="--><?php //echo $profile->countryCode; ?><!--" id="profileCountryOld"/>-->
<!--            </div>-->
<!--        </li>-->

	    <li class="row">
		    <div class="col-md-5">
			    <span style="text-transform: uppercase; padding: 6px 0px; display: block;">Bid confirmations Enabled: </span>
		    </div>
		    <div class="col-md-7">
			    <select id="bidConfirmationsEnabled" name="bidConfirmationsEnabled"
			            title="Bid Confirmations"
			            class="col-md-12">
				    <option value="yes" <?php selected($bidConfirm, true);?>><?php _e("Yes"); ?></option>
				    <option value="no" <?php selected($bidConfirm, false);?>><?php _e("No"); ?></option>
			    </select>
		    </div>
	    </li>
    </ul>
    <div class="row">
        <div class="col-md-12">
            <input class="button green-solid-button"  type="submit" value="submit" id="updateUserProfile"/>
            <input type='hidden' name='action' value='handbid_post_update_bidder' />
            <?php echo ($redirect) ? '<input type=\'hidden\' name=\'redirect\' value=\'' . $redirect . '\'/>' : null; ?>
        </div>
    </div>
</form>
