<?php
/**
 * @copyright Copyright (c) 2014-2015 Handbid Inc.
 * @category handbid
 * @package Handbid2-WordPress
 * @license Proprietary
 * @link http://www.handbid.com/
 * @author Master of Code (worldclass@masterofcode.com)
 */


if (!is_null($this->get('profile'))) {
    $profile = $this->get('profile');
	$auction = $this->get('auction');
    $inventory = $this->get('inventory');
    $address = $profile->shippingAddress;
    $redirect = $this->get('redirect');
    $countries = $this->get("countries");
    $countryIDs = $this->get("countryIDs");
    $bidConfirm = $this->get("bidConfirm");
} else {
    echo "You must be logged in to view your profile.";
    return;
}

$currencyCode = (isset($auction->currencyCode))? $auction->currencyCode : HANDBID_DEFAULT_CURRENCY;
$currencySymbol = (isset($auction->currencySymbol))? $auction->currencySymbol : HANDBID_DEFAULT_CURRENCY_SYMBOL;
?>

<form class="edit-profile" action="<?php echo get_admin_url() . 'admin-post.php'; ?>" method="post" enctype="multipart/form-data">
    <input type="hidden" id="payInvoiceID" name="payInvoiceID" value="">
    <ul class="simple-list">
        <li class="row">
            <div class="col-md-12">
                <input type="text" name="alias" data-profile-form-field value="<?php echo $profile->alias; ?>" id="profileAlias" placeholder="Alias" title="Alias"/>
                <input type="hidden" value="<?php echo $profile->alias; ?>" id="profileAliasOld"/>
            </div>
        </li>
        <li class="row">
            <div class="col-md-6">
                <input type="text" name="firstName" data-profile-form-field value="<?php echo $profile->firstName; ?>" id="profileFirstName" placeholder="First Name" title="First Name"/>
                <input type="hidden" value="<?php echo $profile->firstName; ?>" id="profileFirstNameOld"/>
            </div>
            <div class="col-md-6">
                <input type="text" name="lastName" data-profile-form-field value="<?php echo $profile->lastName; ?>" id="profileLastName" placeholder="Last Name" title="Last Name"/>
                <input type="hidden" value="<?php echo $profile->lastName; ?>" id="profileLastNameOld"/>
            </div>
        </li>
        <li class="row">
            <div class="col-md-12">
                <span title="Email" style="text-transform: uppercase;"><?php echo $profile->email; ?></span>
                <input type="hidden" value="<?php echo $profile->email; ?>" id="profileEmail"/>
                <input type="hidden" value="<?php echo $profile->email; ?>" id="profileEmailOld"/>
            </div>
        </li>
	    <?php if(!empty($inventory->spendingLimit)){ ?>
	    <li class="row">
		    <div class="col-md-12">
			    <span title="Spending Limit: <?php echo $currencySymbol . $inventory->spendingLimit; ?>" style="text-transform: uppercase;">Spending Limit: <?php echo $currencySymbol . $inventory->spendingLimit; ?></span>
		    </div>
	    </li>
	    <?php }?>
        <li class="row">
            <div class="col-md-4">
                        <select id="userAddressCountryId" name="userAddressCountryId"
                                data-profile-form-field
                                title="Country"
                                data-provinces-nonce="<?php echo apply_filters("handbid_create_nonce", date("d.m.Y") . "country_provinces");?>"
                                class="col-md-12">
                            <?php
                            $curID = 0;
                            foreach($countryIDs as $country){
                                $selected = trim($profile->userAddressCountryId) ? selected($profile->userAddressCountryId, $country->id, false) : selected("US", $country->countryCode, false);
                                $curIDTemp = trim($profile->userAddressCountryId) ? ($profile->userAddressCountryId == $country->id ? $country->id : 0) : ("US" == $country->countryCode ? $country->id : 0);
                                $curID = ($curIDTemp == -1)? $curID : $curIDTemp;
                                echo "<option value='" . $country->id . "' " . $selected . ">" . $country->name . "</option>";
                            }
                            ?>
                        </select>
                <input type="hidden" value="<?php echo $profile->userAddressCountryId; ?>" id="userAddressCountryIdOld"/>
            </div>
            <div class="col-md-8">
                <input type="tel" name="userCellPhone" data-profile-form-field value="<?php echo $profile->userCellPhone; ?>" id="profileCellPhone" placeholder="Cell Phone" title="Cell Phone"/>
                <input type="hidden" value="<?php echo $profile->userCellPhone; ?>" id="profileCellPhoneOld"/>
            </div>
        </li>
        <li class="row">
            <div class="col-md-6">
                <input type="password" name="password" data-profile-form-password placeholder="Password" title="Password" id="profileNewPassword"/>
            </div>
            <div class="col-md-6">
                <input type="password" name="password2" data-profile-form-password-confirm placeholder="Confirm Password" title="Confirm Password" id="profileNewPasswordConfirm"/>
            </div>
        </li>
        <li class="row">
            <div class="col-md-12">
                <input type="text" name="shippingAddress" data-profile-form-field value="<?php echo $profile->shippingAddress; ?>"
                       id="profileShippingAddress" onfocus="handbid_main.initGoogleAutocomplete('profileShippingAddress')"
                       placeholder="Shipping Address" title="Shipping Address"/>
                <input type="hidden" value="<?php echo $profile->shippingAddress; ?>" id="profileShippingAddressOld"/>
            </div>
        </li>

	    <li class="row">
		    <div class="col-md-5">
			    <span style="text-transform: uppercase; padding: 6px 0px; display: block;">Bid confirmations Enabled: </span>
		    </div>
		    <div class="col-md-7">
			    <select id="bidConfirmationsEnabled" name="bidConfirmationsEnabled"
			            title="Bid Confirmations"
			            class="col-md-12">
				    <option value="yes" <?php selected($bidConfirm, true);?>><?php _e("Yes"); ?></option>
				    <option value="no" <?php selected($bidConfirm, false);?>><?php _e("No"); ?></option>
			    </select>
		    </div>
	    </li>
    </ul>
    <div class="row">
        <div class="col-md-12">
            <button class="button green-solid-button loading-span-button"  type="submit" value="submit" id="updateUserProfile">
                <span>Submit</span>
            </button>
            <input type='hidden' name='action' value='handbid_post_update_bidder' />
            <?php echo ($redirect) ? '<input type=\'hidden\' name=\'redirect\' value=\'' . $redirect . '\'/>' : null; ?>
        </div>
    </div>
</form>
