<?php
if (!is_null($this->get('profile'))) {
    $profile = $this->get('profile');
} else {
    echo "You must be logged in to view your profile.";
    return;
}

?>

<table class="bidder-table">
    <thead>
    <tr>
        <th></th>
        <th>Name</th>
        <th>Cell Phone</th>
        <th>Email</th>
        <th></th>
    </tr>
    </thead>
    <tr>
        <td>
            <img src="<?php echo $profile->photo; ?>"/>
        </td>
        <td>
            <?php echo $profile->firstName . ' ' . $profile->lastName; ?>
        </td>
        <td>
            <?php echo $profile->cellPhone->value; ?>
        </td>
        <td>
            <?php echo $profile->email; ?>
        </td>
        <td>
            <?php echo do_shortcode('[handbid_bidder_profile_form]'); ?>
        </td>
    </tr>
</table>