<?php
if (!is_null($this->get('profile'))) {
    $profile = $this->get('profile');
    $address = $profile->shippingAddress;
    $redirect = $this->get('redirect');
} else {
    echo "You must be logged in to view your profile.";
    return;
}

?>

<form class="edit-profile" action="<?php echo get_admin_url() . 'admin-post.php'; ?>" method="post" enctype="multipart/form-data">
    <ul class="simple-list">
        <li class="row">
            <div class="col-md-12">
                <input type="text" name="firstName" value="<?php echo $profile->firstName; ?>" placeholder="First Name"/>
            </div>
        </li>
        <li class="row">
            <div class="col-md-12">
                <input type="text" name="lastName" value="<?php echo $profile->lastName; ?>" placeholder="Last Name"/>
            </div>
        </li>
        <li class="row">
            <div class="col-md-12">
                <input type="email" name="email" value="<?php echo $profile->email; ?>" placeholder="Email"/>
            </div>
        </li>
        <li class="row">
            <div class="col-md-12">
                <input type="tel" name="cellPhone[value]" value="<?php echo $profile->cellPhone->value; ?>" placeholder="Cell Phone"/>
            </div>
        </li>
        <li class="row">
            <div class="col-md-12">
                <label>Upload Photo</label>
                <input type="file" name="photo"/>
            </div>
        </li>
        <li class="row">
            <div class="col-md-12">
                <input type="password" name="password" placeholder="Password"/>
            </div>
        </li>
        <li class="row">
            <div class="col-md-12">
                <input type="password" name="password2" placeholder="Confirm Password"/>
            </div>
        </li>
        <li class="row">
            <div class="col-md-12">
                <input type="text" name="shippingAddress[street1]" value="<?php echo $address->street1; ?>" placeholder="Street"/>
            </div>
        </li>
        <li class="row">
            <div class="col-md-12">
                <input type="text" name="shippingAddress[street2]" value="<?php echo $address->street2; ?>" placeholder="Street 2"/>
            </div>
        </li>
        <li class="row">
            <div class="col-md-12">
                <input type="text" name="shippingAddress[city]" value="<?php echo $address->city; ?>" placeholder="City"/>
            </div>
        </li>
        <li class="row">
            <div class="col-md-12">
                <input type="text" name="shippingAddress[province]" value="<?php echo $address->province; ?>" placeholder="Province"/>
            </div>
        </li>
        <li class="row">
            <div class="col-md-12">
                <input type="text" name="shippingAddress[postalCode]" value="<?php echo $address->postalCode; ?>" placeholder="Postal Code"/>
            </div>
        </li>
        <li class="row">
            <div class="col-md-12">
                <input type="text" name="shippingAddress[country]" value="<?php echo isset($address->country) ? $address->country : 'US'; ?>" placeholder="Country"/>
            </div>
        </li>
    </ul>
    <div class="row">
        <div class="col-md-12">
            <input class="button green-solid-button" type="submit" value="submit"/>
            <input type='hidden' name='form-id' value='handbid-update-bidder' />
            <input type='hidden' name='action' value='submit-form' />
            <?php echo ($redirect) ? '<input type=\'hidden\' name=\'redirect\' value=\'' . $redirect . '\'/>' : null; ?>
        </div>
    </div>
</form>