<?php
/**
 * @copyright Copyright (c) 2014-2015 Handbid Inc.
 * @category handbid
 * @package Handbid2-WordPress
 * @license Proprietary
 * @link http://www.handbid.com/
 * @author Master of Code (worldclass@masterofcode.com)
 */

global $displayBidderProfile;
if(!$this->get('profile'))
    return;

$auction = $this->get('auction');
$profile = $this->get('profile');
$bidConfirm = $this->get("bidConfirm");
$auctionID = (isset($auction->id))?$auction->id:"";
$profileDashboardOn = get_option('handbidDisplayProfileDashboardOn', array("other", "auction", "auction-item"));
$pageNameForProfile = get_query_var('name');
$pageNameForProfile = (in_array($pageNameForProfile, array("auction", "auction-item")))?$pageNameForProfile:"other";
$displayBidderProfile = in_array($pageNameForProfile, $profileDashboardOn);
$bidderLocationQuestion = (!empty($auction->bidderLocationQuestion)
    ? $auction->bidderLocationQuestion
    : (!empty($auction->bidderLocationText)
        ? $auction->bidderLocationText
        : ''));
$welcomeForReceipt = (!empty($auction->welcomeForReceipt)) ? str_replace(['{auction}'], [$auction->name], $auction->welcomeForReceipt) : '';
?>
<div class="sticky">
    <div id="bidder-info-load" class="bidder-info-load <?php echo (!$displayBidderProfile)?"hidden-page-dashboard":"";?>"
         data-profile-paddle-number="<?php echo $auction->currentPaddleNumber; ?>"
         data-auction="<?php echo (int) $auctionID; ?>"
         data-auction-status="<?php echo $auction->status; ?>"
         data-auction-name="<?php echo esc_js($auction->name); ?>"
         data-auction-key="<?php echo $auction->key; ?>"
         data-auction-guid="<?php echo $auction->auctionGuid; ?>"
         data-auction-locatin-question="<?php echo esc_attr($bidderLocationQuestion); ?>"
         data-auction-welcome-message="<?php echo esc_attr($welcomeForReceipt); ?>"
         data-auction-image="<?php
         $image = $auction->logo->medium;
         $image = ($image) ? $image : $auction->imageUrl;
         $imageUrlPath = parse_url($image);
         $image = ($imageUrlPath["scheme"]) ? $image : "https://" . $image;
         echo $image; ?>"
         data-auction-organization-key="<?php echo $auction->organization->key; ?>"
         data-auction-organization-name="<?php echo $auction->organization->name; ?>"
         data-profile-id="<?php echo (int) $profile->id; ?>"
         data-load="<?php echo wp_create_nonce("bidder-".date("Y.m.d"));?>"
         data-paddle-nonce="<?php echo apply_filters("handbid_create_nonce", date("d.m.Y") . "add_paddle");?>">

        <?php
        if($displayBidderProfile) {
            echo do_shortcode( "[handbid_bidder_profile_bar  auction='" . $auctionID . "' isinitialloading='1']" );
    }
    ?>

    </div>
</div>
