<?php
/**
 * @copyright Copyright (c) 2014-2015 Handbid Inc.
 * @category handbid
 * @package Handbid2-WordPress
 * @license Proprietary
 * @link http://www.handbid.com/
 * @author Master of Code (worldclass@masterofcode.com)
 */


if (!is_null($this->get('profile'))) {
    $auction    = $this->get('auction');
    $profile    = $this->get('profile');
    $losing     = $this->get('losing');
    $winning    = $this->get('winning');
    $purchases  = $this->get('purchases');
    $maxBids    = $this->get('maxBids');
    $total      = $this->get('totalSpent');
    $myAuctions = $this->get('myAuctions');
    $myInvoices = $this->get('myInvoices');
    $myMessages = $this->get('notifications');
    $isInitialLoading = 0; //$this->get('isInitialLoading');
    $bidderName = strtoupper($profile->firstName[0]) . '. ' . $profile->lastName;
    $redirect   = $_SERVER['REQUEST_URI'];
    $bidderPage = is_page('bidder');
    $currencyCode = (isset($auction->currencyCode))? $auction->currencyCode : HANDBID_DEFAULT_CURRENCY;
    $currencySymbol = (isset($auction->currencySymbol))? $auction->currencySymbol : HANDBID_DEFAULT_CURRENCY_SYMBOL;
} else {
    return;
}
?>
<div class="bidder-info-container" data-dashboard-profile-id="<?php echo $profile->id; ?>">
    <div class="container container-fluid underlined">
        <div class="row meta">
            <div class="pin col-md-6 col-xs-6">
                <label>Pin Code:</label>
                <?php echo $profile->pin; ?>
            </div>
            <div class="auction col-md-4 col-xs-4">
                <?php
                if($auction) {
                    echo $auction->name;
                } ?>
            </div>
            <div class="paddle-number col-md-2 col-xs-2">
                <?php
                if($auction) {
                    echo "Paddle # : <span data-profile-current-paddle-number data-paddle-for-auction-".$auction->id.">".$auction->currentPaddleNumber;
                } ?>
            </div>
        </div>
        <?php $loader = ($isInitialLoading)?" initial-loading-space ":"";?>
        <div class="row slider-nav slider-nav-mobile" data-slider-nav-id="bidder-dashboard">

            <div class="col-xs-9">

                <div class="pin col-md-12 col-xs-12">
                    <label>Pin Code:</label>
                    <?php echo $profile->pin; ?>
                </div>

                <a class="col-xs-12 profile-user-info profile-opener" data-slider-nav-key="profile-user-info">
                    <span><?php echo $bidderName; ?></span>
                </a>

            </div>
            <a class="col-xs-3 total-spent">

                <span><span class="handbidAuctionCurrency" title="<?php echo $currencyCode; ?>"><?php echo $currencySymbol; ?></span> <span data-handbid-stats-grand-total><?php echo $total; ?></span></span>
                <label>Total</label>

            </a>

        </div>

        <div class="row slider-nav slider-nav-desktop stats-bar <?php echo ($bidderPage) ? 'auto-open' : ''; ?>" data-slider-nav-id="bidder-dashboard" data-toggle-mode="true">
            <a class="col-md-<?php echo ($auction) ? '2' : '3'; ?> col-xs-8 profile-user-info profile-opener" data-slider-nav-key="profile-user-info">
                <span><?php echo $bidderName; ?></span>
            </a>
            <?php if($auction) {
                ?>
                <a class="col-md-2 col-sm-3 col-xs-3 profile-max-bids <?php echo $loader;?>" data-slider-nav-key="profile-max-bids">
                    <label>Max Bids</label>
                    <span data-handbid-stats-num-proxies><?php echo ($maxBids) ? count($maxBids) : '0'; ?></span>
                </a>
                <a class="col-md-2 col-sm-3 col-xs-3 profile-winning <?php echo $loader;?>" data-slider-nav-key="profile-winning">
                    <label>Winning</label>
                    <span data-handbid-stats-num-winning><?php echo ($winning) ? count($winning) : '0'; ?></span>
                </a>
                <a class="col-md-2 col-sm-3 col-xs-3 profile-losing <?php echo $loader;?>" data-slider-nav-key="profile-losing">
                    <label>Losing</label>
                    <span data-handbid-stats-num-losing><?php echo ($losing) ? count($losing) : '0'; ?></span>
                </a>
                <a class="col-md-2 col-sm-3 col-xs-3 profile-purchases <?php echo $loader;?>" data-slider-nav-key="profile-purchases">
                    <label>Purchases</label>
                    <span data-handbid-stats-num-purchases><?php echo ($purchases) ? count($purchases) : '0'; ?></span>
                </a>
                <a class="col-md-2 col-xs-12 total-spent <?php echo $loader;?>">
                    <label>Total</label>
                    <span><span class="handbidAuctionCurrency" title="<?php echo $currencyCode; ?>"><?php echo $currencySymbol; ?></span><span data-handbid-stats-grand-total><?php echo $total; ?></span></span>
                </a>
            <?php } ?>
        </div>
    </div>
    <div class="full-width-container bidder-info-body">
        <div class="container container-fluid">
            <div class="slider-content" data-slider-nav-id="bidder-dashboard">

                <div class="row" data-slider-nav-key="profile-user-info">

                    <?php echo $this->partial('user-info.phtml', [
                        'profile'    => $profile,
                        'auction'    => $auction,
                        'winning'    => $winning,
                        'losing'     => $losing,
                        'redirect'   => $redirect,
                        'myAuctions' => $myAuctions,
                        'myInvoices' => $myInvoices,
                        'notifications' => $myMessages,
                    ]);
                    ?>
                </div>

                <div class="row" data-slider-nav-key="profile-max-bids">
                    <div class="col-md-12 simple-list-container">
                        <ul class="simple-list handbid-list-of-bids-proxy" data-no-items-text="You have not set any max bids on items.">
                            <?php
                            if(count($maxBids) > 0) {
                                forEach($maxBids as $bid) {
                                    ?>
                                    <li class="row bid-row-id-<?php echo $bid->id; ?>"
                                        data-maxbid-item-id="<?php echo $bid->item->id; ?>"
                                        data-proxy-item-id="<?php echo $bid->item->id; ?>"
                                        data-proxy-item-max-value="<?php echo (int) $bid->maxAmount; ?>"
                                        >
                                        <div class="col-md-8 col-xs-8">
                                            <a href="/auctions/<?php echo $auction->key; ?>/item/<?php echo $bid->item->key; ?>"><h4><?php echo $bid->item->name; ?></h4></a>
                                        </div>
                                        <div class="col-md-2 col-xs-2">
                                            <span class="bid-amount winning"><span class="handbidAuctionCurrency" title="<?php echo $currencyCode; ?>"><?php echo $currencySymbol; ?></span><span><?php echo (int) $bid->maxAmount; ?></span></span>
                                        </div>
                                        <div class="col-md-2 col-xs-2">
                                            <a class="button pink-solid-button loading-span-button" href="#" data-handbid-delete-proxy="<?php echo $bid->id; ?>" data-item-id="<?php echo $bid->item->id; ?>"><em>Delete</em></a>
                                        </div>
                                    </li>
                                <?php
                                }
                            } else {
                                ?>
                                <p>You have not set any max bids on items.</p>
                            <?php
                            }
                            ?>
                        </ul>
                    </div>
                </div>

                <div class="row" data-slider-nav-key="profile-winning">
                    <div class="col-md-12 simple-list-container">
                        <ul class="simple-list handbid-list-of-bids-winning" data-no-items-text="You are currently not winning any items.">
                            <?php
                            if(count($winning) > 0 ) {
                                forEach($winning as $bid) {
                                    ?>
                                    <li
                                        data-dashboard-price="<?php echo (int) $bid->amount; ?>"
                                        data-winning-item-id="<?php echo $bid->item->id; ?>">
                                        <h4 class="bid-name">
                                            <a href="/auctions/<?php echo $auction->key; ?>/item/<?php echo $bid->item->key; ?>"><?php echo $bid->item->name; ?></a>
                                        </h4>
                                        <span class="bid-amount winning"><span class="handbidAuctionCurrency" title="<?php echo $currencyCode; ?>"><?php echo $currencySymbol; ?></span><?php echo (int) $bid->amount; ?></span>
                                    </li>
                                <?php
                                }
                            } else {
                                ?>
                                <p>You are currently not winning any items.</p>
                            <?php
                            }
                            ?>
                        </ul>

                    </div>
                </div>

                <div class="row" data-slider-nav-key="profile-losing">
                    <div class="col-md-12 simple-list-container">
                        <ul class="simple-list handbid-list-of-bids-losing" data-no-items-text="You are currently not losing any items.">
                            <?php
                            if(count($losing) > 0 ) {
                                forEach($losing as $bid) {
                                    ?>
                                    <li class="row"
                                        data-losing-item-id="<?php echo $bid->item->id; ?>">
                                        <div class="col-md-8 col-xs-8">
                                            <a href="/auctions/<?php echo $auction->key; ?>/item/<?php echo $bid->item->key; ?>"><h4><?php echo $bid->item->name; ?></h4></a>
                                        </div>
                                        <div class="col-md-4 col-xs-4">
                                            <span class="bid-amount losing"><span class="handbidAuctionCurrency" title="<?php echo $currencyCode; ?>"><?php echo $currencySymbol; ?></span><span><?php echo (int) $bid->amount; ?></span></span>
                                        </div>
                                    </li>
                                <?php
                                }
                            } else {
                                ?>
                                <p>You are currently not losing any items.</p>
                            <?php
                            }
                            ?>
                        </ul>
                    </div>
                </div>

                <div class="row" data-slider-nav-key="profile-purchases">
                    <div class="col-md-12 simple-list-container">
                        <ul class="simple-list handbid-list-of-bids-purchases" data-no-items-text="You have not purchased any items.">
                            <?php
                            if(count($purchases) > 0 ) {
                                forEach($purchases as $purchase) {
                                    ?>
                                    <li class="row"
                                        data-dashboard-price="<?php echo (int) $purchase->grandTotal; ?>"
                                        data-purchased-item-id="<?php echo $purchase->item->id; ?>"
                                        data-purchased-purchase-id="<?php echo $purchase->id; ?>">
                                        <div class="col-md-4 col-xs-4">
                                            <a href="/auctions/<?php echo $auction->key; ?>/item/<?php echo $purchase->item->key; ?>"><h4><?php echo $purchase->item->name; ?></h4></a>
                                        </div>
                                        <div class="col-md-4 col-xs-4">
                                            <h4 class="quantity-total"><?php echo $purchase->quantity; ?> x <span class="handbidAuctionCurrency" title="<?php echo $currencyCode; ?>"><?php echo $currencySymbol; ?></span><?php echo $purchase->pricePerItem; ?></h4>
                                        </div>
                                        <div class="col-md-4 col-xs-4">
                                            <span class="bid-amount winning"><span class="handbidAuctionCurrency" title="<?php echo $currencyCode; ?>"><?php echo $currencySymbol; ?></span><span><?php echo $purchase->grandTotal; ?></span></span>
                                        </div>
                                    </li>
                                <?php
                                }
                            } else {
                                ?>
                                <p>You have not purchased any items.</p>
                            <?php
                            }
                            ?>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
