<?php
/**
 * @copyright Copyright (c) 2014-2015 Handbid Inc.
 * @category handbid
 * @package Handbid2-WordPress
 * @license Proprietary
 * @link http://www.handbid.com/
 * @author Master of Code (worldclass@masterofcode.com)
 */


if(!$this->get('profile'))
    return;

$auction = $this->get('auction');
$profile = $this->get('profile');
?>
<div id="bidder-info-load" class="bidder-info-load"
     data-profile-paddle-number="<?php echo $auction->currentPaddleNumber; ?>"
     data-auction="<?php echo (int) $auction->id; ?>"
     data-auction-status="<?php echo $auction->status; ?>"
     data-auction-name="<?php echo esc_js($auction->name); ?>"
     data-auction-key="<?php echo $auction->key; ?>"
     data-auction-image="<?php echo "http://" . HANDBID_IMAGES_HOST . $auction->imageUrl; ?>"
     data-auction-organization-key="<?php echo $auction->organization->key; ?>"
     data-auction-organization-name="<?php echo $auction->organization->name; ?>"
     data-profile-id="<?php echo (int) $profile->id; ?>"
     data-load="<?php echo wp_create_nonce("bidder-".date("Y.m.d"));?>"
     data-paddle-nonce="<?php echo apply_filters("handbid_create_nonce", date("d.m.Y") . "add_paddle");?>">

    <?php
    echo do_shortcode("[handbid_bidder_profile_bar  auction='".$auction->id."' isinitialloading='1']");
    ?>

</div>