<?php
if (!is_null($this->get('bids'))) {
    $bids    = $this->get('bids');
    $auction = $this->get('auction');
} else {
    echo "I could not find you max bids.";
    return;
}

?>
<div class="bidder-info-container">
    <?php
    if (count($bids) > 0) {
        ?>

        <table class="bidder-table">
            <thead>
            <tr>
                <th>Max Amount</th>
                <th>Item</th>
                <th colspan="2">Action</th>
            </tr>
            </thead>
            <?php
            forEach ($bids as $bid) {
                ?>
                <tr>
                    <td>
                        <?php echo '$' . $bid->maxAmount; ?>
                    </td>
                    <td>
                        <a href="/auctions/<?php echo $auction->key; ?>/item/<?php echo $bid->meta['itemKey']; ?>"><?php echo $bid->name; ?></a>
                    </td>
                    <td>
                        <a class="button greenButton" href="/auctions/<?php echo $auction->key; ?>/item/<?php echo $bid->meta['itemKey']; ?>">View</a>
                    </td>
                    <td>
                        <a class="button greenButton" href="#" data-handbid-delete-proxy="<?php echo $bid->_id; ?>"><?php echo __('Delete'); ?></a>
                    </td>
                </tr>
            <?php
            }

            ?>
        </table>

    <?php
    } else {
        ?>
        <tr>
            <td>
                <?php echo __('You do not have any active max bids'); ?>
            </td>
        </tr>
    <?php
    }
    ?>
</div>