<?php
if (!is_null($this->get('bids'))) {
    $bids = $this->get('bids');
} else {
    echo "I could not find you max bids.";
    return;
}

?>

<table class="bidder-table">
    <thead>
    <tr>
        <th>Max Amount</th>
        <th>Item</th>
        <th>Change</th>
    </tr>
    </thead>
    <?php forEach ($bids as $bid) {
        ?>
        <tr>
            <td>
                <?php echo '$' . $bid->maxAmount; ?>
            </td>
            <td>
                <?php echo $bid->name; ?>
            </td>
            <td>
                <a href="#" data-handbid-delete-proxy="<?php echo $bid->_id; ?>"><?php echo __('Delete'); ?></a>
            </td>
        </tr>
    <?php
    }
    ?>

</table>