<?php
if ($this->get('bids')) {
    $bids = $this->get('bids');
} else {
    echo "You must be logged in to view your proxy bids.";
    return;
}

?>

<table class="bidder-table">
    <thead>
    <tr>
        <th>Max Amount</th>
        <th>Item</th>
    </tr>
    </thead>
    <?php forEach ($bids as $bid) {
        ?>
        <tr>
            <td>
                <?php echo '$' . $bid->maxAmount; ?>
            </td>
            <td>
                <?php echo $bid->name; ?>
            </td>
            <td>
                <a href="#"><?php __('Delete'); ?></a>
            </td>
        </tr>
    <?php
    }
    ?>

</table>