<?php
if (!is_null($this->get('purchases'))) {
    $purchases = $this->get('purchases');
} else {
    echo "I could not find your purchases.";
    return;
}

//Total	Item	Price Per Item	Quantity
?>

<table class="bidder-table">
    <thead>
    <tr>
        <th>Total</th>
        <th>Item</th>
        <th>Price Per Item</th>
        <th>Quantity</th>
    </tr>
    </thead>
    <?php
    if(count($purchases) > 0) {

        forEach($purchases as $item) {
        ?>
            <tr>
                <td>
                    <?php echo '$' . $item->grandTotal; ?>
                </td>
                <td>
                    <?php echo $item->name; ?>
                </td>
                <td>
                    <?php echo '$' . $item->pricePerItem; ?>
                </td>
                <td>
                    <?php echo $item->quantity; ?>
                </td>
            </tr>
        <?php
        }
    }
    else
    {
        ?>
        <tr>
            <td>
                <?php echo __('You have not purchased any items'); ?>
            </td>
        </tr>
    <?php
    }
    ?>

</table>