<?php
if (!is_null($this->get('purchases'))) {
    $purchases = $this->get('purchases');
} else {
    echo "I could not find your purchases.";
    return;
}
?>

<div class="bidder-info-container">
    <?php
    if (count($purchases) > 0) {

        ?>

        <table class="bidder-table">
            <thead>
            <tr>
                <th>Total</th>
                <th>Item</th>
                <th>Price Per Item</th>
                <th>Quantity</th>
            </tr>
            </thead>
            <?php

            forEach ($purchases as $item) {
                ?>
                <tr>
                    <td>
                        <?php echo '$' . $item->grandTotal; ?>
                    </td>
                    <td>
                        <?php echo $item->name; ?>
                    </td>
                    <td>
                        <?php echo '$' . $item->pricePerItem; ?>
                    </td>
                    <td>
                        <?php echo $item->quantity; ?>
                    </td>
                </tr>
            <?php
            }
            ?>
        </table>
    <?php
    } else {
        ?>
        <tr>
            <td>
                <?php echo __('You have not purchased any items'); ?>
            </td>
        </tr>
    <?php
    }
    ?>
</div>