<?php
/**
 * @copyright Copyright (c) 2014-2015 Handbid Inc.
 * @category handbid
 * @package Handbid2-WordPress
 * @license Proprietary
 * @link http://www.handbid.com/
 * @author Master of Code (worldclass@masterofcode.com)
 */

$invoices = $this->get("myInvoices");
$profile = $this->get("profile");
$creditCards = $profile->creditCards;
$coinsCount = 0;
$groupDivider = ",";
$coinsDivider = ".";

foreach ($invoices as $i => $invoice) {
    foreach ($invoice->lineItems as $li => $lineItem) {
        unset($invoices[$i]->lineItems[$li]->bidder);
    }
}

?>

<ul class="simple-list">
    <?php if (count($invoices) > 0) {
        forEach ($invoices as $invoice) {

            ?>
            <li class="row receiptRow margin-bottom <?php echo ($invoice->paid) ? "open" : "preview"; ?>"
                data-receipt-block-id="<?php echo $invoice->id; ?>"
                data-receipt-block-guid="<?php echo $invoice->receiptsGuid; ?>"
                >
                <div class="col-md-10">
                    <h4 class="invoice-title margin-bottom"><?php echo $invoice->name; ?></h4>
                </div>
                <div class="col-md-2">
                    <a class="cta-link" data-toggle-invoice-link="<?php echo $invoice->id; ?>">View</a>
                </div>
                <div class="col-md-12 invoice-details-container" style="display: none;">

                    <?php
                    $currency = $invoice->currencySymbol;
                    $auctionItems = [];
                    $purchaseItems = [];
                    $auctionTotal = 0;
                    $purchaseTotal = 0;
                    foreach ($invoice->lineItems as $lineItem) {
                        if ($lineItem->item->isDirectPurchaseItem) {
                            $purchaseItems[] = $lineItem;
                            $purchaseTotal += (int) $lineItem->grandTotal;
                        } else {
                            $auctionItems[] = $lineItem;
                            $auctionTotal += (int) $lineItem->grandTotal;
                        }
                    }?>
                    <table class="table  table-receipt-summary ">
                        <tbody>
                        <tr>
                            <th scope="row">Auction Total</th>
                            <td class="format-money"><?php echo $currency . "<em>" . number_format($auctionTotal, $coinsCount, $coinsDivider, $groupDivider) . "</em>";?></td>
                        </tr>
                        <tr>
                            <th scope="row">Purchase Total</th>
                            <td class="format-money"><?php echo $currency . "<em>" . number_format($purchaseTotal, $coinsCount, $coinsDivider, $groupDivider) . "</em>";?></td>
                        </tr>
                        <tr class="receipt-total">
                            <th scope="row">Subtotal</th>
                            <td class="format-money"><?php echo $currency . "<em>" . number_format($invoice->subTotal / 100, $coinsCount, $coinsDivider, $groupDivider) . "</em>";?></td>
                        </tr>
                        <tr>
                            <th scope="row"><?php echo $invoice->taxLabel;?></th>
                            <td class="format-money"><?php echo $currency . "<em>" . number_format($invoice->taxRate / 100, $coinsCount, $coinsDivider, $groupDivider) . "</em>";?></td>
                        </tr>
                        <tr class="receipt-due">
                            <th scope="row" class="total">Balance Due</th>
                            <td class="receipt-total format-money text-red" data-attribute="grandTotal"><?php echo $currency . "<em>" . number_format($invoice->grandTotal / 100, $coinsCount, $coinsDivider, $groupDivider) . "</em>";?></td>
                        </tr>
                        </tbody>
                    </table>

                    <?php if(!((bool) $invoice->paid)){?>
                        <div class="unpaidControls">
                    <div class="col-md-12 margin-bottom">
                            <div class="col-md-3">
                                <a class="buy-now green-solid-button receipt-action-button col-md-12 loading-span-button"
                                    ><span>Print Receipt</span></a> </div>
                            <div class="col-md-3">
                                <a class="buy-now green-solid-button receipt-action-button col-md-12 loading-span-button"
                                    ><span>Email Receipt</span></a> </div>
                            <div class="col-md-3">
                                <a class="buy-now green-solid-button receipt-action-button col-md-12 loading-span-button"
                                    ><span>Text Receipt</span></a> </div>
                    </div>

                    <div class="col-md-12  margin-bottom receipt-payment-block">
                            <div class="col-md-6">
                                <select class="select-payment-card col-md-12" style="<?php echo (!count($creditCards)) ? " display:none; " : "" ; ?>">
                                    <?php
                                    if(count($creditCards)){
                                        foreach($creditCards as $i => $creditCard){
                                            echo "<option data-option-val='".$creditCard->id."' value='".$creditCard->id."' ".selected($i, 0, false).">".$creditCard->nameOnCard . " (xxxx xxxx xxxx ".$creditCard->lastFour.")</option>";
                                        }
                                    }
                                    ?>
                                </select>
                            </div>
                            <div class="col-md-3">
                                <a class="buy-now green-solid-button receipt-action-button make-payment-button col-md-12 loading-span-button"
                                   data-auction-id="<?php echo $invoice->auctionId; ?>"
                                   data-receipt-id="<?php echo $invoice->id; ?>"
                                   data-make-payment-nonce="<?php echo apply_filters("handbid_create_nonce", date("d.m.Y") . "make_receipt_payment");?>"
                                   data-handbid-credit-cards-need
                                   <?php if(!count($creditCards)){?> data-handbid-credit-cards-required <?php } ?>
                                    ><span>Make Payment</span></a>
                            </div>
                    </div>
                    </div>
                    <?php }?>

                    <div class="col-md-12 margin-bottom paidControls" style="<?php echo (!((bool) $invoice->paid))?" display:none; ":"";?>">
                        <div class="col-xs-12 col-md-6 col-xs-offset-0 col-md-offset-3">
                            <a class="buy-now green-solid-button receipt-action-button col-md-12 loading-span-button"
                                ><span>Paid In Full</span></a> </div>
                    </div>


                    <div class="col-md-12">
                        <a class="cta-link margin-bottom" data-toggle-invoice-more-link="<?php echo $invoice->id; ?>">More Details</a>
                    </div>

                    <div class="item-1-col row col-md-12 invoice-more-details-container" style="display: none;">

                        <?php if($auctionTotal){?>
                        <div class="receipt">
                            <h4>Auction Items (<span class="format-money"><?php
                                    echo $currency . "<em>" . number_format($auctionTotal, $coinsCount, $coinsDivider, $groupDivider) . "</em>";
                                    ?></span>)</h4>

                            <div id="w0" class="grid-view">
                                <table class="table table-striped table-bordered">
                                    <thead>
                                    <tr>
                                        <th>Item Code</th>
                                        <th>Item Name</th>
                                        <th>Market Value</th>
                                        <th>Category</th>
                                        <th>Bid</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <?php
                                    foreach ($auctionItems as $auctionItem) {
                                        echo '<tr data-key="' . $auctionItem->item->id . '">
                                        <td>' . $auctionItem->item->itemCode . '</td>
                                        <td>' . $auctionItem->item->name . '</td>
                                        <td class="format-money">' . (($auctionItem->item->value) ? $currency . "<em>" .  number_format($auctionItem->item->value, $coinsCount, $coinsDivider, $groupDivider) : "--") . "</em>". '</td>
                                        <td>' . $auctionItem->item->categoryName . '</td>
                                        <td class="format-money">' . $currency . "<em>" .  number_format($auctionItem->grandTotal, $coinsCount, $coinsDivider, $groupDivider) . "</em>". '</td>
                                    </tr>';
                                    }
                                    ?>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <?php }?>
                        <?php if($purchaseTotal){?>
                        <div class="receipt">
                            <h4>Purchases (<span class="format-money"><?php
                                    echo $currency . "<em>" . number_format($purchaseTotal, $coinsCount, $coinsDivider, $groupDivider) . "</em>";
                                    ?></span>)</h4>

                            <div id="w1" class="grid-view">
                                <table class="table table-striped table-bordered">
                                    <thead>
                                    <tr>
                                        <th>Item Code</th>
                                        <th>Item Name</th>
                                        <th>Quantity</th>
                                        <th>Unit Price</th>
                                        <th>Total</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <?php
                                    foreach ($purchaseItems as $purchaseItem) {
                                        echo '<tr data-key="' . $purchaseItem->item->id . '">
                                        <td>' . $purchaseItem->item->itemCode . '</td>
                                        <td>' . $purchaseItem->item->name . '</td>
                                        <td>' . $purchaseItem->quantity . '</td>
                                        <td class="format-money">' . $currency . "<em>" .  number_format($purchaseItem->pricePerItem, $coinsCount, $coinsDivider, $groupDivider) . "</em>" . '</td>
                                        <td class="format-money">' . $currency . "<em>" .  number_format($purchaseItem->grandTotal, $coinsCount, $coinsDivider, $groupDivider)  . "</em>" . '</td>
                                    </tr>';
                                    }
                                    ?>

                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <?php }?>

                    </div>
            </li>
        <?php
        }
    } else {
        ?>
        <p>No Receipts/Invoices found..</p>
    <?php
    }
    ?>
</ul>