<?php
/**
 * @copyright Copyright (c) 2014-2015 Handbid Inc.
 * @category handbid
 * @package Handbid2-WordPress
 * @license Proprietary
 * @link http://www.handbid.com/
 * @author Master of Code (worldclass@masterofcode.com)
 */

$invoices = $this->get("myInvoices");
$profile = $this->get("profile");
$invoicePage = $this->get("invoicePage");
$creditCards = $profile->creditCards;
$coinsCount = 2;
$groupDivider = ",";
$coinsDivider = ".";
?>

<ul class="simple-list">
    <?php
    if (!empty($invoices) && is_array($invoices)) {

        forEach ($invoices as $invoice) {
            $currency = $invoice->currencySymbol;
            $auctionItems = [];
            $purchaseItems = [];
            $redemptionInstructions = [];
            $auctionTotal = 0;
            $purchaseTotal = 0;
            $itemTax = 0;
            foreach ($invoice->lineItems as $lineItem) {
                if ($lineItem->item->isDirectPurchaseItem) {
                    $purchaseItems[] = $lineItem;
                    $purchaseTotal += (int)$lineItem->grandTotal;
                } else {
                    $auctionItems[] = $lineItem;
                    $auctionTotal += (int)$lineItem->grandTotal;
                }
                if(!empty($lineItem->item->redemptionInstructions)){
                    $redemptionInstructions[] = [
                        'name' => $lineItem->item->name,
                        'note' => $lineItem->item->redemptionInstructions,
                    ];
                }
                $itemTax += ($lineItem->tax)?$lineItem->tax:0;
            }
            ?>
            <li class="row receiptRow margin-bottom <?php echo ($invoice->paid) ? "open" : "preview"; ?>
                <?php echo ($invoice->enableCreditCardSupport == "1")?"":" invoiceNoCCAllowed "?>"
                <?php echo $invoice->enableCreditCardSupport; ?>
                data-receipt-block-id="<?php echo $invoice->id; ?>"
                data-receipt-of-auction="<?php echo $invoice->auctionId; ?>"
                data-receipt-block-guid="<?php echo $invoice->receiptsGuid; ?>"
                data-receipt-total="<?php echo number_format($invoice->grandTotal / 100, $coinsCount, $coinsDivider, $groupDivider); ?>"
                >
                <?php if($invoicePage){?>
                    <div class="col-md-12">
                        <h3 class="margin-bottom"><?php echo $invoice->name; ?></h3>
                    </div>
                <?php }else{?>
                    <div class="col-md-10">
                        <h4 class="invoice-title margin-bottom"><?php echo $invoice->name; ?></h4>
                    </div>
                    <div class="col-md-2">
                        <a class="cta-link" data-toggle-invoice-link="<?php echo $invoice->id; ?>">View</a>
                    </div>
                <?php }?>
                <div class="col-md-12 invoice-details-container" style="<?php echo ($invoicePage) ? '' : 'display: none;'; ?>">

                    <table class="table  table-receipt-summary ">
                        <tbody>
                        <tr>
                            <th scope="row">Auction Total</th>
                            <td class="format-money"><?php echo $currency . "<em>" . number_format($auctionTotal, $coinsCount, $coinsDivider, $groupDivider) . "</em>"; ?></td>
                        </tr>
                        <tr>
                            <th scope="row">Purchase Total</th>
                            <td class="format-money"><?php echo $currency . "<em>" . number_format($purchaseTotal, $coinsCount, $coinsDivider, $groupDivider) . "</em>"; ?></td>
                        </tr>
                        <tr class="receipt-total">
                            <th scope="row">Subtotal</th>
                            <td class="format-money"><?php echo $currency . "<em>" . number_format($invoice->subTotal / 100, $coinsCount, $coinsDivider, $groupDivider) . "</em>"; ?></td>
                        </tr>
                        <tr>
                            <th scope="row"><?php echo $invoice->taxLabel; ?></th>
                            <td class="format-money"><?php echo $currency . "<em>" . number_format($invoice->tax / 100, $coinsCount, $coinsDivider, $groupDivider) . "</em>"; ?></td>
                        </tr>
                        <?php if($itemTax){?>
                        <tr>
                            <th scope="row">Item Tax</th>
                            <td class="format-money"><?php echo $currency . "<em>" . number_format($itemTax / 100, $coinsCount, $coinsDivider, $groupDivider) . "</em>"; ?></td>
                        </tr>
                        <?php }?>
                        <tr class="receipt-due">
                            <th scope="row" class="total">TOTAL</th>
                            <td class="receipt-total format-money text-red"
                                data-attribute="grandTotal"><?php echo $currency . "<em>" . number_format($invoice->grandTotal / 100, $coinsCount, $coinsDivider, $groupDivider) . "</em>"; ?></td>
                        </tr>
                        <?php if(!($invoice->paid) and $invoice->amountPaid > 0){?>
                            <tr class="unpaidRows">
                                <th scope="row">Already Paid</th>
                                <td class="format-money"
                                    data-attribute="grandTotal"><?php echo $currency . "<em>" . number_format($invoice->amountPaid / 100, $coinsCount, $coinsDivider, $groupDivider) . "</em>"; ?></td>
                            </tr>
                            <tr class="receipt-due unpaidRows">
                                <th scope="row" class="total">LEFT</th>
                                <td class="receipt-total format-money text-red"
                                    data-attribute="grandTotal"><?php echo $currency . "<em>" . number_format(($invoice->grandTotal - $invoice->amountPaid) / 100, $coinsCount, $coinsDivider, $groupDivider) . "</em>"; ?></td>
                            </tr>
                        <?php }?>
                        </tbody>
                    </table>
                    <div class="row">
                    <div class="col-xs-12 margin-bottom share-receipt-controls">
                        <div class="col-xs-6 col-md-3">
                            <a class="buy-now green-solid-button receipt-action-button col-xs-12 loading-span-button"
                               onclick="handbid_main.sendInvoice('<?php echo $invoice->id; ?>','<?php echo $profile->email; ?>', false)"
                            ><span>Email Receipt</span></a></div>
                        <div class="col-xs-6 col-md-3">
                            <a class="buy-now green-solid-button receipt-action-button col-xs-12 loading-span-button"
                               onclick="handbid_main.sendInvoice('<?php echo $invoice->id; ?>','<?php echo $profile->userCellPhone; ?>', true)"
                            ><span>Text Receipt</span></a></div>
                    </div>
                    </div>
                    <?php if (!((bool)$invoice->paid)) { ?>
                        <div class="unpaidControls row">


                            <div class="col-xs-12 col-md-12  margin-bottom receipt-payment-block hideIfNoCCAllowed">
                                <div class="col-xs-12 col-sm-6">
                                    <select class="select-payment-card col-xs-12 col-md-12"
                                            style="<?php echo (!count($creditCards)) ? " display:none; " : ""; ?>">
                                        <?php
                                        if (count($creditCards)) {
                                            foreach ($creditCards as $i => $creditCard) {
                                                echo "<option data-option-val='" . $creditCard->id . "' value='" . $creditCard->id . "' " . selected($i, 0, false) . ">" . $creditCard->nameOnCard . " (xxxx xxxx xxxx " . $creditCard->lastFour . ")</option>";
                                            }
                                        }
                                        ?>
                                    </select>
                                </div>
                                <div class="col-xs-6 col-sm-3">
                                    <a class="button green-solid-button handbid-modal-link add-credit-card-to-receipt col-xs-12" data-handbid-modal-key="credit-card-form">
                                        Add Credit Card</a>
                                </div>
                                <div class="col-xs-6 col-sm-3">
                                    <a class="buy-now green-solid-button receipt-action-button make-payment-button col-xs-12 loading-span-button"
                                       data-auction-id="<?php echo $invoice->auctionId; ?>"
                                       data-receipt-id="<?php echo $invoice->id; ?>"
                                       data-make-payment-nonce="<?php echo apply_filters("handbid_create_nonce", date("d.m.Y") . "make_receipt_payment"); ?>"
                                       data-handbid-credit-cards-need
                                        <?php if (!count($creditCards)) { ?> data-handbid-credit-cards-required <?php } ?>
                                        <?php if (isset($invoice->requireAddresstoPay) and intval($invoice->requireAddresstoPay)) { ?> data-require-address-to-pay <?php } ?>
                                        ><span>Make Payment</span></a>
                                </div>
                            </div>

                            <div class="col-xs-12 col-md-12  margin-bottom receipt-payment-block showIfNoCCAllowed">
                                <div class="col-xs-12 col-md-12">
                                    <h4>Payments have been disabled through the site.<br>Contact the auction manager to pay.</h4>
                                </div>
                            </div>
                        </div>
                    <?php } ?>
                    <div class="row">
                        <div class="col-xs-12 margin-bottom paidControls"
                             style="<?php echo (!((bool)$invoice->paid)) ? " display:none; " : ""; ?>">
                            <div class="col-xs-6 col-xs-offset-3">
                                <span class="buy-now green-solid-button receipt-action-button col-xs-12"
                                    ><span>Paid In Full</span></span></div>
                        </div>
                    </div>


                    <div class="col-md-12">
                        <a class="cta-link margin-bottom" data-toggle-invoice-more-link="<?php echo $invoice->id; ?>">Toggle
                            Details</a>
                    </div>

                    <div class="item-1-col row col-md-12 invoice-more-details-container"  style="<?php echo ($invoicePage) ? '' : 'display: none;'; ?>">

                        <?php
                        if ($auctionTotal) { ?>
                            <div class="receipt">
                                <h4>Auction Items (<span class="format-money"><?php
                                        echo $currency . "<em>" . number_format($auctionTotal, $coinsCount, $coinsDivider, $groupDivider) . "</em>";
                                        ?></span>)</h4>

                                <div id="w0" class="grid-view">
                                    <table class="table table-striped table-bordered">
                                        <thead>
                                        <tr>
                                            <th>Item Code</th>
                                            <th>Item Name</th>
                                            <th>Market Value</th>
                                            <th class="hide-in-mobile">Category</th>
                                            <th>Bid</th>
                                            <th class="hide-in-mobile">Tax</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        <?php
                                        foreach ($auctionItems as $auctionItem) {
                                            echo '<tr data-key="' . $auctionItem->item->id . '">
                                        <td>' . $auctionItem->item->itemCode . '</td>
                                        <td>' . $auctionItem->item->name . '</td>
                                        <td class="format-money">' . (($auctionItem->item->value) ? $currency . "<em>" . number_format($auctionItem->item->value, $coinsCount, $coinsDivider, $groupDivider) : "--") . "</em>" . '</td>
                                        <td class="hide-in-mobile" >' . $auctionItem->item->categoryName . '</td>
                                        <td class="format-money">' . $currency . "<em>" . number_format($auctionItem->grandTotal, $coinsCount, $coinsDivider, $groupDivider) . "</em>" . '</td>
                                        <td class="format-money hide-in-mobile">' . $currency . "<em>" . number_format($auctionItem->tax / 100, $coinsCount, $coinsDivider, $groupDivider) . "</em>" . '</td>
                                    </tr>';
                                        }
                                        ?>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        <?php } ?>
                        <?php if ($purchaseTotal) { ?>
                            <div class="receipt">
                                <h4>Purchases (<span class="format-money"><?php
                                        echo $currency . "<em>" . number_format($purchaseTotal, $coinsCount, $coinsDivider, $groupDivider) . "</em>";
                                        ?></span>)</h4>

                                <div id="w1" class="grid-view">
                                    <table class="table table-striped table-bordered">
                                        <thead>
                                        <tr>
                                            <th>Item Code</th>
                                            <th>Item Name</th>
                                            <th class="hide-in-mobile">Quantity</th>
                                            <th class="hide-in-mobile">Unit Price</th>
	                                        <th class="hide-in-mobile">ItemTax</th>
                                            <th>Total</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        <?php
                                        foreach ($purchaseItems as $purchaseItem) {
                                            echo '<tr data-key="' . $purchaseItem->item->id . '">
                                        <td>' . $purchaseItem->item->itemCode . '</td>
                                        <td>' . $purchaseItem->item->name . '</td>
                                        <td class="hide-in-mobile" >' . $purchaseItem->quantity . '</td>
                                        <td class="format-money hide-in-mobile">' . $currency . "<em>" . number_format($purchaseItem->pricePerItem, $coinsCount, $coinsDivider, $groupDivider) . "</em>" . '</td>
                                        <td class="format-money hide-in-mobile">' . $currency . "<em>" . number_format($purchaseItem->tax / 100, $coinsCount, $coinsDivider, $groupDivider) . "</em>" . '</td>
                                        <td class="format-money">' . $currency . "<em>" . number_format($purchaseItem->grandTotal, $coinsCount, $coinsDivider, $groupDivider) . "</em>" . '</td>
                                    </tr>';
                                        }
                                        ?>

                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        <?php } ?>
                        <?php if ($invoicePage and !empty($redemptionInstructions)) { ?>
                            <div class="receipt">
                                <h4>
                                    Important Information About Your Items</h4>

                                <div id="w1" class="grid-view">
                                    <table class="table table-striped table-bordered">
                                        <thead>
                                        <tr>
                                            <th>Item Name</th>
                                            <th>Instruction</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        <?php
                                        foreach ($redemptionInstructions as $redemptionInstruction) {
                                            ?>
                                            <tr>
                                                <td><?php echo $redemptionInstruction['name']?></td>
                                                <td><?php echo $redemptionInstruction['note']?></td>
                                            </tr>
                                            <?php
                                        }
                                        ?>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        <?php } ?>

                    </div>
            </li>
        <?php
        }
    } else {
        ?>
        <p>You don't have any invoices! Buy or bid in the auction and we'll generate one for you</p>
    <?php
    }
    ?>
</ul>