<?php
/**
 * @copyright Copyright (c) 2014-2015 Handbid Inc.
 * @category handbid
 * @package Handbid2-WordPress
 * @license Proprietary
 * @link http://www.handbid.com/
 * @author Master of Code (worldclass@masterofcode.com)
 */


$profile    = $this->get('profile');
    $auctionCurrent    = $this->get('auction');
    $winning    = $this->get('winning');
    $losing     = $this->get('losing');
    $redirect   = $this->get('redirect');
    $myAuctions = $this->get('myAuctions');
$myInvoices = $this->get('myInvoices');
$myMessages = $this->get('notifications');
$unpaidInvoices = 0;
if(count($myInvoices)){
    foreach($myInvoices as $invoice){
        if(! $invoice->paid){
            $unpaidInvoices++;
        }
    }
}
?>

<div class="col-md-2 col-xs-12 bidder-image-wrapper">
    <?php
    $image = $profile->imageUrl;
    if(trim($image)){
    if(strpos($image, "http") === false){
        $image = "http://".$image;
    }
    ?>
    <img src="<?php echo $image; ?>" class="bidder-image"/>
    <?php }?>
    <div class="slider-nav" data-slider-nav-id="bidder-dashboard-inner">
        <a data-slider-nav-key="user-profile" class="edit-picture">Edit Pic</a>
    </div>
</div>
<div class="col-md-3 col-xs-12">
    <ul class="quick-links slider-nav auto-open" data-slider-nav-id="bidder-dashboard-inner">
        <li><a data-slider-nav-key="user-profile">User Profile</a></li>
        <li><a data-slider-nav-key="update-credit-card">Update Credit Card</a></li>
        <li><a data-slider-nav-key="see-my-auctions">See My Auctions</a></li>
        <li><a data-slider-nav-key="bidder-notifications">Messages</a></li>
        <li><a data-slider-nav-key="see-my-receipt">View Receipts/Invoices <span class="badge unpaidInvoicesCountContainer" style="<?php echo ($unpaidInvoices)?"":"display:none;";?>"><?php echo $unpaidInvoices;?></span></a></li>
        <li><a href="/organizations">Find an Organization</a></li>
        <li><a href="/auctions">Find an Auction</a></li>
        <li><a href="/handbid-logout">Logout</a></li>
    </ul>
</div>

<div class="col-md-7 col-xs-12">
    <div class="slider-content" data-slider-nav-id="bidder-dashboard-inner">

        <div class="" data-slider-nav-key="user-profile" data-slider-href="">
            <?php echo do_shortcode('[handbid_bidder_profile_form redirect="' . $redirect . '"]'); ?>
        </div>

        <div class="" data-slider-nav-key="update-credit-card">
            <?php echo do_shortcode('[handbid_bidder_credit_cards]'); ?>
        </div>

        <div class="" data-slider-nav-key="see-my-auctions">
            <div class="active-auctions-list-area" data-nonce="<?php echo apply_filters("handbid_create_nonce", date("d.m.Y") . "get_active_auctions");?>">
            <?php
                echo $this->partial('active-auctions.phtml', [
                    'myAuctions' => $myAuctions,
                ]);?>
            </div>

        </div>
        <div class="" data-slider-nav-key="bidder-notifications">
            <div class="messages-list-area" data-nonce="<?php echo apply_filters("handbid_create_nonce", date("d.m.Y") . "get_messages");?>">
            <?php
            echo $this->partial('notifications.phtml', [
                'notifications' => $myMessages,
            ]);?>
            </div>
        </div>
        <div class="" data-slider-nav-key="see-my-receipt">
            <div class="receipts-list-area" data-nonce="<?php echo apply_filters("handbid_create_nonce", date("d.m.Y") . "get_invoices");?>">
                <?php
                echo $this->partial('receipt.phtml', [
                    'profile'    => $profile,
                    'auction'    => $auctionCurrent,
                    'myInvoices' => $myInvoices,
                ]);?>
            </div>
        </div>
    </div>
</div>