<?php
if($this->context[0]) {
    $categories = $this->context[0];
    $items = $this->context[1];
}
else
{
    echo "No Auction Set";
    return;
}

?>


<div class="auctionItemListWidget">

    <!-- Filtering Side Bar -->
    <div class="sideBar">
        <div class="sectionHeading">Auction Name Items</div>

        <label>Show Items:</label>
        <ul>
            <li><a href="#">All Items</a></li>
            <li><a href="#">For Sale</a></li>
            <li><a href="#">Live</a></li>
            <li><a href="#">Extended</a></li>
            <li><a href="#">No Bids</a></li>
            <li><a href="#">Favorites</a></li>
        </ul>

        <label>Categories:</label>
        <ul>
            <?php

                forEach($categories as $category) {
                    ?>
                    <li><a href="#"><?= $category['name']; ?></a></li>
                    <?php
                }

            ?>
        </ul>

        <label>Price Ranges:</label>
        <ul>
            <li><a href="#">0 - 100</a></li>
            <li><a href="#">100 - 250</a></li>
            <li><a href="#">250 - 500</a></li>
            <li><a href="#">> 500</a></li>
        </ul>
    </div>

    <!-- Item List -->
    <div class="itemList">

        <div class="FilterBar">
            <label>Filter By:</label>
            <select>
                <option value="price-range">Price Range</option>
                <option value="price-range">1</option>
                <option value="price-range">2</option>
            </select>

            <select>
                <option value="price-range">Donor</option>
                <option value="price-range">1</option>
                <option value="price-range">2</option>
            </select>


            <select>
                <option value="price-range">Category</option>
                <option value="price-range">1</option>
                <option value="price-range">2</option>
            </select>

            <select>
                <option value="price-range">Bids</option>
                <option value="price-range">1</option>
                <option value="price-range">2</option>
            </select>

            <select>
                <option value="price-range">Type</option>
                <option value="price-range">1</option>
                <option value="price-range">2</option>
            </select>

            <a href="#">Clear Filters</a>
        </div>
        <ul class="items">
            <?php forEach($items as $item) {
                ?>

                <li class="item">
                    <a href="#">
                        <div class="topContainer" style="background-image:url(<?= $item['images'][0]; ?>)">
                            <div class="price">
                                <?= $item['currentPrice']; ?>
                            </div>
                                <span class="bidIncrement">
                                    Bid Increment:
                                    <span class="amount"><?= $item['bidIncrement']; ?></span>
                                </span>
                        </div>
                        <div class="description">
                            <div class="itemCode">
                                <?= __('Item Code') . ' : ' . $item['itemCode']; ?>
                            </div>
                            <div class="itemName">
                                <?= $item['name']; ?>
                            </div>
                            <div class="itemCategory">
                                <?= $item['currentPrice']; ?>
                            </div>
                        </div>
                        <div class="bottomBar">
                                <span class="totalBids">
                                    <?= __('Bids') . ' : ' . $item['_restMetaData']['totalBids']; ?>
                                </span>
                                <span class="totalFavorites">
                                    Favorites: 20
                                </span>
                                <span class="totalViews">
                                    Views: 222
                                </span>
                        </div>
                    </a>
                </li>
                <?php
            } ?>
        </ul>
    </div>
</div>

