<div class="auctionItemListWidget">

    <!-- Filtering Side Bar -->
    <div class="sideBar">
        <div class="sectionHeading">Auction Name Items</div>

        <label>Show Items:</label>
        <ul>
            <li><a href="#">All Items</a></li>
            <li><a href="#">For Sale</a></li>
            <li><a href="#">Live</a></li>
            <li><a href="#">Extended</a></li>
            <li><a href="#">No Bids</a></li>
            <li><a href="#">Favorites</a></li>
        </ul>

        <label>Categories:</label>
        <ul>
            <li><a href="#">Dining (12)</a></li>
            <li><a href="#">Floral (3)</a></li>
            <li><a href="#">Hotels (4)</a></li>
            <li><a href="#">Kids and Family (11)</a></li>
        </ul>

        <label>Price Ranges:</label>
        <ul>
            <li><a href="#">0 - 100</a></li>
            <li><a href="#">100 - 250</a></li>
            <li><a href="#">250 - 500</a></li>
            <li><a href="#">> 500</a></li>
        </ul>
    </div>

    <!-- Item List -->
    <div class="itemList">

        <div class="FilterBar">
            <label>Filter By:</label>
            <select>
                <option value="price-range">Price Range</option>
                <option value="price-range">1</option>
                <option value="price-range">2</option>
            </select>

            <select>
                <option value="price-range">Donor</option>
                <option value="price-range">1</option>
                <option value="price-range">2</option>
            </select>


            <select>
                <option value="price-range">Category</option>
                <option value="price-range">1</option>
                <option value="price-range">2</option>
            </select>

            <select>
                <option value="price-range">Bids</option>
                <option value="price-range">1</option>
                <option value="price-range">2</option>
            </select>

            <select>
                <option value="price-range">Type</option>
                <option value="price-range">1</option>
                <option value="price-range">2</option>
            </select>

            <a href="#">Clear Filters</a>
        </div>
        <ul class="items">
            <li class="item">
                <a href="#">
                    <div class="topContainer" style="background-image:url('../images/xyz.jpg');">
                        <div class="price">
                            $255
                        </div>
                                <span class="bidIncrement">
                                    Bid Increment:
                                    <span class="amount">$10</span>
                                </span>
                    </div>
                    <div class="description">
                        <div class="itemCode">
                            Item Code: 201
                        </div>
                        <div class="itemName">
                            AWS Titanium Driver
                        </div>
                        <div class="itemCategory">
                            Sports
                        </div>
                    </div>
                    <div class="bottomBar">
                                <span class="totalBids">
                                    Bids: 22
                                </span>
                                <span class="totalFavorites">
                                    Favorites: 20
                                </span>
                                <span class="totalViews">
                                    Views: 222
                                </span>
                    </div>
                </a>
            </li>


            <li class="item">
                <a href="#">
                    <div class="topContainer" style="background-image:url('../images/xyz.jpg');">
                        <div class="price">
                            $255
                        </div>
                                <span class="bidIncrement">
                                    Bid Increment:
                                    <span class="amount">$10</span>
                                </span>
                    </div>
                    <div class="description">
                        <div class="itemCode">
                            Item Code: 201
                        </div>
                        <div class="itemName">
                            AWS Titanium Driver
                        </div>
                        <div class="itemCategory">
                            Sports
                        </div>
                    </div>
                    <div class="bottomBar">
                                <span class="totalBids">
                                    Bids: 22
                                </span>
                                <span class="totalFavorites">
                                    Favorites: 20
                                </span>
                                <span class="totalViews">
                                    Views: 222
                                </span>
                    </div>
                </a>
            </li>
            <li class="item">
                <a href="#">
                    <div class="topContainer" style="background-image:url('../images/xyz.jpg');">
                        <div class="price">
                            $255
                        </div>
                                <span class="bidIncrement">
                                    Bid Increment:
                                    <span class="amount">$10</span>
                                </span>
                    </div>
                    <div class="description">
                        <div class="itemCode">
                            Item Code: 201
                        </div>
                        <div class="itemName">
                            AWS Titanium Driver
                        </div>
                        <div class="itemCategory">
                            Sports
                        </div>
                    </div>
                    <div class="bottomBar">
                                <span class="totalBids">
                                    Bids: 22
                                </span>
                                <span class="totalFavorites">
                                    Favorites: 20
                                </span>
                                <span class="totalViews">
                                    Views: 222
                                </span>
                    </div>
                </a>
            </li>
            <li class="item">
                <a href="#">
                    <div class="topContainer" style="background-image:url('../images/xyz.jpg');">
                        <div class="price">
                            $255
                        </div>
                                <span class="bidIncrement">
                                    Bid Increment:
                                    <span class="amount">$10</span>
                                </span>
                    </div>
                    <div class="description">
                        <div class="itemCode">
                            Item Code: 201
                        </div>
                        <div class="itemName">
                            AWS Titanium Driver
                        </div>
                        <div class="itemCategory">
                            Sports
                        </div>
                    </div>
                    <div class="bottomBar">
                                <span class="totalBids">
                                    Bids: 22
                                </span>
                                <span class="totalFavorites">
                                    Favorites: 20
                                </span>
                                <span class="totalViews">
                                    Views: 222
                                </span>
                    </div>
                </a>
            </li>
            <li class="item">
                <a href="#">
                    <div class="topContainer" style="background-image:url('../images/xyz.jpg');">
                        <div class="price">
                            $255
                        </div>
                                <span class="bidIncrement">
                                    Bid Increment:
                                    <span class="amount">$10</span>
                                </span>
                    </div>
                    <div class="description">
                        <div class="itemCode">
                            Item Code: 201
                        </div>
                        <div class="itemName">
                            AWS Titanium Driver
                        </div>
                        <div class="itemCategory">
                            Sports
                        </div>
                    </div>
                    <div class="bottomBar">
                                <span class="totalBids">
                                    Bids: 22
                                </span>
                                <span class="totalFavorites">
                                    Favorites: 20
                                </span>
                                <span class="totalViews">
                                    Views: 222
                                </span>
                    </div>
                </a>
            </li>
        </ul>
    </div>
</div>

