<?php
if ($this->context[0] && $this->context[1]) {
    $categories = $this->context[0];
    $items      = $this->context[1];
    $donors     = array_unique($items);
} else {
    echo "No Categories / Items Found";
    return;
}

?>

<div class="auctionItemListWidget">

    <!-- Filtering Side Bar -->
    <div class="sideBar">
        <div class="sectionHeading"><?= __('Auction Items'); ?></div>

        <label><?= __('Show Items'); ?> :</label>
        <ul>
            <li><a href="#">All Items</a></li>
            <li><a href="#">For Sale</a></li>
            <li><a href="#">Live</a></li>
            <li><a href="#">Extended</a></li>
            <li><a href="#">No Bids</a></li>
            <li><a href="#">Favorites</a></li>
        </ul>

        <label><?= __('Categories'); ?>:</label>
        <ul>
            <?php

            forEach ($categories as $category) {
                ?>
                <li><a href="#"><?= $category['name']; ?></a></li>
            <?php
            }

            ?>
        </ul>

        <label><?= __('Price Ranges'); ?>:</label>
        <ul>
            <li><a href="#">0 - 100</a></li>
            <li><a href="#">100 - 250</a></li>
            <li><a href="#">250 - 500</a></li>
            <li><a href="#">> 500</a></li>
        </ul>
    </div>

    <!-- Item List -->
    <div class="itemList">

        <div class="FilterBar">
            <label><?= __('Filter By'); ?> :</label>
            <select>
                <option value="price-range">Price Range</option>
                <option value="price-range">1</option>
                <option value="price-range">2</option>
            </select>

            <select>
                <option value="price-range">Donor</option>
                <?php
                forEach ($donors as $donor) {
                    ?>
                    <option value="<?= $donor['_id']; ?>"><?= $donor['name']; ?></option>
                <?php
                }
                ?>
            </select>


            <select>
                <option value="all">Categories</option>
                <?php
                forEach ($categories as $category) {
                    ?>
                    <option value="<?= $category['_id']; ?>"><?= $category['name']; ?></option>
                <?php
                }
                ?>
            </select>

            <select>
                <option value="price-range">Bids</option>
                <option value="price-range">1</option>
                <option value="price-range">2</option>
            </select>

            <select>
                <option value="price-range">Type</option>
                <option value="price-range">1</option>
                <option value="price-range">2</option>
            </select>

            <a href="#"><?= __('Clear Filters'); ?></a>
        </div>
        <ul class="items">
            <?php forEach ($items as $item) { ?>
                <li class="item">
                    <a href="#">
                        <div class="topContainer" style="background-image:url(<?= $item['images'][0]; ?>)">
                            <div class="price">
                                <?= $item['currentPrice']; ?>
                            </div>
                            <span class="bidIncrement">
                                <?= __('Bid Incremenet'); ?> :
                                <span class="amount"><?= $item['bidIncrement']; ?></span>
                            </span>
                        </div>
                        <div class="description">
                            <div class="itemCode">
                                <?= __('Item Code') . ' : ' . $item['itemCode']; ?>
                            </div>
                            <div class="itemName">
                                <?= $item['name']; ?>
                            </div>
                            <div class="itemCategory">
                                <?= $item['currentPrice']; ?>
                            </div>
                        </div>
                        <div class="bottomBar">
                            <span class="totalBids">
                                <?= __('Bids') . ' : ' . $item['_restMetaData']['totalBids']; ?>
                            </span>
                            <span class="totalFavorites">
                                <?= __('Favorites'); ?> : 20
                            </span>
                            <span class="totalViews">
                                <?= __('Views'); ?> : 222
                            </span>
                        </div>
                    </a>
                </li>
            <?php } ?>
        </ul>
    </div>
</div>

