<?php
if ($this->get('auction')) {
    $auction = $this->get('auction');
    $location = $auction->location;
    if (isset($auction->meta)) {
        $org = $auction->meta->organization;
    }

} else {
    echo "No Auction Set";
    return;
}

$dateFormat = 'm/d/Y h:i a';
$url = get_permalink() . '?auction=' . get_query_var('auction');

?>

<div class="bannerContainer parallax" style="background-image: url('<?php echo $auction->banner; ?>');">
    <div class="innerBanner">
        <div class="statusContainer">
            <div class="name">
                <div class="auctionName">
                    <a href="/auction-detail?auction=<?php echo $auction->key; ?>"><?php echo $auction->name; ?></a>
                </div>
                <a class="orgTitle" href="/organization?organization=<?php echo $org->key; ?>"><?php echo $org->name; ?></a>
            </div>
            <?php if ($auction->status != "closed") {
                if (isset($auction->closingTime)) { ?>
                    <div class="timeRemaining"><?php echo __('Auction closes in ') . $auction->closingTime; ?></div>
                <?php }
                else {
                    ?>
                    <div class="status <?php echo $auction->status; ?>"><?php echo __('Auction is') . ' ' . $auction->status . ' ' . __('for Bidding'); ?></div>
                <?php
                }?>
            <?php
            } ?>
        </div>
        <div class="highlightImage">
            <div class="highlightImageInner" style="background-image: url('<?php echo $auction->logo->medium; ?>');"></div>
        </div>
        <div class="socialLinks">
            <a class="facebook"
               href="https://www.facebook.com/sharer/sharer.php?u=<?php htmlspecialchars($url, ENT_QUOTES); ?>"
               title="Share on Facebook." target="_blank">Facebook</a>
            <a class="twitter"
               href="http://twitter.com/home/?status=<?php echo urlencode($auction->name); ?> - <?php echo $url; ?>"
               title="Tweet this!" target="_blank">Twitter</a>

            <a class="gplus" href="https://plus.google.com/share?url=<?php the_permalink(); ?>" onclick="javascript:window.open(this.href,
          '', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=600,width=600');return false;">Google+</a>
        </div>

        <!-- banner overlay information -->
        <div>
<!--    <div class="bannerContentOverlay">-->
<!--        <div class="eventsAndDetails">-->
<!--            <div class="detailsWrapper">-->
<!--                <ul class="eventDetails">-->
<!---->
<!--                    <li>--><?php //echo date(
//                            $dateFormat,
//                            $auction->startTime
//                        ); ?><!-- - --><?php //echo date($dateFormat, $auction->endTime); ?><!--</li>-->
<!--                    <li>--><?php //echo $auction->vanityAddress; ?><!--</li>-->
<!--                    <li>--><?php //echo $location->full; ?><!--</li>-->
<!--                </ul>-->
<!---->
<!--            </div>-->
<!--        </div>-->
<!--    </div>-->
        </div>

        <div class="actionBar">
            <a class="modalLink contactButton" href="#modal1"><span><?php echo __('Help'); ?></span></a>
            <a href="#" class="register"><span><?php echo __('Register'); ?></span></a>
            <a href="#" class="buyTickets"><span><?php echo __('Tickets'); ?></span></a>
        </div>
    </div>

    <div class="heroOverlay"></div>
    <div class="statBar">
        <div class="innerStatBar">
            <div class="listStats">
                <div class="animated auctionImage" style="background-image: url('<?php echo $auction->logo->small; ?>');">
                </div>
                <div class="statBox auctionName">
                    <span><?php echo $auction->name; ?></span>
                </div>
                </div>
                <div class="statBox items">
                    <span><?php echo __('Items'); ?></span>
                    <span><?php echo $auction->meta->totalItems; ?></span>
                </div>

                <?php if ( is_user_logged_in() ) {
                ?>
                    <div class="statBox winning">
                        <span><?php echo __('Winning'); ?></span>
                        <span>Value</span>
                    </div>
                    <div class="statBox losing">
                        <span><?php echo __('Losing'); ?></span>
                        <span>Value</span>
                    </div>
                    <div class="statBox proxy">
                        <span><?php echo __('Proxy'); ?></span>
                        <span>Value</span>
                    </div>
                    <div class="statBox favorites">
                        <span><?php echo __('Favorites'); ?></span>
                        <span>Value</span>
                    </div>
                <?php } ?>
            </div>
        </div>
    </div>
</div>

<div id="modal1" class="modal">
    <h3 class="modalTitle"><?php echo __('Contact Auction Host'); ?></h3>
    <p class="closeBtn">Close</p>
    <?php echo do_shortcode('[gravityform id=1 title=false description=false]'); ?>
</div>
