<?php
if ($this->get('auction')) {

    $auction = $this->get('auction');
    $location = $auction->location;

    $categories = $this->get('categories');
    $donors = $this->get('donors');

    if (isset($auction->meta->organization)) {
        $org = $auction->meta->organization;
    }

} else {
    echo "No Auction Set";
    return;
}

// For Filter Bar
$showItems   = [
    'all'       => 'All Items',
    'forSale'   => 'For Sale',
    'live'      => 'Live',
    'extended'  => 'Extended',
    'noBids'    => 'No Bids',
    'favorites' => 'Favorites'
];
$priceRanges = [
    '_all' => 'All',
    '_0'   => '0 - 100',
    '_1'   => '101 - 250',
    '_2'   => '251 - 500',
    '_5'   => '501+'
];

$status = ($auction->status == "open") ? 'open' : 'closed';

$url = get_permalink() . '?auction=' . get_query_var('auction');

?>


<div class="bannerContainer parallax" style="background-image: url('<?php echo $auction->banner; ?>');">
    <div class="innerBanner">
        <div class="statusContainer">
            <div class="name">
                <div class="auctionName">
                    <a href="/auction-detail?auction=<?php echo $auction->key; ?>"><?php echo $auction->name; ?></a>
                </div>
                <a class="orgTitle" href="/organization?organization=<?php echo $org->key; ?>"><?php echo $org->name; ?></a>
            </div>
            <div class="highlightImage">
                <img src="<?php echo $auction->logo->medium; ?>"/>
            </div>
            <div class="bannerExtraInfo">
                <div class="auctionDate">
                    <span><?php echo date('m/d/Y',$auction->startTime); ?></span>

                </div>
                <div class="auctionTime">
                    <span><?php echo date('h:i a',$auction->startTime); ?></span>

                </div>
            </div>
        </div>
        <div class="socialLinks">
            <a class="facebook"
               href="https://www.facebook.com/sharer/sharer.php?u=<?php htmlspecialchars($url, ENT_QUOTES); ?>"
               title="Share on Facebook." target="_blank">Facebook</a>
            <a class="twitter"
               href="http://twitter.com/home/?status=<?php echo urlencode($auction->name); ?> - <?php echo $url; ?>"
               title="Tweet this!" target="_blank">Twitter</a>

            <a class="gplus" href="https://plus.google.com/share?url=<?php the_permalink(); ?>" onclick="javascript:window.open(this.href,
          '', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=600,width=600');return false;">Google+</a>
        </div>

        <div class="actionBar">
            <a class="modalLink contactButton" href="#modal1"><span><?php echo __('Help'); ?></span></a>
            <a href="#" class="register"><span><?php echo __('Register'); ?></span></a>
            <a href="#" class="buyTickets"><span><?php echo __('Tickets'); ?></span></a>
        </div>
    </div>

    <div class="heroOverlay"></div>
    <div class="statBar">
        <div class="innerStatBar">
            <div class="listStats">
                <div class="auctionImage" style="background-image: url('<?php echo $auction->logo->small; ?>');">
                </div>
                <div class="statBox auctionName">
                    <span><?php echo $auction->name; ?></span>
                </div>

                <?php if ( $this->get('profile') ) {
                ?>
                    <div class="statBox winning">
                        <label><?php echo __('Winning'); ?></label>
                        <span><?php echo $this->get('winningBids'); ?></span>
                    </div>
                    <div class="statBox losing">
                        <label><?php echo __('Losing'); ?></label>
                        <span><?php echo $this->get('losingBids'); ?></span>
                    </div>
                    <div class="statBox proxy">
                        <label><?php echo __('Proxy'); ?></label>
                        <span><?php echo $this->get('proxies'); ?></span>
                        <span>Value</span>
                    </div>
                <?php } ?>
                <div class="statBox statusBox">
                    <label><?php echo __('Status'); ?></label>
                    <span class="status <?php echo $status; ?>"><?php echo __(ucfirst($status)); ?></span>

                </div>
                <div class="statBox filterBox">
                    <button class="button"><?php echo __('Filter'); ?></button>
                </div>
            </div>
            <div class="filterBar">
                <div class="filterGroup">
                    <label class="categoryLabel"><?php echo __('Show Items'); ?> :</label>
                    <ul class="fancyRadio">
                        <?php forEach ($showItems as $k => $v) {
                            ?>
                            <li>
                                <input id="<?php echo $k; ?>" type="radio" name="category" value="<?php echo $k; ?>">
                                <label for="<?php echo $k; ?>"><?php echo __($v); ?></label>
                            </li>
                        <?php
                        }
                        ?>
                    </ul>
                </div>

                <div class="filterGroup">
                    <label class="categoryLabel"><?php echo __('Categories'); ?>:</label>
                    <ul class="categorySort fancyRadio">
                        <?php

                        forEach ($categories as $category) {
                            ?>
                            <li>
                                <input id="<?php echo sanitize_html_class($category); ?>" type="radio" name="category"
                                       value="<?php echo sanitize_html_class($category); ?>">
                                <label for="<?php echo sanitize_html_class($category); ?>"><?php echo __(
                                        ucfirst($category)
                                    ); ?></label>
                            </li>
                        <?php
                        }

                        ?>
                    </ul>
                </div>
                <div class="filterGroup">
                    <label class="categoryLabel"><?php echo __('Price Ranges'); ?>:</label>
                    <ul class="priceSort fancyRadio">
                        <?php
                        forEach ($priceRanges as $k => $v) {
                            ?>
                            <li>
                                <input id="<?php echo $k; ?>" type="radio" name="category" value="<?php echo $k; ?>">
                                <label for="<?php echo $k; ?>"><?php echo __($v); ?></label>
                            </li>
                        <?php
                        }
                        ?>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="modal1" class="modal">
    <h3 class="modalTitle"><?php echo __('Contact Auction Host'); ?></h3>
    <p class="closeBtn">Close</p>
    <?php echo do_shortcode('[gravityform id=1 title=false description=false]'); ?>
</div>
