<?php

$auction     = $this->get('auction');
$location    = $auction->locations[0];
$hasLocation = !!($location->auctionLocationStreet1);
$address     = null;
$mapsUrl     = null;
$categories  = $this->get('categories');
$categories  = $auction->categories;


$locationStreet1 = $location->auctionLocationStreet1;
$locationStreet2 = $location->auctionLocationStreet2;
$locationPCode = $location->auctionLocationPostalCode;
$locationCity = $location->auctionLocationCity;
$locationProvince = $location->province->countriesRegionsName;
$locationProvinceShort = $location->province->countriesRegionsShortName;

if ($hasLocation) {

    $address = $locationStreet1 . ', ' . $locationStreet2 . ', ' . $locationCity . ', ' . $locationProvince . ', ' . $locationPCode;
}

if (!$auction) {
    return '';
}
?>

<div class="auction-details <?php echo $auction->status; ?>" data-handbid-auction-guid="<?php echo $auction->auctionGuid; ?>" >

<div class="container container-fluid detail-banner-wrapper">
    <div class="detail-banner" style="background-image: url('<?php echo "http://" . $auction->banner; ?>')">
        <div class="logo">
            <img src="<?php echo "http://" . HANDBID_IMAGES_HOST . $auction->imageUrl; ?>"/>
        </div>
    </div>
    <div class="controls">

        <?php echo do_shortcode('[handbid_social_share]'); ?>

        <span class="buttons">
            <a href="#" class="button pink-button register" data-handbid-connect>Register</a>

            <?php if ($auction->enableTicketSales) { ?>
                <?php echo do_shortcode('[handbid_auction_ticket_list]'); ?>
            <?php } ?>

            <span class="status">
                Status<span class="status-box"></span><span class="status-label"><?php echo $auction->status; ?></span>
            </span>
            </span>


    </div>
</div>

<?php $informationFirst = (in_array($auction->status, ["preview", "presale", "closed"]));?>
<ul class="slider-nav col-md-12 auto-open" data-slider-nav-id="auction-details">
    <?php if ($auction->description and $informationFirst) { ?>
        <li>
            <a data-slider-nav-key="description">Auction Information</a>
        </li>
    <?php } ?>
    <li>
        <a data-slider-nav-key="items">Items</a>
    </li>
    <?php if ($auction->description and !$informationFirst) { ?>
        <li>
            <a data-slider-nav-key="description">Auction Information</a>
        </li>
    <?php } ?>
    <?php if ($hasLocation) { ?>
        <li>
            <a data-slider-nav-key="map">Event Details</a>
        </li>
    <?php } ?>
</ul>
<div class="slider-content" data-slider-nav-id="auction-details">

    <div class="container container-fluid" data-slider-nav-key="items">
        <div class="row">

            <div class="sticky sticky-for-sort-bar">

                <div class="sort-bar auction-item-list">

                    <div class="category-cover-cheating"></div>

                    <div class="col-md-6 col-xs-6 fancy-search-wrapper">

                        <form class="fancy-search" method="get">
                            <button type="button">Search Items</button>
                            <input class="query" type="search" name="q" placeholder="Search items"/>
                            <a class="reset" href="#" style="display: none">X</a>
                        </form>

                    </div>
                    <div class="col-md-2 col-xs-2 sort-label">Sort By:</div>
                    <div class="col-md-4 col-xs-4 select-wrapper">
                        <select name="sort">
                            <option value="_sortNameAsc">Name: A-Z</option>
                            <option value="_sortNameDesc">Name: Z-A</option>
                            <option value="_sortPriceAsc">Price: Low to High</option>
                            <option value="_sortPriceDesc">Price: High to Low</option>
                            <option value="_sortBidsAsc">Total Bids: Least to Most</option>
                            <option value="_sortBidsDesc">Total Bids: Most to Least</option>
                        </select>

                    </div>
                </div>

                <div class="clear"></div>


                <div class="mobile-filters">

                    <select name="mobile-sort">
                        <option value="_sortNameAsc">Sort By Name: A-Z</option>
                        <option value="_sortNameDesc">Name: Z-A</option>
                        <option value="_sortPriceAsc">Price: Low to High</option>
                        <option value="_sortPriceDesc">Price: High to Low</option>
                        <option value="_sortBidsAsc">Total Bids: Least to Most</option>
                        <option value="_sortBidsDesc">Total Bids: Most to Least</option>
                    </select>

                    <select name="mobile-type">
                        <option value="*">Type: All Items</option>
                        <option value="[data-for-sale]">For Sale</option>
                        <option value="[data-live]">Live</option>
                        <option value="[data-no-bids]">No Bids</option>
                    </select>

                    <select name="mobile-category">

                        <option value="*">Category: All Items</option>

                        <?php foreach ($categories as $category) {

                            if (count($category->items) > 0) {
                                ?>
                                <option value="[data-tags~='|<?php echo esc_html(
                                    sanitize_key($category->name)
                                ); ?>|']"><?php echo $category->name . ' (' . count($category->items) . ')'; ?></option>
                            <?php
                            } //end if
                        } ?>
                    </select>

                </div>

            </div>

        </div>

        <div class="row">

            <div class="col-md-2 col-sm-3 col-xs-12 sticky filter-wrapper" data-sticky-margin-top="65">

                <div class="filters">

                    <div class="section" data-section="type">
                        <h4>Items</h4>
                        <ul class="by-item-type">
                            <li data-selector="*" class="selected"><a href="#">All Items</a></li>
                            <li data-selector="[data-for-sale]"><a href="#">For Sale</a></li>
                            <li data-selector="[data-live]"><a href="#">Live</a></li>
                            <li data-selector="[data-no-bids]"><a href="#">No Bids</a></li>
                        </ul>
                    </div>

                    <div class="section" data-section="category">
                        <h4>Categories</h4>
                        <ul class="by-category">
                            <?php
                            $allCount = 0;
                            foreach ($categories as $category) {
                                $allCount += count($category->items);
                            } ?>
                            <li data-selector="*" class="selected"><a href="#">All (<?php echo $allCount; ?>)</a></li>

                            <?php foreach ($categories as $category) {

                                if (count($category->items) > 0) {
                                    ?>
                                    <li data-selector="[data-tags~='|<?php echo esc_html(
                                        sanitize_key($category->name)
                                    ); ?>|']" data-legacy-category-id="<?php echo $category->_id; ?>"><a
                                            href="#"><?php echo $category->name . ' (' . count($category->items) . ')'; ?></a>
                                    </li>
                                <?php
                                } //end if
                            } ?>

                        </ul>
                    </div>

                </div>


            </div>
            <div class="col-md-10 col-sm-9 col-xs-12">

                <?php echo do_shortcode('[handbid_auction_item_list auction="' . $auction->key . '"]'); ?>

            </div>
        </div>
    </div>

    <?php
    if ($auction->description) { ?>
        <div class="container container-fluid big-content" data-slider-nav-key="description">
            <?php echo $auction->description; ?>
        </div>
    <?php } ?>

    <?php if ($hasLocation) { ?>
        <div class="details-map" data-slider-nav-key="map" data-address="<?php echo $address; ?>">

            <div id="large-map"></div>
            <div id="small-map"></div>

        </div>
        <div style="display: none" id="map-marker-content">
            <?php if ($auction->vanityAddress) { ?>
                <div class="overflow" style="width:310px;">
                    <div class="row">
                        <div class="col-md-4 col-xs-4 iw-label">Location</div>
                        <div class="col-md-8 col-xs-8"><?php echo $auction->vanityAddress; ?></div>
                    </div>
                    <div class="row">
                        <div class="col-md-4 col-xs-4 iw-label">Address</div>
                        <div
                            class="col-md-8 col-xs-8"><?php

                            echo $locationStreet1 . ' ' . $locationStreet2 . '<br />' . $locationCity . ', ' . strtoupper(
                                    $locationProvinceShort
                                ) . ' ' . $locationPCode; ?></div>
                    </div>
                    <div class="row submit">
                        <a class="pink-button get-directions" onclick="getDirections()" href="#">Get Directions</a>
                    </div>
                </div>
            <?php } ?>
        </div>
    <?php } ?>

</div>
</div>

<?php //holy lazy piece of ...?>
<script src="https://maps.googleapis.com/maps/api/js?v=3.exp"></script>
