<?php

if ($this->context) {

    $auction  = $this->context['auction'];
    $coordinates  = $this->context['coordinates'];
} else {

    echo "No Auction Set";
    return;
}

$dateFormat = 'm/d/Y h:i a';

// @Todo Fix url w/ query params, Horrible way to do this, sorry!
$url = get_permalink() . '?auction=' . get_query_var('auction');

?>
<div class="eventsAndDetails">
    <div class="sectionHeading"><?php echo __('Auction & Event Details'); ?></div>
    <div class="socialLinks">
        <a class="facebook" href="https://www.facebook.com/sharer/sharer.php?u=<?php htmlspecialchars($url, ENT_QUOTES); ?>" title="Share on Facebook." target="_blank">Facebook</a>
        <a class="twitter" href="http://twitter.com/home/?status=<?php echo urlencode($auction->name); ?> - <?php echo $url; ?>" title="Tweet this!" target="_blank">Twitter</a>

        <a class="gplus" href="https://plus.google.com/share?url=<?php the_permalink(); ?>" onclick="javascript:window.open(this.href,
  '', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=600,width=600');return false;">Google+</a>
    </div>
    <div class="detailsWrapper">
        <ul class="eventDetails">

            <li><label><?php echo __('Event Dates') . ' : '; ?></label><?php echo date($dateFormat,$auction->startTime); ?> - <?php echo date($dateFormat,$auction->endTime); ?></li>
            <li><label><?php echo __('Event Location') . ' : '; ?></label><?php echo $auction->vanityAddress; ?></li>
            <li><label><?php echo __('Event Address') . ' : '; ?></label>
                <?php echo $coordinates->location->full; ?>
            </li>
        </ul>

        <div class="actionBar">
            <a href="#" class="register"><?php echo __('Register'); ?></a>
            <a href="#" class="buyTickets"><?php echo __('Buy Tickets'); ?></a>
        </div>
    </div>

</div>

