<div class="eventsAndDetails">
    <div class="sectionHeading">Auction & Event Details</div>
    <div class="socialLinks">
        <a href="#">Facebook</a>
        <a href="#">Twitter</a>
        <a href="#">Share</a>
    </div>
    <div class="detailsWrapper">
        <ul class="eventDetails">
            <li><label>Event Dates:</label> May 3rd - May 5th 2014</li>
            <li><label>Event Location:</label> MGM Las Vegas</li>
            <li><label>Event Address:</label> 123 Abc Street</li>
        </ul>

        <div class="actionBar">
            <a href="#" class="register">Register</a>
            <a href="#" class="buyTickets">Buy Tickets</a>
        </div>
    </div>

</div>