<?php
    $auctions = $this->get('auctions');

    $dateFormat = 'm/d/Y h:i a';
?>
<table class="auctionTable">
    <thead>
        <th><?= __('Current Auctions'); ?></th>
        <th></th>
        <th><?= __('Status'); ?></th>
        <th><?= __('Date'); ?></th>
        <th><?= __('Total Items'); ?></th>
        <th></th>
    </thead>
    <?php
    forEach($auctions as $auction) { ?>
        <tr onclick="window.location.href='/auction-detail/?auction=<?= $auction->_id; ?>'">
            <td class="cell-image cell-first">
                <img class="alignnone animated fadeIn" alt="<?= $auction->name; ?>" src="<?= $auction->image; ?>" style="opacity: 0;">
            </td>
            <td class="cell-name">
                <div class="name"><?= $auction->name; ?></div>

                <div class="vanity">
                    <?= $auction->vanityAddress; ?>
                </div>
                <div class="address">
                    <?= $auction->location->full; ?>
                </div>
            </td>
            <td class="cell-status">
                <?= $auction->status; ?>
            </td>
            <td class="cell-time">
                <div class="startDate">
                    <div class="label">
                        <?= __('Start'); ?>
                    </div>
                    <div>
                        <?= date($dateFormat,$auction->startTime); ?>
                    </div>
                </div>
                <div class="endDate">
                    <span>
                        <?= __('End'); ?>
                    </span>
                    <?= date($dateFormat,$auction->startTime); ?>
                </div>
            </td>
            <td class="cell-numItems">
                Total Items: Need Data
            </td>
            <td classs="cell-button">
                <span class="button auctionListLogo">
                    <?= __('View'); ?>
                </span>
            </td>
        </tr>
    <?php
    }
    ?>

</table>