<?php
if ($this->context) {
    $categories = $this->context['categories'];
    $items      = $this->context['items'];
    $donors     = $this->context['donors'];

    $showItems = [
        'all'       => 'All Items',
        'forSale'   => 'For Sale',
        'live'      => 'Live',
        'extended'  => 'Extended',
        'noBids'    => 'No Bids',
        'favorites' => 'Favorites'
    ];
    $priceRanges = [
        '_all' => 'All',
        '_0'   => '0 - 100',
        '_1'   => '101 - 250',
        '_2'   => '251 - 500',
        '_5'   => '501+'
    ];

} else {
    echo "No Categories / Items Found";
    return;
}

?>


<div class="auctionItemListWidget">

    <!-- Filtering Side Bar -->
    <div class="sideBar widgetContainer filterBar">
        <h3><?php echo __('Auction Items'); ?></h3>

        <label class="categoryLabel"><?php echo __('Show Items'); ?> :</label>
        <ul class="fancyRadio">
            <?php forEach($showItems as $k => $v) {
                ?>
                <li>
                    <input id="<?php echo $k; ?>" type="radio" name="category" value="<?php echo $k; ?>">
                    <label for="<?php echo $k; ?>"><?php echo __($v); ?></label>
                </li>
            <?php
            }
            ?>
        </ul>

        <label class="categoryLabel"><?php echo __('Categories'); ?>:</label>
        <ul class="categorySort fancyRadio">
            <?php

            forEach ($categories as $category) {
                ?>
                <li>
                    <input id="<?php echo sanitize_html_class($category); ?>" type="radio" name="category" value="<?php echo sanitize_html_class($category); ?>">
                    <label for="<?php echo sanitize_html_class($category); ?>"><?php echo __(ucfirst($category)); ?></label>
                </li>
            <?php
            }

            ?>
        </ul>

        <label class="categoryLabel"><?php echo __('Price Ranges'); ?>:</label>
        <ul class="priceSort fancyRadio">
            <?php
            forEach($priceRanges as $k => $v ) {
                ?>
                <li>
                    <input id="<?php echo $k; ?>" type="radio" name="category" value="<?php echo $k; ?>">
                    <label for="<?php echo $k; ?>"><?php echo __($v); ?></label>
                </li>

                <li><input type="radio" name="priceRange" value=""></li>
            <?php
            }
            ?>
        </ul>
    </div>

    <!-- Item List -->
    <div class="itemList">

        <div class="filterBar">
            <label><?php echo __('Filter By'); ?> :</label>

            <select>
                <option value="price-range">Donor</option>
                <?php
                forEach ($donors as $donor) {
                    ?>
                    <option value="<?php echo $donor->_id; ?>"><?php echo $donor->name; ?></option>
                <?php
                }
                ?>
            </select>

            <select>
                <option value="price-range">Bids</option>
                <option value="price-range">1</option>
                <option value="price-range">2</option>
            </select>

            <a class="button" href="#"><?php echo __('Clear Filters'); ?></a>
        </div>
        <ul id="container" class="items js-isotope">
            <?php forEach ($items as $item) {

                // By default no filtering is done
                $priceClass = '_all';

                if($item->currentPrice >= 0 && $item->currentPrice <= 100 ) {
                    $priceClass = '_0';
                }
                else if($item->currentPrice >= 101 && $item->currentPrice < 250) {
                    $priceClass = '_1';
                }
                else if($item->currentPrice >= 251 && $item->currentPrice < 500) {
                    $priceClass = '_2';
                }
                else if($item->currentPrice >= 501) {
                    $priceClass = '_5';
                }

                ?>
                <li class="item item-tile
<!--                --><?//= sanitize_html_class($item['_restMetaData']['categoryName']) . ' ' . $priceClass; ?><!-- -->
                all _all">
                    <a href="/auction-item/?item=<?php echo $item->_id; ?>">
                        <div class="item-content-inner">
                            <div class="image" style="background-image: url(<?php echo $item->images[0]; ?>);">
                                <div class="block currentPrice">
                                    <span><?php echo __('Current bid'); ?></span><span class="price"><?php echo '$' . $item->currentPrice; ?></span></div>
                                <div class="block itemCode"><?php echo __('Item Code') . ' : ' . $item->itemCode; ?></div>
                            </div>
                            <div class="details">
                                <h2><?php echo $item->name; ?></h2>
                                <div class="bidIncrement"><?php echo __('Bid Increment') . ': $' . $item->bidIncrement; ?></div>
                                <div class="category">Category: Sports</div>
                            </div>
                        </div>
                    </a>
                    <div class="footer">
<!--                        <div class="stat bidCount"><div class="icon"></div>--><?//= $item['_restMetaData']['totalBids']; ?><!--</div>-->
                        <div class="stat favCount"><div class="icon"></div>20</div>
                        <div class="stat viewCount"><div class="icon"></div>200</div>
                    </div>
                </li>

            <?php } ?>
        </ul>
    </div>
</div>

