<?php
if ($this->context[0] && $this->context[1]) {
    $categories = $this->context[0];
    $items      = $this->context[1];
    $donors     = array_unique($items);
} else {
    echo "No Categories / Items Found";
    return;
}

?>

<div class="auctionItemListWidget">

    <!-- Filtering Side Bar -->
    <div class="sideBar widgetContainer">
        <h3><?= __('Auction Items'); ?></h3>

        <label><?= __('Show Items'); ?> :</label>
        <ul>
            <li><a href="#">All Items</a></li>
            <li><a href="#">For Sale</a></li>
            <li><a href="#">Live</a></li>
            <li><a href="#">Extended</a></li>
            <li><a href="#">No Bids</a></li>
            <li><a href="#">Favorites</a></li>
        </ul>

        <label><?= __('Categories'); ?>:</label>
        <ul>
            <?php

            forEach ($categories as $category) {
                ?>
                <li><a href="#"><?= $category['name']; ?></a></li>
            <?php
            }

            ?>
        </ul>

        <label><?= __('Price Ranges'); ?>:</label>
        <ul>
            <li><a href="#">0 - 100</a></li>
            <li><a href="#">100 - 250</a></li>
            <li><a href="#">250 - 500</a></li>
            <li><a href="#">> 500</a></li>
        </ul>
    </div>

    <!-- Item List -->
    <div class="itemList">

        <div class="FilterBar">
            <label><?= __('Filter By'); ?> :</label>
            <select>
                <option value="price-range">Price Range</option>
                <option value="price-range">1</option>
                <option value="price-range">2</option>
            </select>

            <select>
                <option value="price-range">Donor</option>
                <?php
                forEach ($donors as $donor) {
                    ?>
                    <option value="<?= $donor['_id']; ?>"><?= $donor['name']; ?></option>
                <?php
                }
                ?>
            </select>


            <select>
                <option value="all">Categories</option>
                <?php
                forEach ($categories as $category) {
                    ?>
                    <option value="<?= $category['_id']; ?>"><?= $category['name']; ?></option>
                <?php
                }
                ?>
            </select>

            <select>
                <option value="price-range">Bids</option>
                <option value="price-range">1</option>
                <option value="price-range">2</option>
            </select>

            <select>
                <option value="price-range">Type</option>
                <option value="price-range">1</option>
                <option value="price-range">2</option>
            </select>

            <a href="#"><?= __('Clear Filters'); ?></a>
        </div>
        <ul id="container" class="items">
            <?php forEach ($items as $item) { ?>
                <li class="item item-tile">
                    <a href="/auction-item/?item=<?= $item['_id']; ?>">
                        <div class="item-content-inner">
                            <div class="image" style="background-image: url(<?= $item['images'][0]; ?>);">
                                <div class="block currentPrice">
                                    <span><?= __('Current bid'); ?></span><?= '$' . $item['currentPrice']; ?></div>
                                <div class="block itemCode"><?= __('Item Code') . ' : ' . $item['itemCode']; ?></div>
                            </div>
                            <div class="details">
                                <h2><?= $item['name']; ?></h2>
                                <div class="bidIncrement"><?= __('Bid Increment') . ': $' . $item['bidIncrement']; ?></div>
                                <div class="category">Category: Sports</div>
                            </div>
                        </div>
                    </a>
                    <div class="footer">
                        <div class="stat bidCount"><div class="icon"></div><?= __('Bids') . ' : ' . $item['_restMetaData']['totalBids']; ?></div>
                        <div class="stat favCount"><div class="icon"></div><?= __('Favorites'); ?> 20</div>
                        <div class="stat viewCount"><div class="icon"></div><?= __('Views'); ?> 200</div>
                    </div>
                </li>

            <?php } ?>
        </ul>
    </div>
</div>

