<div class="page-not-found center-text auction-setup-page">
    <h2 style=" font-size: 6em; ">Auction</h2>
    <h3>Under construction</h3>
    <div class="gavel-icon"
        style="
            background-image: url('<?php echo HANDBID_PLUGIN_URL;?>/public/images/AuctionUnderConstruction.jpg');
            width: 400px;
            height: 200px;
            background-size: contain;
        "
        ></div>
    <p style="font-size: 20px;">Pardon our dust while we get this auction setup for bidding!
    </p>
    <a href="/" class="button green-solid-button">Return to home page</a>

</div>