<?php
$auctions = $this->get('auctions');
?>

<div id="showcase-full-width">
    <div class="hfeed">
        <ul id="showcase-items" class="image-grid isotope">
            <?php
            forEach ($auctions as $auction) {
                ?>
                <li class="twocol showcase-item clearfix term-6">
                    <article class="portfolio type-portfolio">
                        <div class="image-area animated fadeInUp" style="opacity: 0;">
                            <a title="<?php echo $auction->name; ?>" href="/auction-detail/?auction=<?php echo $auction->key; ?>">
                                <img class="thumbnail" src="<?php echo $auction->logo->medium; ?>" alt="<?php echo $auction->name; ?>" title="<?php echo $auction->name; ?>">
                            </a>
                            <span class="image-info-buttons">
                                <a class="lightbox-link" title="<?php echo $auction->name; ?>" href="<?php echo $auction->logo->medium; ?>">
                                </a>
                            </span>

                            <div class="image-info">
                                <h3 class="post-title">
                                    <a title="<?php echo $auction->name; ?>" href="/auction-detail/?auction=<?php echo $auction->key; ?>">
                                        <?php echo $auction->name; ?>
                                    </a>
                                </h3>

                                <div class="terms">
                                    <a
                                        href="/auction-detail/?auction=<?php echo $auction->key; ?>">
                                        <div><?php echo date('m/d/Y', $auction->startTime); ?></div>
                                        <div><?php echo date('h:i a', $auction->startTime); ?></div>
                                        </a>
                                </div>
                            </div>
                        </div>
                    </article>
                </li>

            <?php
            }
            ?>
    </div>
</div>