<?php
/**
 * @copyright Copyright (c) 2014-2015 Handbid Inc.
 * @category handbid
 * @package Handbid2-WordPress
 * @license Proprietary
 * @link http://www.handbid.com/
 * @author Master of Code (worldclass@masterofcode.com)
 */

$auction = $this->get('auction');

if (!$auction) {
    return;
}

?>
<div class="auction-timer row" data-handbid-timer style="display: none;">

    <div class="col-xs-3 col-md-3 indicator-wrapper">
        <canvas data-handbid-timer-indicator class="indicator" width="60" height="60"></canvas>
    </div>

    <div class="col-xs-3 col-md-3 hours section">

        <div class="amount" data-handbid-timer-label="hours">
            0

        </div>
        <div class="the-label">Hours</div>

    </div>

    <div class="col-xs-3 col-md-3 minutes section">

        <div class="amount" data-handbid-timer-label="minutes">
            0
        </div>
        <div class="the-label">Mins</div>

    </div>

    <div class="col-xs-3 col-md-3 seconds section">

        <div class="amount" data-handbid-timer-label="seconds">
            0
        </div>
        <div class="the-label">Secs</div>

    </div>


</div>