<?php

$auction = $this->get('auction');

if (!$auction || !$auction->closingTime) {
    return;
}

?>
<div class="auction-timer row" data-handbid-timer style="display: none;">

    <div class="col-md-3">
        <canvas data-handbid-timer-indicator class="indicator" width="60" height="60"></canvas>
    </div>

    <div class="col-md-3 hours section">

        <div class="amount" data-handbid-timer-label="hours">
            0
        </div>
        <div class="the-label">Hours</div>

    </div>

    <div class="col-md-3 minutes section">

        <div class="amount" data-handbid-timer-label="minutes">
            0
        </div>
        <div class="the-label">Mins</div>

    </div>

    <div class="col-md-3 seconds section">

        <div class="amount" data-handbid-timer-label="seconds">
            0
        </div>
        <div class="the-label">Secs</div>

    </div>


</div>